### ISSUE TITLE
Crash/hang for some numpy arrays?

### ISSUE THREAD

**Issue by h-vetinari** [serge-sans-paille/pythran#1011]
I'm struggling with problems related to #842 and was working on test-cases to isolate the behaviour, when I stumbled across a bug that seems very weird to me.

Two almost identical arrays - one runs without problems, the other crashes. The difference must be very subtle, because every aspect I could think of checking is exactly equal.

I'm on latest commit as of yesterday (https://github.com/serge-sans-paille/pythran/commit/bb977467e42a36d393df6bad4d3a459d86defbb9), Windows 10, Python 3.6.6, MSVC 2017 Community 15.8.2, IPython 6.5.0.

Test function:
```
%%pythran
#pythran export myfunc(float[][])
#pythran export myfunc(float[::,:])
import numpy as np

def myfunc(x):
    numpoints = x.shape[0]
    res = np.zeros((numpoints, 2), dtype=float)
    for i in range(numpoints):
        res[i, 0] = x[i, :].min()
        res[i, 1] = x[i, :].max()
    return res
```

Execution:
The first call always runs successfully (with any combination of uncommenting the lines for `x`), and the second always hangs or crashes -- *unless* `df = df.astype(float)` is commented out (note that this command shouldn't do anything as `xx` gets cast to `float` in any case!).
```
import pandas as pd 
import numpy as np
N = 20
df = pd.DataFrame(np.random.randint(1e3, 2e3, (N, 6)),
                  columns=['x1', 'x2', 'x3', 'y1', 'y2', 'y3'])
x = df.filter(regex='x').astype(float).values
# x = np.asfortranarray(x)
# x = np.ascontiguousarray(x)
# x = x.copy()
print(myfunc(x)[0])
print('works!')

df = df.astype(float) # without this line, things run fine
xx = df.filter(regex='x').astype(float).values

print(f'dtype equal:   {x.dtype == xx.dtype}', f'strides equal: {x.strides == x.strides}',
      f'shape equal:   {x.shape == xx.shape}', f'flags equal:   {x.flags == xx.flags}',
      f'values equal:  {(x == xx).all(axis=None)}', sep='\n')
myfunc(xx) # either hangs or crashes!
```

**Comment by h-vetinari** [comment]
@serge-sans-paille Has this been reproducible for you, or did I manage to make a mistake somewhere?

**Comment by serge-sans-paille** [comment]
I just checked and saw a nice message on stdout: 

```
reshaped array are not supported
```

and I get a crash on the second one. So yes! I can reproduce

**Comment by serge-sans-paille** [comment]
@h-vetinari please confirm #1014 fixes your issue. If so I'm releasing after the merge.

**Comment by h-vetinari** [comment]
@serge-sans-paille Can confirm that #1014 fixes this. Thanks a lot for the quick response!
