### ISSUE TITLE
Compilation fails on np.diff() (Linux and macOS)

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1015]
I'm getting a compilation failure on this simple code:
```
import numpy as np
#pythran export testFunc()
def testFunc():
    S = np.ones((40,200))
    SF = np.zeros(S.shape)     # This breaks
    #SF = np.zeros((40,200))  # This works
    DS = np.diff(SF, axis=1)
    return DS, S
```
Using the current head (99d8234f) of master on both Linux and MacOS.

**Comment by serge-sans-paille** [comment]
thanks @jeanlaroche. I can reproduce the problem, which is fairly easy: we d'ont support the axis argument for ``np.diff``. i'll fix that.

**Comment by jeanlaroche** [comment]
Awesome thank!
J.
