### ISSUE TITLE
Compilation bug on selection of return values

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1017]
This is a minor bug as it's very easy to work around it, but nonetheless it would be good if this didn't crash....
```
import numpy as np
#pythran export testFunc()
def testFunc():
    x=2
    y=3
    z=4
    return x,y,z

#pythran export testFunc2()
def testFunc2():
    x,y = testFunc()[0:2]  # <- this crashes
    return x,y
```

**Comment by serge-sans-paille** [comment]
Fixed by #1019 (?)

**Comment by jeanlaroche** [comment]
Alas no:
`E: Invalid subscripting of `Tuple[int, T0, T1]` by `slice` (B1017.py, line 12)`

**Comment by serge-sans-paille** [comment]
Should be now fixed, thanks for reporting!
