### ISSUE TITLE
TypeError: Invalid call to pythranized function when calling with param x[:,None]

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1025]
Consider the function below. 
```
import numpy as np

#pythran export test(float[][] or float[::][::])
def test(x):
    return np.max(x)
```
If you call `test(np.zeros(2000,2))` everything's fine, but if you call with `test(np.zeros(2000)[:,None])` you get the usual error:
```
TypeError: Invalid call to pythranized function `test(float64[:, :] (reshaped))'
Candidates are:

    - test(float[:,:])
    - test(float[::,::])
```
This despite the fact that np.zeros(2000)[:,None] has a shape of (2000,1). The problem is that np.zeros(2000)[:,None].strides is (8,0) and that trips up the verification code. Artificially setting the strides to (8,8) fixes the problem.

**Comment by serge-sans-paille** [comment]
Yeah, as noted in the comment, this has been reshaped and is currently not supported. I should be able to workaround that.

**Comment by serge-sans-paille** [comment]
@ashwinvis & @jeanlaroche #1048 should be an improvment there.

**Comment by ashwinvis** [comment]
I confirm that @jeanlaroche 's test case works with #1048.

**Comment by jeanlaroche** [comment]
Yes, I confirm it's now fixed.
