### ISSUE TITLE
Compare to cython and nuitka

### ISSUE THREAD

**Issue by KOLANICH** [serge-sans-paille/pythran#1046]

**Comment by serge-sans-paille** [comment]
Can you elaborate? Are you expecting a documentation entry that explains the difference between the approcahes, some benchmarks, anything else?

**Comment by KOLANICH** [comment]
Yes. Especially performance comparison.

**Comment by KOLANICH** [comment]
Thank you for the answer.

**Comment by serge-sans-paille** [comment]
Great, feel free to close the issue then ;-)
