### ISSUE TITLE
Error at runtime: TypeError and "reshaped"

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1049]
I got this strange error on a cluster with a code which works on other computers:

```
TypeError: Invalid call to pythranized function
`dealiasing_setofvar(complex128[:, :, :] (reshaped), uint8[:, :], int, int)'
Candidates are:

     - dealiasing_setofvar(complex128[:,:,:], uint8[:,:], int, int)
```

It is normal ? What does it exactly mean? I didn't find anything in the doc...

**Comment by serge-sans-paille** [comment]
> It is normal ? What does it exactly mean? I didn't find anything in the doc...

Yes, it's normal, altohough I'm trying to improve the situation. All the
magic lies in the ``(reshaped)`` which basically means that the
parameter as the good dimensions, but it's wrapping a reshpaed array, or
a sliced view...

Can you give me more info about the callsite?

Oh, and #1048 may solve your issue. If so, please tell me!

**Comment by serge-sans-paille** [comment]
cc @ashwinvis #1048 has been merged in master, does that close this issue?

**Comment by serge-sans-paille** [comment]
@ashwinvis up.

**Comment by ashwinvis** [comment]
I am unsure of this error, only @paugier knows exactly how to reproduce this.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by paugier** [comment]
I close this issue because it is unclear how to reproduce it and it could be that #1048 solves the problem.
