### ISSUE TITLE
Packaging bug on Fedora and packaging example?

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1053]
I went in Brest to work with fluidsim_ocean developers. We had many problems, and most of them were related to Pythran :-)

In particular, we didn't manage to compile Pythran extensions on a Fedora machine with this silly but annoying error: `g++: error: mypackage/mod_pythran.cpp: No such file or directory`. We tried with fluidfft and fluidsim and nothing worked.

The C++ files are created by Pythran but cannot be found to create the extension!

Then, I thought "we have to try with a serious project using Pythran" but I didn't know what to use and there is nothing on examples of usages of Pythran in the doc (see #1055 ).

Then, I thought "Is there an example package which shows how to use Pythran?" but I think the answer is no...

Then, I thought "I have to write this example" and I did it (see https://bitbucket.org/fluiddyn/example_package_fluidpythran) but using fluidpythran because it was easier and because I anyway needed to have that. The good thing is that we are indeed able to reproduce the bug on Fedora (see [this issue](https://bitbucket.org/fluiddyn/example_package_fluidpythran/issues/1/bug-fedora-conda-pythran)).

@serge-sans-paille do you understand this problem? Do you think I did something wrong with `PythranBuildExt` and `PythranExtension`?

**Comment by paugier** [comment]
Of course, I don't get the problem on my computers (on Ubuntu and Debian).

To reproduce (see [this issue for the error log](https://bitbucket.org/fluiddyn/example_package_fluidpythran/issues/1/bug-fedora-conda-pythran)):

```
conda create --name toto -c conda-forge python=3.6
conda activate toto
conda install numpy pythran
pip install -e hg+https://bitbucket.org/fluiddyn/example_package_fluidpythran#egg=example_package_fluidpythran -v  --no-cache-dir
python -m example_package_fluidpythran
```

I'm going to ask Sylvie if she gets the same problem with your test examples.

**Comment by serge-sans-paille** [comment]
yeah, that's how it's usually done. looks like for some reason, the `cwd` changes at some point... Maybe we could save the absolute path of the ``.cpp``? I'll prepare a branch with that patch.

**Comment by serge-sans-paille** [comment]
ok, that does not work, trying something else...

**Comment by serge-sans-paille** [comment]
I just tried a fresh fedora install and run the above command, everything compiles gracefully. Inside a virtual env (not a conda env).

**Comment by serge-sans-paille** [comment]
And tried through conda too: everything works fine. Maybe it's an issue related to the Ifremer environment?

**Comment by serge-sans-paille** [comment]
@paugier : pythran is now packaged on fedora, does it solve the issue?

**Comment by serge-sans-paille** [comment]
I Assume this is fixed now, three years of Pythran within Fedora should be enough of a test.
