### ISSUE TITLE
Examples of usages of Pythran in the documentation

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1055]
I propose that some words could be added in Pythran's documentation to list examples of usages of Pythran. When I encountered [a problem with building a package using Pythran](https://github.com/serge-sans-paille/pythran/issues/1053), I would have liked to try with another packages and I didn't find what to use.

### Which packages use Pythran?

On PyPI: https://pypi.org/search/?q=pythran

- fluidpythran
- fluidimage
- fluidsim
- pyLBM (Loic Gouarin)
- triflow (Nicolas Cellier)

However, I know that fluidfft also uses Pythran and it is not listed, so I guess one needs to mention Pythran in the README to be in this list. So there may be other projects using Pythran?

On Github, it's not really better.

- https://github.com/boileaum/phypso

### Pythran is not used enough...

I conclue from this search that Pythran is not used enough to write Python packages for scientific computing.

It seems to me that Pythran is now nearly ready to be used "in production" in serious projects. Having more users (and in particular serious projects) would be very good for Pythran (and for all early-adopter projects already using it).

I am aware of the work done with Scipy developers (see https://mail.python.org/pipermail/scipy-dev/2018-January/022325.html, https://mail.python.org/pipermail/scipy-dev/2018-May/022837.html and
https://github.com/scipy/scipy/pull/8306). I see that Scipy developers would prefer to use Pythran within Cython, which is understandable for them. However, for most packages, it would be simpler and better to use Pythran without Cython.

For many usecases (when no need to interface with non-Python code), Pythran has big advantages compared to Cython:

- Pure Python-Numpy-Scipy code
- high level code easier to maintain
- all this with good performance (with SIMD and OpenMP)

I mean if maintainers of scientific Python packages would have to chose today what to use, Pythran is for many cases technically the right solution.

It could be interesting to have the same approach you had with the PR on Scipy (https://github.com/scipy/scipy/pull/8306) with other packages, for example:

- scikit-learn
- scikit-image
- astropy
- ...

**Comment by serge-sans-paille** [comment]
As extra information, I know that Pythran is used in a few private context too: @jeanlaroche and @diorcety both use Pythran extensively as part of their job. It is also used in several CNRS entities, internally.

The [scikit image PR](https://github.com/scikit-image/scikit-image/pull/3226) is on stand-by, I should probably focus on this. Astropy looks like a good candidate too, you're right.

**Comment by serge-sans-paille** [comment]
@paugier some doc in #1070. This covers the basics.

**Comment by serge-sans-paille** [comment]
@martibosch thanks for reporting. It's probably related to the `.pythran` file, let me check that.

**Comment by martibosch** [comment]
yes it is indeed. Either the `.pythran` file is included in the `MANIFEST`, either the pythran signatures are included directly on the `.py` files. I have gone for the second option and tested it in Test PyPI and it appears to work (I will release the fix soon). If it is of more help, this repository was also useful: https://github.com/ElofssonLab/pyGaussDCA

In any case, thank you very much for your hint. I hope that my repository can also serve as an example PyPI package for pythran (which futher includes automated PyPI deployment via Travis CI).

Cheers.

**Comment by serge-sans-paille** [comment]
@martibosch do you mean that once the `*.pythran` files are included in the `MANIFEST`, the bug no longer shows?

**Comment by martibosch** [comment]
I have gone for the easy way and I have not actually tried the `.pythran` file approach. I will try it in TestPyPI and come back with an answer in some minutes.

**Comment by martibosch** [comment]
it seems to work. I have moved the pythran signature from the `.py` back to the `.pythran` file, added a line `include pylandstats/*.pythran` in the `MANIFEST.in`, and uploaded to Test PyPI. You might give it a try it as in `pip install --no-cache-dir --extra-index-url https://test.pypi.org/simple/ pylandstats==0.7.3` (note that you do not even need to have pythran installe)
