### ISSUE TITLE
extend pythran (statistical distributions)

### ISSUE THREAD

**Issue by RalphFS** [serge-sans-paille/pythran#1063]
Would it be possible to integrate statistical distributions into Pythran? In Cython, for example, you can use the GSL package or wrap the [Rmath-julia library](https://github.com/JuliaStats/Rmath-julia). It would be great to have access to these distributions from Pythran.

..to make the question more general: Is it theoretically possible to use Cython functions from within Pythran or to call Pythran functions from Cython? I know that there is the Cython: np_pythran=True feature but that's not what I mean. 
I was just wondered if I could possibly replace a Cython cdef function with a Pythran function and maybe compile the Cython function in c++ via "distutils: language = c++".
This would make Cython easier and in many cases faster while at the same time increasing the area of application of Pythran enormously since external C/C++ libraries could also be used.

**Comment by serge-sans-paille** [comment]
hi RaphFS,
the only way to achieve that goal is through `capsule`. The documentation about its usage in pythran is not very verbose (see http://serge-sans-paille.github.io/pythran-stories/the-capsule-corporation.html) but that's a good opportunity to improve it :-)

**Comment by serge-sans-paille** [comment]
BTW please note that if the distribution is part of ``numpy.random``, we should just add support for it in Pythran. Please name them :-)

**Comment by serge-sans-paille** [comment]
As of capsule usage, here is an example with gsl:

```
"""
callsite.py - demonstrates advanced capsule usage
"""
import ctypes

PyCapsule_New = ctypes.pythonapi.PyCapsule_New
PyCapsule_New.restype = ctypes.py_object
PyCapsule_New.argtypes = ctypes.c_void_p, ctypes.c_char_p, ctypes.c_void_p

ctypes.CDLL('/usr/lib/x86_64-linux-gnu/libgslcblas.so.0', mode=ctypes.RTLD_GLOBAL)
gsl = ctypes.CDLL('/usr/lib/x86_64-linux-gnu/libgsl.so.23', mode=ctypes.RTLD_GLOBAL)
gsl_cdf_ugaussian_Pinv = gsl.gsl_cdf_ugaussian_Pinv
gsl_cdf_ugaussian_Pinv.restype = ctypes.c_double
gsl_cdf_ugaussian_Pinv.argtypes = ctypes.c_double,

capsule = PyCapsule_New(gsl_cdf_ugaussian_Pinv, "double(double)", None)

from pythranized import callback

print(callback(capsule, 0.3))
```

And the pythran file:

```
"""
pythranized.py - using capsule from pythran
"""
#pythran export callback(float64(float64), float64)

def callback(cdf_ugaussian_Pinv, val):
    return cdf_ugaussian_Pinv(val)
```

**Comment by serge-sans-paille** [comment]
@paugier you might be interested in this one.

**Comment by serge-sans-paille** [comment]
Everything explained in the doc associated to #1070
