### ISSUE TITLE
Getting TypeError in Jupyter notebooks when running Pythran

### ISSUE THREAD

**Issue by dxm447** [serge-sans-paille/pythran#1086]
If I run the following on my Jupyter notebook
`import pythran`
`%load_ext pythran.magic`
`%%pythran`
`#pythran export pi_approximate_pythran(int)`
`import numpy as np`
`def pi_approximate_pythran(n):`
`    step = 1.0 / n`
`    result = 0`
`    for i in range(n):`
`        x = (i + 0.5) * step`
`        result += 4.0 / (1.0 + x * x)`
`    return step * result`
I get the following error (I am running Pythran 0.8.7 on a Python3.5 kernel. I have gcc and g++ installed through conda in my system.):
```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-067586d5c0b5> in <module>
TypeError: 'method' object is not iterable

**Comment by dxm447** [comment]
I am attaching the full error output

[ErrorOutput.txt](https://github.com/serge-sans-paille/pythran/files/2573650/ErrorOutput.txt)
 Also I am using Ubuntu 16.04

**Comment by serge-sans-paille** [comment]
can you try ``pip install -U  nextworkx`` ?

**Comment by serge-sans-paille** [comment]
How did you install pythran by the way? conda? pip? setup install?

**Comment by dxm447** [comment]
Hi @serge-sans-paille thanks for getting back so quickly. I tried `pip install -U networkx` and I am trying it now. I installed Pythran through conda

**Comment by dxm447** [comment]
Uninstalled Anaconda and did a clean install - and it's working great! 

By the way, I was using the Intel channels previously - so most of my packagers were the Intel packages - I do not know whether it was the cause

**Comment by serge-sans-paille** [comment]
ok, nevermind. Closing the issue then!
