### ISSUE TITLE
Raise PythranTypeError instead of TypeError ?

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1087]
It would be convenient if Pythran raise `PythranTypeError` instead of simply `TypeError`.

`PythranTypeError` should of course inherit from `TypeError`.

**Comment by serge-sans-paille** [comment]
Mmmmh, that would make the client application depend on an ``import pythran`` statement... what are you trying to achieve? Maybe we can find an other way?

**Comment by serge-sans-paille** [comment]
Some extra thoughts: that would mean adding pythran as a runtime dependency for any package using pythran, and we don't want that. One possible alternative:

```python
from foo import bar  # could be pythran code
class PythranTypeError(TypeError):
    pass

def wrap(f):
    import inspect, sys
    if not inspect.isbuiltin(f): return f
    def wrapped(*args, **kwargs):
        try:
            return f(*args, **kwargs)
        except TypeError as te:
             raise PythranTypeError, str(te), sys.exc_info()[2]
    return wrapped
    
bar = wrap(bar)
```

**Comment by paugier** [comment]
It seems to me that Pythran users could still be able to catch a `PythranTypeError` without importing pythran.

```
try:
    my_func(1, 2)
except TypeError:
    do_something()
```
would still work (since `PythranTypeError` would be a `TypeError`).

However, in some situations, we would to be able to distinguish between a standard TypeError and a PythranTypeError.

It's not very important. Here, https://bitbucket.org/fluiddyn/fluidpythran/src/ed37b22082e27e31b7cf446f23760f557915240a/fluidpythran/cached_jit.py#lines-221, I though it would be cleaner to be able to write
```
try:
    return self.pythran_func(*args, **kwargs)
except PythranTypeError:
    # need to compiled or recompile
    pass
```
because a standard `TypeError` can also be raised in the code even if there is no Pythran `TypeError`...

**Comment by serge-sans-paille** [comment]
> PythranTypeError without importing pythran.

Yeah, but that PythranTypeError would need to be defined somewhere in
the native module then, and be consistent across all modules, which
basically means some pythran runtime :/

**Comment by paugier** [comment]
Ok I may understand now...

I'm not used to think that we can use Pythran extensions without the Pythran package... but of course it's important!

So it was just a bad idea and I'll just keep the `except TypeError` :-)
