### ISSUE TITLE
Wheels for packages using Pythran (C++11)?

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1089]
To be quite universal, Python wheels for Linux have to (should) be built on manylinux (a very old OS, i.e. Centos 5).

This OS comes with an old version of gcc (I think 4.8) so it is not simple to use C++11.

I guess during your work on potentially using Pythran in Scipy, @serge-sans-paille  you thought about this issue.

Do you think it is possible (and not too difficult) to build a Linux wheel for a package using Pythran (or more generally C++11)? Do you know if it has been done before (links of examples)?

**Comment by serge-sans-paille** [comment]
I never tried before, and have no experience with wheels :-/
It does not make sense to bundle pythran as a wheel (no binary) but it does make sense for package dependeing on pythran, we should test that.

See https://github.com/pypa/manylinux/issues/118

**Comment by paugier** [comment]
In the issue you mention, it seems that the problem is with C++14 so C++11 may be less a problem.

Note that there is also manylinux2010 https://www.python.org/dev/peps/pep-0571/

Anyway, I guess we won't be able to use the system g++ so we would have to include the newer clib in the wheel. Not sure how we can do that.

CC @CyrilleBonamy

**Comment by diorcety** [comment]
I'm using manylinux with pythran 0.8.7, I have no issue at all with the standard libraries

**Comment by serge-sans-paille** [comment]
scipy wheels are built on manylinux 2010 and / or 2014 and they are built using pythran. I think we can consider this a successful test :-)
