### ISSUE TITLE
Compilation error on XX[uu,] * R[uu, None] 

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1092]
The following code does not compile in MacOS
I suspect it's related to https://github.com/serge-sans-paille/pythran/issues/924
It's also similar to https://github.com/serge-sans-paille/pythran/issues/905 but that issue is fixed (still fixed with latest I can confirm).
```
import numpy as np

#pythran export test(float)
def test(x):
    XX = np.ones((50,2))
    R = np.ones(50)
    uu = np.arange(0,50,2)
    #Y = XX * R[:, None]  # <-This works.
    Y = XX[uu,] * R[uu, None]  # <-This does not work.
    return Y
```

**Comment by serge-sans-paille** [comment]
It does compile on master, on linux, can you double check now?

**Comment by jeanlaroche** [comment]
Still fails on master on macOS. I'll post the error on rc.
