### ISSUE TITLE
Missing symbol when using function in if body

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#1093]
If you try to compile that code you have undefined symbol when running the library:
0000000000000000      D  *UND*	0000000000000000              _ZN12_GLOBAL__N_18pythonic11__builtin__4list6appendISt5tupleIJlNS0_5types4listINS5_3strEEEEEEENS5_9none_typeERNS5_10empty_listEOT_

```

missing = 1
invalid = 2

#pythran export aa(str:str dict)
def aa(headers):
    errors = []

    def add_error(type, args):
        errors.append((type, args))

    def get_header(name, type=float):
        if name in headers:
            try:
                return type(headers[name])
            except ValueError:
                add_error(invalid, [name])
                return None
        else:
            add_error(missing, [name])
            return None

    lpix = get_header('lpix')
    if lpix is not None and lpix <= 0.0:
        add_error(invalid, ['lpix'])

    #add_error(invalid, ['lpix']) # Uncomment to resolve the issue

    return (errors, (lpix, ))
```

**Comment by diorcety** [comment]
And missing implementation in https://github.com/serge-sans-paille/pythran/blob/master/pythran/pythonic/__builtin__/list/append.hpp ?

**Comment by serge-sans-paille** [comment]
It's a consequence of the type inference issue: pythran fails to infer the lis type, so it generates a call to empty_list::append, which does not exist. Indeed, if you append something to a list, then pythran should know its type because tehre's something appended to it :-)

**Comment by serge-sans-paille** [comment]
OK, I've been investigating that one quite a bit, and from type inference perspective it's a nightmare, it combines interprocedural stuff with isNone, I'll do my best but that's relatively scary.

Don't expect a solution as christmas gift ;-)

**Comment by diorcety** [comment]
That strange because i'm using almost the same kind of function pattern without having this error, I will try to track down on my side

**Comment by diorcety** [comment]
If you add the following lines before return, no more error
```
    if 'aa' not in headers:
      add_error()
```

**Comment by diorcety** [comment]
Even better:

Not working
```
if headers['ee'] is None:
       add_error()
```


Working:
```
    if headers['ee'].startswith("ee"):
       add_error()

```

Seems linked with the NoneType

**Comment by serge-sans-paille** [comment]
@diorcety ISTM that the issue if now fixed (by you) Can you confirm, and if so, close the issue? Thanks!

**Comment by diorcety** [comment]
Indeed this one is good, only #1185 remains
