### ISSUE TITLE
Issue when calling pythranized function from c++ main (MacOS)

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1094]
I'm pythranizing a simple function:
```
import numpy as np
def initState():
    A = np.zeros((10000,2))
    B = tuple([A])
    return B
```
Using pythran -e test.py so I get test.cpp and nothing more.
Then I call initState from a main.cpp file:
```
#include "test.cpp"
int main()
{
    auto state = __pythran_test::initState()();
    return 0;
}
```
Compilation has no issue, but when running main.out I get this assertion error:
```
Assertion failed: (N == v && "consistent init"), function check_type, file pythran/pythran/pythonic/include/types/tuple.hpp, line 159.
Abort trap: 6
```
If I comment out the assert in tuple.hpp, things work fine (and the rest of my program works fine as well). I'm not sure why this assert is being triggered...
MacOS.

**Comment by serge-sans-paille** [comment]
I can reproduce on linux

**Comment by serge-sans-paille** [comment]
Simpler reproducer


```
import numpy as np
def initState():
    return np.zeros((10000,))
```

**Comment by serge-sans-paille** [comment]
Fixed by #1097

**Comment by serge-sans-paille** [comment]
I'm waiting for the fft2 version now :-)

**Comment by jeanlaroche** [comment]
oh maaaan, it's a lot of work!

**Comment by jeanlaroche** [comment]
I confirm the problem is fixed in fix/pshape-type-inference... Thanks a bunch!
