### ISSUE TITLE
Large discrepancy in np.remainder (MacOS and Unix)

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1103]
The following function returns different value in python and with pythran
```
import numpy as np

#pythran export test(float)
def test(C):
    N2 = 6.0
    N = 12
    y = np.remainder(C+ N2 + 10*N, N) - N2
    return y
```
in python: test(1.) return 1.0
But the pythran version returns -11.0 (which is erroneous)

**Comment by jeanlaroche** [comment]
Simpler repro:
```
#pythran export test(float,float)
def test(x,y):
    return np.remainder(x,y)
```
Test with any negative x and positive y. The issue is that np.remainder(x,y) always has the sign of y because it's computed as x-floor(x/y)*y . Since floor(x/y)<x/y, if y>0 then floor(x/y)*y < x and x-floor(x/y)*y > 0. Similarly, if y<0 then x-floor(x/y)*y < 0.
I believe xsimd::remainder does not behave like that.

**Comment by jeanlaroche** [comment]
ugh. This is all very weird but I suppose std and xsimd use a version that returns the same absolute value whether x and or y are positive or negative (you measure the remainder toward 0 and not toward -infinity). What do you suggest should be done?

**Comment by jeanlaroche** [comment]
In the meantime, I implemented my own workaround with x/y - y*np.round(x/y)

**Comment by serge-sans-paille** [comment]
I'm testing copysign(remainder(x, y), y)

**Comment by jeanlaroche** [comment]
> I'm testing copysign(remainder(x, y), y)

Wait, that won't work. It's not just a question of sign...

**Comment by jeanlaroche** [comment]
I checked with std::remainder and std::fmod, neither can be used: std::remainder uses round(x/y) instead of floor(), and std::fmod uses int(x/y) (rounding toward 0) which again does not work.
What we need is really x - y*floor(x/y)

**Comment by serge-sans-paille** [comment]
#1106 with *your* proposal

**Comment by jeanlaroche** [comment]
It's working now. Thanks a bunch!
