### ISSUE TITLE
Julia microbenchmarks

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1104]
I played again with Julia microbenchmarks (https://julialang.org/benchmarks/), Pythran 0.9 and FluidPythran.

The code and some results are here https://github.com/fluiddyn/BenchmarksPythonJuliaAndCo/tree/master/JuMicroBenchmarks

There is one big Pythran performance issue with matrix multiplication for which Pythran is ~ 10 times slower than Numpy...

Pythran is slower than Julia for random generation but it is a known and understood issue (see #759).

@serge-sans-paille do you see possible improvements in the Python code (https://github.com/fluiddyn/BenchmarksPythonJuliaAndCo/blob/master/JuMicroBenchmarks/perf.py)?

@serge-sans-paille I'd like also to add few functions for which we know that Pythran does a good job. Could you please tell me which functions I could try?

**Comment by serge-sans-paille** [comment]
For matrix multiply, the problem probably lies in the blas version you're using, I have that in my pythranrc:

```
blas=openblas
```

**Comment by serge-sans-paille** [comment]
Don't know if you consider it fair to activate ``-march=native -DUSE_XSIMD`` ?

**Comment by paugier** [comment]
Yes I consider it fair to activate `-march=native -DUSE_XSIMD`. I am comparing JIT and these are the default option for the cachedjit decorator.

**Comment by paugier** [comment]
The performance issue for matrix multiplication is indeed solved with blas=openblas or blas=mkl. I thought Pythran would be by default able to use the blas library used by Numpy.

The default value leads to slow result... It may be good to warn the user and stress that the parameter blas is very important?

**Comment by paugier** [comment]
I have a performance issue with random generation. It is much worth than before (#759) since now, Pythran is ~10 times slower than Numpy...

See the tables in https://github.com/fluiddyn/BenchmarksPythonJuliaAndCo/tree/master/JuMicroBenchmarks

**Comment by paugier** [comment]
The performance issue with random numbers has been fixed by #1118

The overall performance seems good for these benchmarks with Pythran 0.9.1.
