### ISSUE TITLE
Compilation error using slice? MacOS

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1113]
I'm getting a compilation error on this code but I'm not entirely sure exactly where.
```
#pythran export shiftArray(float[],int,int,float)
def shiftArray(x,n,axis,val=0.):
    # A version of np.roll that allows you to insert any value where the roll operation cycles the end or start values.
    y = np.roll(x,n,axis)
    S = [slice(None,None,None)]*x.ndim
    if n>0: S[axis] = slice(0,n)
    elif n<0: S[axis] = slice(n,None)
    if n: y[tuple(S)] = val
    return y
```
This is with the current latest (789bc705)

**Comment by serge-sans-paille** [comment]
ok, so the problem is

1. ``[slice(None,None,None)]*x.ndim`` << you're creating a list and then converting it to tuple. Pythran cannot do that
2. ``x[slice(None, None, None),]`` << that was not supported either

I have patches to have the code work that way:

```python
#pythran export shiftArray(float[],int,int,float) 
def shiftArray(x,n,axis,val=0.): 
    import numpy as np 
    y = np.roll(x,n,axis) 
    S = (slice(None,None, None),)*x.ndim 
    if n>0: S[axis].stop = n 
    elif n<0: S[axis].start = n 
    if n: y[S] = val 
    return y 
```

but it requires some enhancment to pythran. Keep in touch!

**Comment by jeanlaroche** [comment]
Ah yes, that makes sense, the list->tuple. I hadn't thought of creating a tuple right off the bad, and only changing start/stop. Cool!

**Comment by serge-sans-paille** [comment]
Well, my bad, slice attributes are immutable. hard to come up with a decent version...

**Comment by serge-sans-paille** [comment]
Ok, I've got the fix, it's in #1120

**Comment by jeanlaroche** [comment]
I don't get it. What's the fix then? Slice attributes are still read only and pythran can't convert a list to a tuple...

**Comment by serge-sans-paille** [comment]
I made ndarray accept indexing of list of slices in addition to tuple of slices :-) The working code is there:

```
#pythran export shiftArray(float[],int,int,float) 
def shiftArray(x,n,axis,val=0.): 
    import numpy as np 
    y = np.roll(x,n,axis) 
    S = (slice(None,None),)*x.ndim 
    if n>0: S[axis] = slice(0,n)
    elif n<0: S[axis] = slice(n,None)
    if n: y[S] = val 
    return y 
```

**Comment by jeanlaroche** [comment]
Ah great!!! Thanks! But you probably mean 
S = [slice(None,None),]*x.ndim

**Comment by jeanlaroche** [comment]
I confirm that the bug is fixed with S = [slice(None,None),]*x.ndim
Thanks a bunch!
