### ISSUE TITLE
Need a sanity check for ~/.pythranrc

### ISSUE THREAD

**Issue by ashwinvis** [serge-sans-paille/pythran#1117]
There are no issues with the current implementation, but there are many ways the user (**cough cough me**) can make a trivial mistake.

# Case 1: wrong section

```ini
[pythran]
blas=openblas
CC=clang
CXX=clang++
```
**Solution**: a command `pythran-config [--check/--verify/--lint]`  which simply checks if the sections and options are legal.

# Case 2: wrong path
I had my `~/.pythranrc`. But the config was not being parsed. Turns out I had an environment variable configured `XDG_CONFIG_HOME` which would tell https://github.com/serge-sans-paille/pythran/blame/75d5c220278f6f69726591dda59812d8f6d5cab5/pythran/config.py#L21 to look at `~/.config/.pythranrc` instead. Undocumented.

**Solution**: `pythran-config --where` which checks for the path which is parsing. And some documentation about where to put it.

What do you think?

**Comment by ashwinvis** [comment]
If you need me to work on this, I would have some time to spare next week. Just decide on the command-line option names.

**Comment by serge-sans-paille** [comment]
Yeah, go ahead. Whabout a verbose mode to pythran-config that tells you
in the process where it has been looking for?

**Comment by ashwinvis** [comment]
So a simple `pythran-config -v` to do everything. Yes that could work :+1:

**Comment by serge-sans-paille** [comment]
yeah, and ``pythran -v`` would benefit from it if you do it right :-)

**Comment by serge-sans-paille** [comment]
Thanks a lot for contributing to #1145 !
