### ISSUE TITLE
dtype.type does not work for scalars

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1126]
Not sure if this is intended but if I use the method you proposed in #1121 compilation fails, because x.dtype.type does not work for scalars. testcase:
```python
import numpy as np
#pythran export test(complex64)
def test(x):
    return x.dtype.type(1+1j)
```

**Comment by serge-sans-paille** [comment]
Ahah I knew this would pop up, but I was lazy to fix this bug :-)
