### ISSUE TITLE
regression on argmin/max

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1133]
Some time ago I reported a performance difference between a manual argmin and np.argmin (#801) this was fixed in #971. However, there seem to have been a regression recently, because the performance is now back to the same as it was before #971.

current master:
```python
[ins] In [2]: s=np.random.randn(2**16)+np.random.randn(2**16)*1.j ; sc=random.choice(s,32)               

[ins] In [3]: timeit(make_decision.make_decision(s, sc))                                                 
3.21 ms ± 17.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

2a60b11f 
```python
[ins] In [2]: s=np.random.randn(2**16)+np.random.randn(2**16)*1.j ; sc=random.choice(s,32)               

[ins] In [3]: timeit(make_decision.make_decision(s, sc))                                                 
1.33 ms ± 21.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

[ins] In [4]: timeit(make_decision.make_decision2(s, sc))                                                
1.29 ms ± 15.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
I'm still trying to track what commit introduced the regression.

**Comment by cycomanic** [comment]
OK I've narrowed it down to between b72c2215 (last fast version) and 329a6ed1 (regressed version). I was trying to narrow it down further but many of the revisions between would not build the script for me.

**Comment by cycomanic** [comment]
OK the issue seems to come from the XSIMD transition. If I compile without -DUSE_XSIMD then make_decision and make_decision2 have the same time.

**Comment by serge-sans-paille** [comment]
On Sun, Dec 09, 2018 at 03:49:01AM -0800, Jochen Schröder wrote:
> OK the issue seems to come from the XSIMD transition. If I compile without
> -DUSE_XSIMD then make_decision and make_decision2 have the same time.

Thanks for sorting that out! I remember I changed the argmin/max vectorized version...

**Comment by serge-sans-paille** [comment]
@cycomanic does #1149 improve the situation?

**Comment by serge-sans-paille** [comment]
ok, with my test, it doesn't, I need to investigate some more.

**Comment by serge-sans-paille** [comment]
@cycomanic branch updated, performance should be back to normal, if not better.
