### ISSUE TITLE
pythran optimises variable assignement in loop away

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1137]
Took me a while to figure out what was going on, but it seems if we create a new variable inside an if statement in a loop it gets optimized away. 
The following code:

```python
#pythran export amintest1(float, float[])
def amintest1(x, y):
    d0 = 1000.
    for i in range(y.shape[0]):
        d = abs(x-y[i])
        if d < d0:
            d0 = d
            j = i
    return j, d0
```
gets optimized to (output of `pythran -P test.py`)
```python
def amintest1(x, y):
    d0 = 1000.0
    for i in __builtin__.range(__builtin__.getattr(y, 'shape')[0]):
        d = __builtin__.abs((x - y[i]))
        if (d < d0):
            d0 = d
            pass
    return (i, d0)
```
note the assignment to j has been optimized away thus will give wrong results. If we declare j before the loop works correctly.
```python 
def amintest2(x, y):
    d0 = 1000.
    j = 0
    for i in range(y.shape[0]):
        d = abs(x-y[i])
        if d < d0:
            d0 = d
            j = i
    return j, d0
```
becomes:
```python
def amintest2(x, y):
    d0 = 1000.0
    j = 0
    for i in __builtin__.range(__builtin__.getattr(y, 'shape')[0]):
        d = __builtin__.abs((x - y[i]))
        if (d < d0):
            d0 = d
            j = i
    return (j, d0)
```

Also if I compile with `pythran -03 -march=native -ffast-math -fopenmp -DUSE_XSIMD` the time difference is surprisingly large (can assigning one variable more make such a difference?)
```python
In [1]: x=np.random.randn(10**6)

In [2]: import test

In [3]: timeit(test.amintest1(x[100000], x))
485 µs ± 36.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [4]: timeit(test.amintest2(x[100000], x))
3.24 ms ± 25.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by serge-sans-paille** [comment]
Thanks for analysing this bug down to a very simple test case. I'll have a look at it.

**Comment by serge-sans-paille** [comment]
I can reproduce the issue. Note however that the compiler has no way to guess that the condition will be true at least once, so you may end up with j being undefined. I'd rather have 

```
#pythran export amintest1(float, float[])
def amintest1(x, y):
    j, d0 = 0, y[0]
    for i in range(1, y.shape[0]):
        d = abs(x-y[i])
        if d < d0:
            d0 = d
            j = i
    return j, d0
```

be invalid and have pythran raise an error about it. 

```
#pythran export amintest1(float, float[])
def amintest1(x, y):
    d0 = 1000.
    for i in range(y.shape[0]):
        d = abs(x-y[i])
        if d < d0:
            d0 = d
            j = i
    return j, d0
```

**Comment by cycomanic** [comment]
Not sure I understood correctly, but you are saying that the second case should raise an error? 

I don't have an issue initialising all variables before if statements, however I think this should be well documented and a clear error raised in the cases when they have not been initialised, because this is a bitch to debug (and somewhat unexpected) if it happens somewhere inside a large function.

**Comment by cycomanic** [comment]
BTW is the large timing difference expected?
