### ISSUE TITLE
document use of 'or' in signature

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#1138]
It seems a valid type of signature is 
```argument_type or argument_type```
which does not seem to be documented
e.g. ```int or int[:]```

**Comment by serge-sans-paille** [comment]
To be fair, in https://pythran.readthedocs.io/en/latest/MANUAL.html#concerning-pythran-specifications we can read

> If you want to specify multiple overloads, instead of listing them, you can use the or operator to list the alteranives, as in:
>
> #pythran export function_name(type0 or type1, type2, type3 or type4)

With a great typo on alterna*t*ives. I'm open to improvements!

**Comment by nbecker** [comment]
OK, I didn't notice that.  I looked at the formal grammar definition above and didn't see it.
