### ISSUE TITLE
Minor issue: with python3, under macos, pythran no longer ingnores imports it can't handle

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1139]
This compiles fine with python 2.7, or with pyton3 in linux, but not with python3 in macOS, which complains about logging.
```
import logging

#pythran export test()
def test()
    return 1.0
```

**Comment by serge-sans-paille** [comment]
It should always complain when meeting an unsupported import :-)

**Comment by serge-sans-paille** [comment]
@jeanlaroche this does not compile on my Linux box, neither with python2 not python3... Which is the expected behavior.
