### ISSUE TITLE
Compilation error on np.ones(shape)

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1142]
I'm getting a compilation error on this:
```
import numpy as np

#pythran export test(float[][],int,int,float)
def test(array,n,axis,padVal):
    shape = list(array.shape)
    shape[axis]=n
    toPad = padVal*np.ones(shape,dtype=array.dtype)
    return np.concatenate((np.diff(array, n, axis=axis), toPad), axis=axis)
```
Guessing the issue is np.ones(shape) where shape is a list instead of a tuple. Could this be fixed? I don't know how to work around this specific problem...

**Comment by serge-sans-paille** [comment]
> Guessing the issue is np.ones(shape) where shape is a list instead of a tuple.
> Could this be fixed? I don't know how to work around this specific problem...

Yeah, that's the problem. Yout code is very idiomatic, We should be able to support that...
