### ISSUE TITLE
reduction of compilation time  when a function has many arguments

### ISSUE THREAD

**Issue by saidctb** [serge-sans-paille/pythran#1173]
I have this minimal example that  takes forever to compile is there a way to reduce the compilation time when we have this many arguments ? 
```
#pythran export kernel(float[][], float[][], float[][], float[][], float[][], float[][], float[][], float[][], float[][], float[][], float[][], float[][], float[][], float[][], float[][], float[][], float[][])
def kernel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, mat):

    jl1 = 0
    jl2 = 0
    il1 = 0
    il2 = 0

    x1  = arg1[jl1,1]*arg2[jl2,0]
    x2  = arg2[jl1,0]*arg3[jl2,1]
    x3  = arg3[il1,1]*arg4[il2,0]
    x4  = arg4[il1,0]*arg5[il2,1]
    x5  = arg7[il1,il2]
    x6  = arg8[il1,il2]
    x7  = arg9[il1,il2]
    x8  = arg10[il1,il2]
    x9  = arg12[il1,il2]
    x10 = arg13[il1,il2]
    
    det = x1*x2 - x3*x4
    inv = 1.0/(x5*x6 - x7*x8)
    u_x = inv*x9*x10 - inv*x6*x5
    u_y = -inv*x1*x2 + inv*u_x*x1
    v_x = inv*x1*x2 - inv*u_x*x1
    v_y = -inv*x1*x2 + inv*x2*x1

    v   = (u_x*v_x + u_y*v_y)*det*inv

    mat[il1,il2] = v
```

**Comment by serge-sans-paille** [comment]
Hi @saidctb. The problem with this function is that pythran will generate `2**13` versions, for different variations of the argument, transposed or not.

This is obviously an issue, how could we fix that... maybe add a type qualifier `notranspose` or have the compiler warn about the combinatory being too large... Or both! Any thought?

**Comment by saidctb** [comment]
it would be great if there is a flag like `notranspose`  because i will never call the function with the transpose or maybe  you can add a type annotation which specifies the order ,if the user wants to call the function with   Fortran order  or a C order ,like `float[][](F)`  for fortran order  and the default will be the C order in this case you don't have to generate all the possible ways of calling the function

**Comment by serge-sans-paille** [comment]
yeah, forcing the order is a good approach too, that's very explicit. I +1 the idea. Unfortunately, this is not going to make it for next release though :-)

**Comment by serge-sans-paille** [comment]
@saidctb can you confirm #1260 somehow fixes your issue?
