### ISSUE TITLE
Values in tuple are not modifiables

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#1181]
The following example doesn't work well when compiled with pythran

```
def xx(t, v):
    b, _ = t
    b[0] += v

#pythran export fct(int)
def fct(a):
    t = ([0], 12)
    xx(t, a)
    b, _ = t
    return b[0]
```

**Comment by diorcety** [comment]
Disabling extra optimizations solve this issue

**Comment by diorcety** [comment]
This is dead_code_elimination optimization

**Comment by diorcety** [comment]
The issue is: `b, _ = t`
Dead code elimination assume that `xx(t, a)` is pure because t has no argument_effect due to the tuple unpacking

**Comment by serge-sans-paille** [comment]
ok, that's an aliasing issue :-)

**Comment by diorcety** [comment]
I just found a fix if you want :)

**Comment by serge-sans-paille** [comment]
of course :-)

**Comment by serge-sans-paille** [comment]
@diorcety the code now compiles fine, can you confirm and close the issue?

**Comment by diorcety** [comment]
Yes it's good!
