### ISSUE TITLE
Regression in Pythran 0.9.1

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#1182]
[PyGaussDCA 0.1.2][1] used to work great with Pythran 0.9.0, but fails to compile under 0.9.1.

Here is the log:
https://gist.github.com/Dapid/6525319d6492d0a5db55de7bb4938c90

This is not a critical issue for me, since v 0.1.3 works fine with 0.9.1, but I think it points at a regression somewhere.

[1]:https://pypi.org/project/pyGaussDCA/0.1.2/

**Comment by serge-sans-paille** [comment]
I falied to reproduce with the following sequence:

```
mkvirtualenv tmp
pip install numpy pythran
pip install pygaussdca==0.1.3
```

could you isolate the faulty .py file?

**Comment by Dapid** [comment]
The problem is with version 0.1.2, in particular with the file _load_data.py

If I download the .tar.gz from pypi and install it directly, I get the error. If I decompress it first, it works.

**Comment by Dapid** [comment]
Bisect blames this commit:

https://github.com/serge-sans-paille/pythran/commit/7821f3abe2f822a8f88ee93925bb6f1b9e3b55aa

**Comment by serge-sans-paille** [comment]
Bug spotted. It's not something I plan to deal with as of now: cpp file generated by version 0.x are not necessarily compatible with the header files from version 0.y. The fix would be to enforce the pythran version in the requirements... I'll still submit a patch to properly inform the user about the issue.

**Comment by serge-sans-paille** [comment]
Behavior speicifed in c93d76e3847a3f1d288070e379ee386c57274aa2, closing the issue.
