### ISSUE TITLE
Transpose ignored in recent Pythran

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#1189]
```
import random
import numpy as np

#pythran export call()
def call():
    return np.random.random((3, 5)).T
```
```
import test

out = test.call()
print(out.shape)
```

On Pythran master and released, I get (3, 5), instead of (5, 3). Pythran 0.9.0 works fine.

**Comment by Dapid** [comment]
Git bisect points to the culprit:

```
8b4f22aa0ef0a33308d87b2dcb7d9b4cef3a6187 is the first bad commit
commit 8b4f22aa0ef0a33308d87b2dcb7d9b4cef3a6187
Author: serge-sans-paille <serge.guelton@telecom-bretagne.eu>
Date:   Fri Dec 21 18:47:26 2018 +0100

    Correct support of assignment of a transposed view through a slice
    
    Fix #1148
```

https://github.com/serge-sans-paille/pythran/commit/8b4f22aa0ef0a33308d87b2dcb7d9b4cef3a6187

**Comment by serge-sans-paille** [comment]
Probably related to #1183. This is a critical bug: I'll fix that and release a patch version of pythran.

**Comment by Dapid** [comment]
Thanks!

I think it would be nice to have some nightly integration test testing applications using Pythran. For example, a Travis nightly run. Hopefully that will catch more bugs.

**Comment by Dapid** [comment]
I am now running a weekly test with Pythran master on my code:

https://travis-ci.org/ElofssonLab/pyGaussDCA/
