### ISSUE TITLE
Fix default parameters in arange

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1191]
This is in relation with https://github.com/serge-sans-paille/pythran/pull/1190 
The pull request breaks arange (and possibly other functions).

**Comment by serge-sans-paille** [comment]
@jeanlaroche can you remind me of the issue you wanted to fix here? Not the general default parameter stuff, but the specific arange issue? Thanks!

**Comment by jeanlaroche** [comment]
I'm not sure why I opened this bug. The pull request apparently breaks arange, but I don't know why I opened this specific bug... I will close it.
