### ISSUE TITLE
Compilation error on dict that include int and array...

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1222]
This does not compile, but I don't know if that's expected:
```
import numpy as np

#pythran export foo(int)
def foo(n):
    out = {'a':n,'b':np.zeros(n)}
    return out
```

**Comment by serge-sans-paille** [comment]
> #pythran export foo(int)
> def foo(n):
>     out = {'a':n,'b':np.zeros(n)}
>     return out

What would be the type of `out`? string to ... int or array? we don't h ve union
type in pythran so yeah tht's rightfully unsupported :-)

**Comment by jeanlaroche** [comment]
OK Thanks! The only type of dict that's supported is the type that's supported in std I imagine, with a uniform type for both key and value. Thanks.
