### ISSUE TITLE
compile failure (np.hstack?)

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#1227]
https://gist.github.com/nbecker/654d3d83628439a8fe8f4a9cce3150ac

**Comment by nbecker** [comment]
If I change hstack to np.append, I get a similar error
```
/home/nbecker/.local/lib/python3.7/site-packages/pythran/pythonic/numpy/append.hpp:22:60: error: no type named ‘dtype’ in ‘class std::complex<double>’
     types::ndarray<typename F::dtype, typename F::shape_t> ndata(data);
                                                            ^~~~~
/home/nbecker/.local/lib/python3.7/site-packages/pythran/pythonic/numpy/append.hpp:22:60: error: no type named ‘dtype’ in ‘class std::complex<double>’
```
Perhaps append doesn't support appending a scalar to an array?

**Comment by jeanlaroche** [comment]
Appending scalar to array wasn't working up until today. You might want to get the latest and retry.

**Comment by nbecker** [comment]
I apologize, there was 1 error in the function signature.  The 4th argument should be complex, not float:
#pythran export cleanup(complex[:], complex[:], complex[:], complex, float)

However, it still doesn't compile unless I change the lines that used (originally hstack, now append), to:
            Wtmp = np.append (W, [pt])
...
           V = np.append(V, [pt])

That is, np.append (V, pt) does not compile, but np.append (V, [pt]) does, where V is
complex[:] and pt is complex.

**Comment by nbecker** [comment]
It appears that np.append still does not support append a scalar (or somehow I failed to update to latest)

**Comment by nbecker** [comment]
OK, if I update to the correct git branch then it does indeed compile!

**Comment by jeanlaroche** [comment]
> OK, if I update to the correct git branch then it does indeed compile!

My bad, I forgot that it wasn't on master but on a fix branch...
