### ISSUE TITLE
np.setdiff1d not implemented

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#1228]
setdiff1d is not implemented yet, I could use it

**Comment by nbecker** [comment]
Might not be working correctly.  In my code, I get different results for these 2 lines, which should give the same result:

    for pt in np.setdiff1d(pts, W):
    for pt in (pt for pt in pts if pt not in W):

**Comment by serge-sans-paille** [comment]
Can you provide the values for pt and W?

**Comment by nbecker** [comment]
OK, it seems the reason for the different results is simply that the results are returned in a different order.  I don't know if there is any requirement on the order of the returned result.

In my test, I did:
A = [pt for pt in pts if pt not in W]
B = np.setdiff1d(pts, W)
if (set (A) != set (B)):
  print...

And nothing ever prints, so the sets are identical and the results must just be in a different order.

**Comment by nbecker** [comment]
I'm getting segfault in setdiff1d.  Not able to isolate it yet, but here's what gdb says:

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
(anonymous namespace)::pythonic::numpy::impl::set_difference_unique<std::complex<double>*, std::complex<double>*, std::complex<double>*> (
    result=0x5555568317c0, last2=<optimized out>, first2=<optimized out>, last1=0x5555565fe060, first1=0x5555568aa000)
    at /home/nbecker/.local/lib/python3.7/site-packages/pythran/pythonic/numpy/setdiff1d.hpp:48
(gdb) p t1
$1 = {__re_ = <optimized out>, __im_ = 0}
(gdb) p first1
$2 = (std::complex<double> *) 0x5555568aa000
(gdb) p *first1
Cannot access memory at address 0x5555568aa000
(gdb)

**Comment by nbecker** [comment]
Additional info, if I set assume_unique, the code completes normally
