### ISSUE TITLE
key param to sorted

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#1234]
while pythran can compile code like

```a = sorted(b)```

It doesn't support 'key' argument:
```            ordered_pts = sorted(eligible_pts, key=lambda p: abs(pts-p))```
```
CRITICAL: I am in trouble. Your input file does not seem to match Pythran's constraints...
E: function uses an unknown (or unsupported) keyword argument `key` (line 114)
```

**Comment by Dapid** [comment]
`min` and `max` also don't have key argument supported.

**Comment by serge-sans-paille** [comment]
@Dapid can you open a new Issue plz?
