### ISSUE TITLE
np.bincount broken on master

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#1251]
#1249 breaks np.bincount on GCC-5. Here is a short reproducing example:

```
import numpy as np

#pythran export compute(int8[:])
def compute(vector):
   return np.bincount(vector)
```

And the Travis logs for a slightly longer version:
int8: https://travis-ci.org/Dapid/test_travis/jobs/511931148 
int32: https://travis-ci.org/Dapid/test_travis/jobs/511932347

And only on int8 for the shown example: https://travis-ci.org/Dapid/test_travis/jobs/511933665
The error is:

```
/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pythran/pythonic/numpy/bincount.hpp:22:22: error: no matching function for call to ‘max(long int&, int)’
     length = std::max(length, 1 + max(expr));
```

On my machine I have  GCC 8.3.1, and that works.

**Comment by serge-sans-paille** [comment]
I'd try `sed -i - e 's/std::max/numpy::max/g' pythran/pythonic/numpy/bincount.hpp` does that work for you?

**Comment by serge-sans-paille** [comment]
#1253 should do the trick :-) Thanks for reporting o/
