### ISSUE TITLE
NoneType with rvalue reference

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#1266]
When compiling this code
```
import numpy as np

#pythran export to_tuple(float list)
def to_tuple(l):
    def aaa(l):
        return tuple([None if np.isnan(a) else a for a in l])
    return aaa(np.subtract(np.zeros((len(l),)), 2))
```

I have the following issue:
`error: base specifier must name a class`

**Comment by serge-sans-paille** [comment]
I cannot reproduce your issue with master version :-/

**Comment by diorcety** [comment]
clang40 ? c++/4.9 from my debian?

**Comment by diorcety** [comment]
Do you want a preprocessed file ?

**Comment by serge-sans-paille** [comment]
On Wed, Apr 10, 2019 at 12:15:25PM -0700, Diorcet Yann wrote:
> Do you want a preprocessed file ?

the output of -E could help, yes

**Comment by diorcety** [comment]
http://dl.free.fr/m3vAUQ0O9

**Comment by diorcety** [comment]
Do you need any other information?

**Comment by serge-sans-paille** [comment]
On Tue, Apr 23, 2019 at 05:21:23PM +0000, Diorcet Yann wrote:
> Do you need any other information?

Time, I need time :-)

**Comment by diorcety** [comment]
👍

**Comment by serge-sans-paille** [comment]
I can reproduce the issue with the preprocessed file, thanks a bunch!
