### ISSUE TITLE
Wrong return size when two paths can return different arrays

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1287]
This is a regression from 0.9.0
The code below compiles, but does not run right.
test(20) should return a 20 element array, but it does not, it return a 2 element array (with the "correct" values in it, from np.arange() but the size is truncated to two
```
import numpy as np

#pythran export test(int)
def test(N):
    if N<10:
        return np.array([.1,.1])
    A = np.arange(N)
    return A
```

**Comment by jeanlaroche** [comment]
Again, a workaround is this:
```
        A = np.empty(N*0+2,dtype=float)
        A[0:2] = [.1,.1]
```
Any try that prevent pythran from assuming a compile-time known shape for the output...

**Comment by serge-sans-paille** [comment]
It seems to compile fine now, can you confirm?

**Comment by jeanlaroche** [comment]
It compiles all right (always did), it just does not do the right thing!

**Comment by jeanlaroche** [comment]
Confirmed fixed ! Thanks SO MUCH! :)
