### ISSUE TITLE
OpenMP use without pragmas?

### ISSUE THREAD

**Issue by Chronum94** [serge-sans-paille/pythran#1302]
File `cubeimpl.py`:
```python
import numpy as np

#pythran export cubeboi(float[:])
def cubeboi(x):
    CHUNK_SIZE = 2048*32
    arrlen = x.shape[0]
    last_chunk_start = arrlen % CHUNK_SIZE
    for i in np.arange(0, arrlen, CHUNK_SIZE):
        x[i:i + CHUNK_SIZE] = x[i:i + CHUNK_SIZE]**3

    x[-last_chunk_start:] = x[-last_chunk_start:]**3

#pythran export cube_inplace(float[:])
def cube_inplace(arr):
    for i in range(arr.size):
        arr[i] = arr[i]**3
```
Compiled with:
`pythran cubeimpl.py -fopenmp -Ofast -DUSE_XSIMD`

Timed in an Ipython QtConsole in the same directory as the compiled module, with:
```python
import numpy as np
from cubeimpl import cubeboi, cube_inplace
x = np.random.rand(1000000)
x1, x2, x3 = [x.copy()] * 3
%timeit np.power(x1, 3)
%timeit cubeboi(x2)
%timeit cube_inplace(x3)
```

Timing results:
```
68 ms ± 2.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
286 µs ± 21.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.02 ms ± 23 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

When compiled with:
`pythran cubeimpl.py -Ofast -DUSE_XSIMD`

Timing results:
```
66.3 ms ± 1.62 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.01 ms ± 27.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.02 ms ± 40.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

This happens even if I `export OMP_NUM_THREADS=1` in terminal before running the pythran module. There are no Openmp pragmas in my code. I've looked at processor usage during the timeits, and the chunked version of the cube function does in fact use all 6 processors.

All of this was on Ubuntu 18.04, GCC 7.4.0, in a VM.

**Comment by serge-sans-paille** [comment]
There are implict pragmas for some numpy expression. I'm unsure that's a nice feature, but at least it explains the behavior.

**Comment by paugier** [comment]
> This happens even if I export OMP_NUM_THREADS=1 in terminal before running the pythran module.

Just to check, if you do the timeit after `export OMP_NUM_THREADS=1`, only one core is used even with the module compiled with `-fopenmp`, isn't it? If it is not the case, it's a bug. Otherwise, it seems to me that it is a nice behavior.

**Comment by serge-sans-paille** [comment]
> if you do the timeit after export OMP_NUM_THREADS=1, only one core is used even with the module compiled with -fopenmp, isn't it

yes

**Comment by Chronum94** [comment]
Just confirmed that even with OMP_NUM_THREADS=1 I get the openmp speedup.

**Comment by serge-sans-paille** [comment]
```
% git grep '#pragma omp' pythran/pythonic/
```

Now only yields references to `#pragma omp declare reduction`, so leaving aside whatever blas version that may be linked to pythran, no more implicit multithreading within pythran.
