### ISSUE TITLE
Improved export syntax?

### ISSUE THREAD

**Issue by Chronum94** [serge-sans-paille/pythran#1303]
Currently:
```python
#pythran export afunction(int, int)
def afunction(a, b):
```

Proposed:
```python
#pythran export as thisfunction(int, int)
def afunction(a, b):
```

Motivation is that with the second type, if we change the function name from `afunction` to `anotherfunction`, we only need to change it in one place and not two.

**Comment by paugier** [comment]
I don't discuss your proposal... But note that with [Transonic](https://transonic.readthedocs.io), you can use Pythran without writing any Pythran signatures and Pythran modules...

For ahead-of-time compilation:
```
from transonic import boost
@boost
def afunction(a: int, b: int):
    ...
```

For just-in-time compilation:
```
from transonic import jit
@jit
def afunction(a, b):
   ...
```

**Comment by saethlin** [comment]
Alternatively, it could be that
```
#pythran export thisfunction(int, int)
def afunction(a, b):
```
produces a function called `thisfunction` in the `.so` but this might be surprising and let some of what are currently typos pass pythran and cause errors more mysterious down the line.

Or pythran could use the name of the Python function, so that one would write
```
#pythran export (int, int)
def afunction(a, b):
```

**Comment by serge-sans-paille** [comment]
I understand the need of less redundancy - and fully agrees this is the right direction. That being said, i'm not a huge  fan of `thisfunction` and prefer 

```python
#pythran export (int, int)
def afunction(a, b):
```
However, pythran exports are currently not textually tied to the function and cand be written anywhere, e.g. at the beginning of the file, so this is some kind of a change (and maybe not trivial to implement).


Given that python2 support is not going to last, we could also use a more py3-oriented solution, something like

```python
def afunction(a: int, b: int) -> "pythran"
```

But this is not compatible with multiple overloads.

We could also place the export in the docstring which has the advantage of being attached to the function, but it's not clear to me if a pythran export should be part of the doc (I tend to think it may be, but it shouldn't be forced). And it's a radical change with current handling.


So... no clear winner for me :-)

**Comment by paugier** [comment]
> `def afunction(a: int, b: int) -> "pythran"`

Oh I'm shocked! :slightly_smiling_face:  

`->` has a meaning in Python and this function does not return a "pythran" object.

> But this is not compatible with multiple overloads.

It can be easily solved with a small runtime pure python dependency (something like Transonic) to define fuse types in Python.

For Pythran without Transonic, i think it would not be difficult to support 

```
# pythran export (int, int)
def afunction(a, b):
```

with an AST extended to line comments (what we use in Transonic, https://bitbucket.org/fluiddyn/transonic/src/default/transonic/analyses/extast.py).

It could be reasonable for Pythran without Transonic. It does not break the current Pythran syntax. Just export commands with no name apply to the next function definition.

That said, (i) it's not so beautiful (we loose the similarity with a C signature) and (ii) it does not add a lot. One still has to manually write (and read) potentially complicated and long "signatures". As soon as there are a lot of variables, it's difficult to see the correspondence between variables and types.

Transonic improves a lot more the user experience (no need for Pythran signatures, types in annotations, variables containing types, fuse types).

**Comment by serge-sans-paille** [comment]
Closing that issue, using transonic seems to be the way to go for an improved syntax.
