### ISSUE TITLE
passing OpenMP option for Visual Studio?

### ISSUE THREAD

**Issue by piotrbartman** [serge-sans-paille/pythran#1335]
What is the proper way of passing compiler options when running Pythran on Windows and using Visual Studio?

Doing ```pythran -fopenmp``` results in an "unused option" warning from the compiler- as it indeed is not a valid cl.exe option.

Doing ```pythran /OpenMP``` results in Pythran complaining about /OpenMP file not found.

Doing ```pythran "-DBLAH /OpenMP"``` seems to work (judging from pythran -v output) but it's a dirty hack.  

Thank for any hints

**Comment by serge-sans-paille** [comment]
@piotrbartman this is a bug, we only support Linux-style options, let me fix that

**Comment by serge-sans-paille** [comment]
@piotrbartman can you confirm #1338 fixes your issue?

**Comment by piotrbartman** [comment]
Seems to work, lowercase ```/openmp``` is accepted.
```/OpenMP``` gives strange error messages that ```/Op``` ```/Oe``` ```/On``` ```/OM``` ```/OP``` are not accepted, but it's perhaps intented behaviour as VS manual mentions lowercase ```/openmp```

Thanks!

P.S. Now we're facing ```CRITICAL: Cover me Jack. Jack? Jaaaaack!!!!```, will follow up soon
