### ISSUE TITLE
user-defined openmp reductions

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1336]
I realise this is probably not the highest priority, but a way to implement user-defined reductions would be great. Could this possibly be done by simply adding some annotation/command to the reduction function?

**Comment by serge-sans-paille** [comment]
You mean like in OpenMP4?

**Comment by cycomanic** [comment]
Yes essentially. However I was wondering if it was possible to outgenerate all the openmp scaffolding by simply annotating a function to be the reduction function and then referring to that one in the omp pragma

**Comment by serge-sans-paille** [comment]
Turns out this is supported (using pure OpenMP syntax) since 93cd9f4242e66792c877da1d0d4e66f22a8ea945 :-)

You can have a look at an example in https://github.com/serge-sans-paille/pythran/blob/master/pythran/tests/openmp.4/declare_reduction.py

I don't plan to support more than this :-/
