### ISSUE TITLE
openmp collapse issue

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1337]
I'm encountering an issue with `collapse()`

Testcase:
```python
 import numpy as np
#pythran export collapse_bug(complex128[], int, complex128[])
def collapse_bug(x, m, btx):
    n = int(np.log2(m))
    lv = np.zeros((x.shape[0], n))
    N = x.shape[0]
    #omp parallel for collapse(2)
    for i in range(N):
        for k in range(n):
            lv[i,k] = abs(x[i]- btx[k])
    return lv
```
if I try to compile this I get a ` error: not enough for loops to collapse`. The reason seems to be that pythran puts code between the two loops. Here is the relevant part from the cpp file:
```CPP
{
      #pragma omp parallel for collapse(2)
      for (long  i=0L; i < N; i += 1L)
      {
        {
          long  __target140051700270080 = pythonic::__builtin__::functor::int_{}(pythonic::numpy::functor::log2{}(m));
          for (long  k=0L; k < __target140051700270080; k += 1L)
          {
            lv.fast(pythonic::types::make_tuple(i, k)) = pythonic::__builtin__::functor::abs{}((x.fast(i) - btx.fast(k)));
          }
        }
      }
    }
    return lv;
```

According two the openmp specs:
`The loops must be perfectly nested; that is, there is no intervening code nor any OpenMP pragma between the loops which are collapsed"`. so the declaration of the variable is in the wrong spot.

**Comment by serge-sans-paille** [comment]
Pythran tries hard to generate perfectly nested loops when possible. From your test case I don't see any reason why it should fail here, I'll have a look. thanks for reporting!

**Comment by serge-sans-paille** [comment]
#1340 should do the trick, and C++ compiler should be able to optimize the bound computation out of the loop.

**Comment by cycomanic** [comment]
I confirm that #1340 fixed it
