### ISSUE TITLE
Basic example compilation error

### ISSUE THREAD

**Issue by nth29** [serge-sans-paille/pythran#1344]
Compilation of the following example test_pythran.py
"""
#pythran export mytest(float[])
def mytest(n):
    res = (n+2*pow(n**2,2))/n
    return res
"""
with command : 
>pythran test_pythran.py

fails with the following error:

"""
/tmp/tmpwq5KHw.cpp:57:110:   required from here
/usr/local/lib/python2.7/dist-packages/pythran/pythonic/include/types/tuple.hpp:870:37: error: no type named 'type' in 'struct std::tuple_element<0, std::tuple<> >'
           std::tuple<Tys...>> ::type;
                                     ^
WARNING: Compilation error, trying hard to find its origin...
WARNING: Nop, I'm going to flood you with C++ errors!
CRITICAL: Cover me Jack. Jack? Jaaaaack!!!!
E: error: Command "x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-IbFBHb/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=2 -DPYTHRAN_BLAS_BLAS -I/usr/local/lib/python2.7/dist-packages/pythran -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I/usr/include -I/usr/include/python2.7 -c /tmp/tmpwq5KHw.cpp -o /tmp/tmpb_5iui/tmp/tmpwq5KHw.o -std=c++11 -fno-math-errno -w -fvisibility=hidden -fno-wrapv" failed with exit status 1
"""
Pythran version : 0.9.3
Python version : 2.7.16
Operating System: Debian GNU/Linux 10 (buster)
Kernel: Linux 4.19.0-5-amd64
Architecture: x86-64

**Comment by serge-sans-paille** [comment]
Wow, that's a major bug, what a shame our validation suite didn't catch that :-/ I'll have a look during the week end.

**Comment by serge-sans-paille** [comment]
@nth29, can you confirm #1345 solves your issue? You can just run

```
pip install git+https://github.com/serge-sans-paille/pythran.git@fix/fix-broadcast-shape
```

and that should do the trick.

Thanks again for the bug report, trugarez!

**Comment by nth29** [comment]
Yes this solve the issue. Thank you!
