### ISSUE TITLE
type(number)(0)

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1348]
Could something like this be supported ?

```
# pythran export func(int or float)
def func(number):
    return type(number)(0)
```

It's just a question, not an urgent need :slightly_smiling_face:

**Comment by serge-sans-paille** [comment]
I'd say yes :)

**Comment by serge-sans-paille** [comment]
@paugier can you test #1350? It was surprisingly easy to implement, we sure have a good model ;-)

**Comment by paugier** [comment]
I confirm that it works fine for me!

```
from transonic import boost

@boost
def func(number: "int or float"):
    return type(number)(0)

assert type(func(1.0)) == float
assert type(func(1)) == int
```

It is what could be useful in some codes supporting both Cython and Pythran in Transonic, so cool!

Just a remark, the functors can not be converted in the corresponding Python functions if a crazy user try to do:

```
from transonic import boost

@boost
def type_(number: "int or float"):
    return type(number)

assert type_(1.0) == float
assert type_(1) == int
```
