### ISSUE TITLE
Some expensive analyses/transformations could easily be avoided (?)

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1373]
Related to #1357 (but not the main issue)...

On my small laptop doing `pythran main.py -P` on this tiny code takes ~ 10 s !

main.py
```
from common import used_func

def not_used_main():
    result = 0
    for i in range(6):
        for j in range(6):
            result += i * j
    return result

# pythran export func()

def func():
    return used_func()
```

common.py
```
def used_func():
    return 1

def not_used():
    result = 0
    for i in range(6):
        for j in range(6):
            result += i * j
    return result
```

We see that the high level optimization is done for all functions of both modules, while 2 of the functions are not used at all by the exported function.

In some packages, these `common.py` files can be quite large, so it could be a simple optimization to decrease the Pythran compilation times to discard quite early the functions that do not need to be analyzed and optimized.

**Comment by serge-sans-paille** [comment]
As pythran can process unannotated files (for c++ generation) this would imply a
different pipeline, but I actually like the idea!
