### ISSUE TITLE
scipy functions not listed in SUPPORT.html

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1375]
I noticed that scipy functions are not listed in https://pythran.readthedocs.io/en/latest/SUPPORT.html

It's strange because there are scipy functions in pythran.tables.MODULES.

It is on purpose?

**Comment by serge-sans-paille** [comment]
> It is on purpose?

Nop, it's a bug :-)

**Comment by paugier** [comment]
No such bug when scipy is installed so I guess it's only due to 

https://github.com/serge-sans-paille/pythran/blob/master/pythran/tables.py#L4591

```
# detect and prune unsupported modules
for module_name in ["omp", "scipy.special", "scipy"]:
```

2 simple solutions:
- just add scipy in the requirements to build the doc (scipy-1.3.1-cp35-cp35m-manylinux1_x86_64.whl (25.1 MB))
- disable pruning of the unsupported modules when building the doc

Which one do you prefer ?

**Comment by serge-sans-paille** [comment]
>   • just add scipy in the requirements to build the doc

This one :-)

**Comment by serge-sans-paille** [comment]
https://pythran.readthedocs.io/en/latest/SUPPORT.html#scipy \o/
