### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by mgirardis** [serge-sans-paille/pythran#1376]
I was trying to compile [my module](https://www.dropbox.com/s/pkkzoehxbpnt0pc/GLNetEISimLib.py?dl=0) and got the error below, even though pythran successfully generates a [cpp source](https://www.dropbox.com/s/lmqpoai9dt2qeih/GLNetEISimLib.cpp?dl=0) from my module. Besides, it takes very long to generate and compile this module.

Any thoughts? Any other info that I should attach to this issue?

<pre><font color="#EF2929"><b>mschappo</b></font>@<font color="#CC0000">giraneuro</font>(<font color="#555753"><b>~/Dropbox/p/neuromat/programas/python/balanced_net_gl</b></font>) pythran GLNetEISimLib.py -v
INFO:      sys file exists: /home/mschappo/.local/lib/python3.6/site-packages/pythran/pythran.cfg
INFO: platform file exists: /home/mschappo/.local/lib/python3.6/site-packages/pythran/pythran-linux.cfg
WARNING:     user file does not exist: /home/mschappo/.pythranrc
INFO: pythranrc section [pythran] is valid and options are correct
INFO: pythranrc section [typing] is valid and options are correct
INFO: pythranrc section [compiler] is valid and options are correct
running build_ext
<font color="#06989A">new_compiler returns &lt;class &apos;distutils.unixccompiler.UnixCCompiler&apos;&gt;</font>
building &apos;GLNetEISimLib&apos; extension
C compiler: x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC

creating /tmp/tmph73gipw6/tmp
compile options: &apos;-DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_BLAS -I/home/mschappo/.local/lib/python3.6/site-packages/pythran -I/home/mschappo/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c&apos;
extra options: &apos;-std=c++11 -fno-math-errno -w -fvisibility=hidden -fno-wrapv&apos;
x86_64-linux-gnu-gcc: /tmp/tmp00xtcn8d.cpp
<b>x86_64-linux-gnu-gcc:</b> <font color="#EF2929"><b>internal compiler error: </b></font>Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See &lt;file:///usr/share/doc/gcc-7/README.Bugs&gt; for instructions.
WARNING: Compilation error, trying hard to find its origin...
WARNING: Nop, I&apos;m going to flood you with C++ errors!
CRITICAL: Cover me Jack. Jack? Jaaaaack!!!!
E: error: Command &quot;x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DENABLE_PYTHON_MODULE -D__PYTHRAN__=3 -DPYTHRAN_BLAS_BLAS -I/home/mschappo/.local/lib/python3.6/site-packages/pythran -I/home/mschappo/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /tmp/tmp00xtcn8d.cpp -o /tmp/tmph73gipw6/tmp/tmp00xtcn8d.o -std=c++11 -fno-math-errno -w -fvisibility=hidden -fno-wrapv&quot; failed with exit status 4</pre>

**Comment by mgirardis** [comment]
it seems that this error was actually a compiler (gcc) bug...

**Comment by serge-sans-paille** [comment]
That's due to pythran generating too large (or complex) of a file. I'll try to investigate that.
