### ISSUE TITLE
installation manual on windows

### ISSUE THREAD

**Issue by gdementen** [serge-sans-paille/pythran#1381]
Would it be possible to add some instructions on how to get a working Pythran installation on Windows (preferably using conda)? It would be highly appreciated. Yes, pythran installs fine and even translates my python code to C++ but then it tries to compile the generated C++ using my installed VC++ compiler which fails. I know VC++ is not a supported compiler but what should I use and how do I configure that?

**Comment by serge-sans-paille** [comment]
We have a problem with Visual Compiler... Would that be ok to rely on clang on windows? I can try that path...

**Comment by gdementen** [comment]
Sorry, I don't know (hence the question). I am an experienced Python programmer, but once it crosses the C barrier, it is out of my comfort zone.

**Comment by serge-sans-paille** [comment]
Can you test branch #1391 ?

**Comment by gdementen** [comment]
I just tested it and it works fine for my **simple** tests when setting the CXX variable in pythran config file (I never managed to do it using the config command line option, but that's probably just me), though it spewed a lot of warnings. However, I just also realized that a recent version of VC++ also appears to work fine (I just upgraded my old Visual Studio environment to the 2019 version, which includes VC++ 14.2) ! Thanks a lot for your work.

**Comment by serge-sans-paille** [comment]
Cool, closing the issue then.
