### ISSUE TITLE
Possible memory leak in dict as function result

### ISSUE THREAD

**Issue by m-romanov** [serge-sans-paille/pythran#1384]
### Reproduction steps
1. Pythran module
```
#pythran export dict_test(float[:])
def dict_test(v):
    return {'a': v}

#pythran export list_test(float[:])
def list_test(v):
    return [('a', v)]
```
2. Compilation without options: `pythran ./dict_test.py`
3. Usage script:
```
import dict_test as dt
import numpy as np

for i in range(10000):
    _=dt.dict_test(np.random.rand(20000))
```
### Result
The last script memory usage is 1.5GB.
Each call of pythran function leads to additional memory usage.

But it works correctly with a list of tuples instead of a dict.
In case we change last line to `_=dict(dt.list_test(np.random.rand(20000)))` there is no additional memory usage, just initial 16MB.

**Comment by serge-sans-paille** [comment]
#1386 should do the trick, can you confirm? Anyway, thanks a lot for spotting that one o/
