### ISSUE TITLE
numpy.heaviside not supported and ufunc

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1388]
I get a code using https://docs.scipy.org/doc/numpy/reference/generated/numpy.heaviside.html

The easy solution for me was to implement what I needed in Python.

```
def heaviside(x1s, x2):
    ret = np.empty(x1s.shape, dtype=np.int8)
    for i, x1 in enumerate(x1s):
        if x1 < 0:
            ret[i] = 0
        elif x1 > 0:
            ret[i] = 1
        else:
            ret[i] = x2
    return ret
```

When I see that, I feel that it would be good to have in Pythran something similar to http://numba.pydata.org/numba-doc/dev/user/vectorize.html

If we care about pure Numpy compatibility, there is the numpy API https://docs.scipy.org/doc/numpy/reference/generated/numpy.frompyfunc.html

**Comment by serge-sans-paille** [comment]
@paugier #1389 should do the trick

**Comment by serge-sans-paille** [comment]
An yeah ufunc generation would be good to have, I like the 'do it in a numpy-compatible way' approach :-)
