### ISSUE TITLE
SyntaxError: 'break' outside loop

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#1393]
This example:

https://gist.github.com/nbecker/058b8f8d03d50df0471d60df1a69fc85

gives:
    '<constant_folding>', 'exec'),
  File "<constant_folding>", line 8
SyntaxError: 'break' outside loop

But the break is within a loop, and python3 sees no syntax error.

**Comment by serge-sans-paille** [comment]
(side note, if I'm not mistaken, your code should be `np.abs (pts - center)` and not `np.abs (pts) center`, and accept an array instead of a list as second parameter)

Got it, I'll have a look later in the day. Thanks for reporting o/
