### ISSUE TITLE
pts_within_radius2.py fails to compile (g++ or clang++)

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#1401]
Same test (with your small correction), but now fails to compile with 
Successfully installed pythran-0.9.4.post0

Error is:
E: Invalid argument type for function call to `Callable[[T1, Callable[[Iterable[T2]], Array[0 d+, T3]]], ...]`, tried Callable[[Iterable[T0]], List[T0]] (line 14)

gcc-c++-9.2.1-1.fc30.x86_64

**Comment by serge-sans-paille** [comment]
Can you provide me a link to the test case :-) It sure reminds me of something, but I can't find it anymore ^^!

**Comment by nbecker** [comment]
https://gist.github.com/nbecker/058b8f8d03d50df0471d60df1a69fc85

**Comment by serge-sans-paille** [comment]
Thanks, I can reproduce your error. It looks like a python error (like, in the input):

``pts - center`` is invalid if pts is a ``complex list``.
