### ISSUE TITLE
-e flag no longer generates C++ code for functions that don't have a export.

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1407]
According to the doc, the -e flag generates C++ code for functions even if there's no export. This seems to be broken with the latest version.

**Comment by serge-sans-paille** [comment]
You're probably the sole user of that feature ;-) enjoy the fix!

**Comment by jeanlaroche** [comment]
Oh thank you so much man!!! I was going to scramble to put fake import statements! ah ah ah!!!
This is an absolute killer feature man! I don't understand why other people haven't caught up on it. I need to do more evangelizing!
