### ISSUE TITLE
 undefined reference to `cblas_ddot'

### ISSUE THREAD

**Issue by somewheve** [serge-sans-paille/pythran#1414]
I try to install python-pythran on Arch linux using aurman and success

But when I try to use pythran ***.py , error occurs 

```
/usr/bin/ld: /tmp/tmpcoep4lgu/tmp/tmpcoep4lgu/source.o: in function `main':
/tmp/tmpcoep4lgu/source.c:6: undefined reference to `cblas_ddot'
collect2: 错误：ld 返回 1
```

Environment:
```
Linux archlinux 5.3.11-arch1-1 #1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux

Python in System: 2.7, 3.7, 3.8 
```
I don't know how to fix it.

Hope for your reply

**Comment by somewheve** [comment]
gcc version 9.2.0 (GCC)

**Comment by serge-sans-paille** [comment]
Does it work if you install openblas and that to your `~/.pythranrc` file:

```
[compiler]
blas=openblas
```

?

**Comment by serge-sans-paille** [comment]
What's the output of ``pythran --version`` ?

**Comment by somewheve** [comment]
it works when I add the code in ~/.pythranrc
```
[compiler]
blas=openblas
```

^_^ ni hao, I AM THE person who sends email to you!

**Comment by serge-sans-paille** [comment]
I'm still interested in exploring the original issue... what system are you
running on? Ubuntu?
