### ISSUE TITLE
Are objects declared at the top level immutable? 

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1417]
```
AA = [1,2,3]

#pythran export test()
def test():
    print(AA)
    AA.append(4)
    print(AA)            <- prints [1,2,3,4] in python, but [1,2,3] with pythran
```
The code above behaves differently in python and pythran. In python, calling test shows that the append() did work. In pythran it does not.
Is there something special about objects declared in the top level?
If I move the declaration of AA inside test(), then things work OK...

**Comment by serge-sans-paille** [comment]
Yes they are. We should print an error for such codes, and we can do that
because we correctly model function effects.
