### ISSUE TITLE
Is it possible to import "Python" third party modules?

### ISSUE THREAD

**Issue by sullyfischer** [serge-sans-paille/pythran#1436]
This may be a pretty newbie question, but it's something I've been wondering about both Pythran and Cython: Is it possible to import "Python" third party modules?

For example this is the code I'm playing around with:
```
import rsa

#pythran export key_generator
def key_generator():
    return rsa.newkeys(512)
```

Which running `pythran sample.py` gives me:
```
CRITICAL: I am in trouble. Your input file does not seem to match Pythran's constraints...
E: Module 'rsa' not found.
```

**Comment by serge-sans-paille** [comment]
In Cython: yes (but don't expect significant performance improvment for these parts)
In Pythran: no

**Comment by serge-sans-paille** [comment]
Closing the issue, as there's no plan to support that feature in the future. Everything that happens within Pythran is pure native code.
