### ISSUE TITLE
Feature request: disable pythran optimization/analyses to speed up compilation

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1449]
Title says it all. When debugging a large script by trial and error (which is often necessary) speeding up the pythran compilation would be tremendously helpful. Perhaps disabling some of the analysis would help make the compilation faster.
Note that passing the -O0 flag to pythran makes the C++ compilation faster, so that's already a small time saving.

**Comment by serge-sans-paille** [comment]
`pythran --config 'pythran.optimizations='` should do the trick, but it's not. i'll investigate

**Comment by serge-sans-paille** [comment]
Closed by #1450
