### ISSUE TITLE
Enum support

### ISSUE THREAD

**Issue by adam-urbanczyk** [serge-sans-paille/pythran#1462]
After looking at the docs I did not find anything regarding enum support. Are there any plans of adding it? If not, how much work it would be for someone not experienced with this project? BTW: I'd like to use pythran to quickly prototype (and validate) some numerical kernels in python and then use them in pure C++.

**Comment by serge-sans-paille** [comment]
That's not in the plans, but thing can evolve! What are the typical use case you're interested in?

Your use cas is generally pretty well supported, @jeanlaroche is doing exactly the same.

**Comment by serge-sans-paille** [comment]
https://docs.python.org/3/library/enum.html#functional-api is the easiest way for us to support it.

**Comment by adam-urbanczyk** [comment]
Thanks for the quick reply @serge-sans-paille . The use case would be to develop numerical algorithms (e.g. a QP solver) in python and then automatically convert them to C++ by means of pythran. To my understanding everything is in place but it would be just nicer to pass around enums (e.g. exit flags or configuration switches) i.s.o. ints.

**Comment by serge-sans-paille** [comment]
> To my understanding everything is in place

Correct.

>  it would be just nicer to pass around enums (e.g. exit flags or configuration switches) i.s.o. ints.

I've been thinking some about it, and it's going to be difficult. Enum classes are created dynamically on the Python side, we don't want to go to far in that direction. You can still pass integers, or the string version of the enum.
