### ISSUE TITLE
Error using open?

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1469]
The following code compiles with the latest pythran, but upon execution the following error results:
```
TypeError: Invalid call to pythranized function `test()'
Candidates are:

    - test()
```
```
import numpy as np

#pythran export test()
def test():
    f = open('test.data','rb')
    a=f.read()
    return a
```

**Comment by serge-sans-paille** [comment]
I cannot reproduce :-/

**Comment by jeanlaroche** [comment]
Me neither with the latest pythran. I don't know what happened. Sorry for wasting your time, closing the bug.
