### ISSUE TITLE
Feature request: separate .cpp and .hpp with the -e option?

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1470]
I'm using the -e option, which currently generates a single .cpp file. This works, but much better would be for me to have a separate .hpp file that would contain all the struct definitions, typedefs etc, and the .ccp file that would contain the definition of the operators.

I can write a script to do that but that's not going to be super robust.
If the above is not easy/doable, could you possibly output a visible marker at the end of the struct declarations and at the start of the implementations, to help my script?
Thanks!
Jean

**Comment by serge-sans-paille** [comment]
`-e` only generates templated code. I don't understand what's the use of the split here?

**Comment by jeanlaroche** [comment]
> `-e` only generates templated code. I don't understand what's the use of the split here?

I've found that it's possible to include only part of the file (for example, the part that defines the functors) into an h file (so I can declare a local variable as a result type), without needing the implementation of the operator(). Of course the implementation is needed eventually but that can be compiled in another .cpp file, so I don't have to recompile it every time. 
But never mind, I'm managing.

**Comment by serge-sans-paille** [comment]
Yeah, I'm not going to go on further that way, `-e` is already a borderline option ;-)
