### ISSUE TITLE
If one function is #pythran exported other functions are omitted from -e output.

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1471]
Process this with -e.
func1 is in the .ccp output but not func2.
If the #pythran export directive is removed both are present.
```
import numpy as np

#pythran export func1(float)
def func1(x):
    return 2*x

def func2(x):
    return 5*x
```

**Comment by serge-sans-paille** [comment]
I have the patch, but I wonder if it's a bug or a feature? I mean, why would you export one function for a file meant to be processed by `-e`? Because it's a testing export or something? Can you provide me with a use-case for that patch?

**Comment by jeanlaroche** [comment]
I use the export to run a unit test from python, so I export the unit test function, while processing without -e. Then when I process with -e to include the code into my code base I have to remove any export, or nothing gets included. But if you think it's better this way, I have a way to handle it, so no worries at all...

**Comment by serge-sans-paille** [comment]
This is the test case I was overseeing. Then I wonder: if you need `func1` and `func2`, the best thing to do is to put an export for each, so that you test both, right?

**Comment by jeanlaroche** [comment]
Well, I can't do that because currently, I can't export a function that returns a tuple, the way I do it. Python complains when you modify a tuple (as expected) but I have to declare the tuple as a tuple in pythran. So there's a conflict right there. Essentially, I'm not able to test my code from python if I need to pass the tuple back and forth from "pythran to python" so to speak...

**Comment by serge-sans-paille** [comment]
ok. you're use case is rather borderline, I'll stick to current situation which is more consistent. What you can do is don't use export at all, and generate a `.pythran` file or a `#pythran export` line on the fly when testing.
