### ISSUE TITLE
list comparisons misbehaving

### ISSUE THREAD

**Issue by gamask** [serge-sans-paille/pythran#1477]
Code below is passed to pythran.
```python
#pythran export f1 (int list, int list)
def f1 (x, y):
    print (x < y, x == y)
    #print (x > y)              # THIS DOESN'T COMPILE

#pythran export f2 (int list list, int list)
def f2 (x, y):
    import bisect
    print (bisect.bisect_right (x, y))
```

Code below calls the function above.
```python
from DEL_demo import f1, f2

                                # python output         pythran output
f1 ([1,1], [1,1])               # False True            0 True
f1 ([1,1], [1,2])               # True False            -1 False
f1 ([1,1], [1,0])               # False False           1 False

f2 ( [[1,1],[2,2]], [1,1] )     # 1                     1
f2 ( [[1,1],[2,2]], [2,2] )     # 2                     2
f2 ( [[1,1],[2,2]], [1,2] )     # 1                     0
f2 ( [[1,1],[2,2]], [2,3] )     # 2                     0
```

Several issues here.
1. Commented out line in f1 makes pythran crash.
2. less-than comparison on two 1d lists return boolean in python. In pythran it seems to behave like cmp function did in python 2.
3. bisect.bisect_right behaves correctly if second list exists in first list. Otherwise it always returns 0.

It seems to me that all these cases are related, which is why I only opened one issue.

**Comment by serge-sans-paille** [comment]
Yeah, that's stupide, we only implemented `<`, `!=`  and `==` operator, I'll fix that. Thanks for providing such a detailed test case.
