### ISSUE TITLE
Can't choose the new filename without pointing out the extension

### ISSUE THREAD

**Issue by rfiischer** [serge-sans-paille/pythran#1481]
I wanted to pass the `output_file` argument to `pythran.compile_pythranfile`, but I want to make my code compile both on Linux and Windows, so I don't know beforehand the extension of the file. It would be nice to have an option where the extension is set to automatic, and one can change only the module's name.

**Comment by serge-sans-paille** [comment]
What about a magic format like `-o my_filename.%{ext_suffix}` ?

**Comment by serge-sans-paille** [comment]
More likely `-o my_filename%{ext}` btw

**Comment by rfiischer** [comment]
That would be nice! And would be nice also if available at the `pythran.compile_pythranfile` function. My problem is that the user is in charge of compiling the modules beforehand. Therefore, if he doesn't compile, since the `.pyd/.so` and the `.py` files have the same name and are in the same directory, he still loads the `.py` module. I would like to prevent that by having the compiled module have a different name, but maintaining the `.cp37... .pyd` extension. Do you suggest a better and more clever way of doing this with the current version of the package? I have already tried putting a `logging.warning` on the `.py`, but that is misinterpreted by Pythran, even though it doesn't affect the `# pythran export` function.

**Comment by paugier** [comment]
Hi @rfiischer, [transonic](https://foss.heptapod.net/fluiddyn/transonic) could be use for that. it emits a warning it the file is not compiled. it works out of the box on Linux and Windows.
