### ISSUE TITLE
numpy array weirdness

### ISSUE THREAD

**Issue by gamask** [serge-sans-paille/pythran#1496]
pythran code:
```python
#pythran export outer (float64 [], float64 [][][], float64 [])
def outer (x, cache, cache_x0):
    
    #if x[0] == 5.:
    if True:
        cache_slice = cache[-1]
    else:
        cache_slice = cache[-1]
    
    print (cache_slice)
    
    return 123.
```

python code:
```python
import numpy

from DEL_pythran_test import outer

x = numpy.full(shape=(1), fill_value = 123.)
cache = numpy.full(shape=(2, 2, 2), fill_value = 234.)
cache_x0 = numpy.full(shape=(3), fill_value = 345.)

print (outer (x, cache, cache_x0))
```

If we comment out "if True" in function "outer" and uncomment "if x[0] == 5.", then the "print (cache_slice)" line will print an empty array.
Otherwise it prints the actual value of cache[0], which is [[234., 234.], [234., 234.]].

This is using commit fc07a71daf5f8c177bdd51dc4c574659ced873a6, which is the latest as of this writing.

**Comment by serge-sans-paille** [comment]
Weirdness confirmed, I'll have a look!

**Comment by gamask** [comment]
Thanks.

**Comment by serge-sans-paille** [comment]
@gamask just so you know, I have a patch for this one, but it also implies a big performance regression, so I need more thoughts :-) (and time)

**Comment by gamask** [comment]
You mean 5140914?
I was using that for a while. Didn't notice any performance hits in my use case.
I have abandoned the thing where I encountered this so it's no longer relevant to me. Take your time :D

**Comment by serge-sans-paille** [comment]
@gamask : this is finally fixed in master. You had me do *a lot* of work to fix that in a correct way. i don't know if I should thank or hate you ;-)
