### ISSUE TITLE
Best of Pythran, Cython, Nuitka

### ISSUE THREAD

**Issue by sirinath** [serge-sans-paille/pythran#1503]
I am wondering if there is a possibility to merge the best of each to one project so the end-users will get the best possible transpiler than different projects with duplication and different strengths and weaknesses.

**Comment by serge-sans-paille** [comment]
You may want to have a look at https://pypi.org/project/transonic/. It targets pythran, numba and cython. Nuitka doesn't have a strong focus on scientific computing, as far as I know.
