### ISSUE TITLE
Pythran outputs incorrect C++

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1509]
The following code compiles and runs, but does not do the right thing!
```
#pythran export test(int, int[])
import numpy as np
def test(X, Y):
    for ii in range(0, 2):
        if Y[ii] > 2:
            print('Error, Y[ii] should be less than 2 ', Y[ii])
            X = Y[ii] #<- This is optimized away by pythran!!!!
            continue
        X = Y[ii]
    return X

# python -c "from test import *; import numpy as np;  print(test(1,np.array([1,10])))"
```
In fact, looking at the C++ code generated: you can see that X_ = Y.fast(ii); is missing before the continue.
```
      for (long  ii=0L; ii < 2L; ii += 1L)
      {
        if ((pythonic::operator_::gt(Y.fast(ii), 2L)))
        {
          pythonic::__builtin__::functor::print{}(pythonic::types::str("Error, Y[ii] should be less than 2 "), Y.fast(ii));
          continue;
        }
        X_ = Y.fast(ii);
      }
```
Running the code in python and pythran does not output the same value...
`python -c "from test import *; import numpy as np;  print(test(1,np.array([1,10])))"
`

**Comment by serge-sans-paille** [comment]
Fascinating. You found a bug in beniget, which thinks that the first assignment to X has no use.

**Comment by jeanlaroche** [comment]
I knew you'd enjoy this one! It's a logic bug for once!
