### ISSUE TITLE
omp reduction failure on gcc

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1510]
I'm getting a compile error with a relatively simple function using omp reduction(+:) using gcc, which works fine in clang under linux. This is the function:
```
#pythran export apply(complex128[][], complex128[][])
def apply(E, x):
    p = E.shape[0]
    n = x.shape[1]
    xo = 0 + 0j
    #omp parallel for collapse(2) reduction(+:xo)
    for k in range(p):
        for i in range(n):
            xo += E[k, i] * np.conj(x[k, i])
    return xo
```
This fails with `error: user defined reduction not found for ‘xo’` using gcc-9.2.1, but compiles fine with clang. Note that it does not depend on the collapse in reduction either, i.e. the below fails as well:
```
#pythran export apply(complex128[][], complex128[][])
def apply(E, x):
    p = E.shape[0]
    n = x.shape[1]
    xo = 0 + 0j
    i = 2
    #omp parallel for reduction(+:xo)
    for k in range(p):
        #    for i in range(n):
        xo += E[k, i] * np.conj(x[k, i])
    return xo
```

What's weird, I have almost the same code somewhere in my larger code-base and it compiles fine (similar the matmul.py from the t est cases).

**Comment by serge-sans-paille** [comment]
Yeah, OpenMP disallowsthat, as pointed out here:

    http://forum.openmp.org/forum/viewtopic.php?f=3&t=59

However, the following should work:

```python
import numpy as np
#pythran export apply(complex128[][], complex128[][])
def apply(E, x):
    p = E.shape[0]
    n = x.shape[1]
    xo = 0 + 0j
    i = 2
    #omp declare reduction(+: complex: omp_out += omp_in)
    #omp parallel for reduction(+:xo)
    for k in range(p):
        #    for i in range(n):
        xo += E[k, i] * np.conj(x[k, i])
    return xo
```

Maybe we could generate that by default?

**Comment by serge-sans-paille** [comment]
> Maybe we could generate that by default?

For consistency with OpenMP, we probably shouldn't though.

**Comment by cycomanic** [comment]
Ok I was not aware that that's not in the standard. 

I don't have strong opinions on doing the above by default. I think consistency is a secondary concern here considering that clang compiles this just fine. 

I think if the g++ error would a bit clearer (I had the same error on a very different issue before), I probably would not have been so confused.  Anyway feel free to close wont fix.

**Comment by serge-sans-paille** [comment]
ok, a sane default for complex across compilers make sense, implemented that.
