### ISSUE TITLE
Is this expected?

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1516]
Consider this code
```
#pythran export test()
import numpy as np

def A():
    Tuple = tuple([2])
    return Tuple

def C(Tuple):
    Tuple[0] = 3
    print('Value', Tuple[0]) #<- Appears to be modified.

def test():
    YY = A()
    C(YY)
    print('Value', YY[0])  # <- is not modified.
```
This code can't be run in python because of the tuple. But pythran can and does compile it. Is it normal, expected that the value reported by test() YY[0] is not modified in the function test()?

**Comment by serge-sans-paille** [comment]
The implementation of tuple in pythonic doesn't prevent assignment to elemnts. So you can use that if you directly use the .cpp file. That being said, it's not something you should (or even can) rely on, it may change in the future...
