### ISSUE TITLE
Compilation error if variable isn't initialized outside if statement

### ISSUE THREAD

**Issue by gamask** [serge-sans-paille/pythran#1528]
```python
#pythran export f (float64 [][], int)
def f (array, x):
    case = 0
    if x == 1:
        case = 1
    else:
        case = 2
    
    array[0][0] = case
```

Commenting out "case = 0" line causes the compilation error.

**Comment by serge-sans-paille** [comment]
That's a funny one. The issue actually comes from `case` which is a C++ reserved identifier. We try hard to protect these, But I forgot one. That's an easy fix, thanks for reporting nevertheless!

**Comment by gamask** [comment]
That thought crossed my mind but for some reason I didn't try just changing the name of the variable. Ugh...
Thanks for your work man.
