### ISSUE TITLE
call with star arguments not supported

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#1532]
I was happy to see that itertools product was supported, but it seems not for my use case.
given a list of lists of ints like: 
[[0,1,2,3],[0,1],[0,1]]
represents possible values for a sequence of 3 symbols (the 1st could take values {0,1,2,3}, the
2nd and 3rd can take values {0,1}).
Suppose prefix is [0,1,2,3], s is 0, and suffix is [0,1].  
    all_syms = product (*prefix, [s], *suffix)
is supposed to form all possible combinations of [0,1,2,3], [0], [0,1]; e.g., [[0,0,0],[1,0,0]...[3,0,1]]
The length of the argument 'syms' is not fixed: in the example it is 3 but that's just an example.

Don't know any other way to write this without the *prefix
```
def mag_sqr (z):
    return z.real * z.real + z.imag * z.imag

# pythran export find_ll (complex, int list, complex[] list, float[] list)
def find_ll (r, syms, consts, lls):
    d = mag_sqr (r - sum([c[s] for c,s in zip (consts, syms)]))
    this_ll = sum (lls[u][sym] for u,sym in enumerate(syms))
    return -d + this_ll

from itertools import product
# pythran export find_ll_u (complex, int, int, int list list, complex[] list, float[] list)
def find_ll_u (r, u, s, symss, consts, lls):
    N = len(symss)
    prefix = [symss[i] for i in range(u)]
    suffix = [symss[i] for i in range (u+1,N)]
    all_syms = product (*prefix, [s], *suffix)
    #print (list(all_syms))
    return sum(find_ll (r, list(syms), consts, lls) for syms in all_syms)
```

**Comment by serge-sans-paille** [comment]
Thanks for the heads up! It's always a pleasure to see old-time users hanging around :-)
I can think of a way to support start-arguments for tuples (because they have a fixed size) of for fixed-size list, but for generic list. In your example, `prefix ` has a dynamic len, which is... super-challenging ;-). Let me think some more about this though.

**Comment by serge-sans-paille** [comment]
ok, one month later, I can say that I don't see a way for us to support that. At least we have a nice and clear error message ;-)

```console
% pythran a.py
CRITICAL: I am in trouble. Your input file does not seem to match Pythran's constraints...
a.py:16:24 error: Call with star arguments not supported
----
    all_syms = product (*prefix, [s], *suffix)
                        ^~~~ (o_0)
----
