### ISSUE TITLE
Path is too long for windows

### ISSUE THREAD

**Issue by gamask** [serge-sans-paille/pythran#1539]
Trying to compile a file that worked flawlessly on linux would invariably give this error.
I had already applied the registry fix that is frequently suggested.
Something like SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled. Set it to 1. I'm not on windows right now so I can't verify the exact registry key.
This was on windows 10, with python 3.7, almost certainly 3.7.6.

My file was about 2000 lines long. It imports math and numpy.

Here's the weird part.
If I removed a bunch of functions from my file it would start working when I had only about 700-800 lines left. It doesn't matter which functions I removed so long as the code was still valid (nothing referencing removed functions).
Then I tried removing only blank lines and comments. And it worked. Lucky for me my file had a ton of comments and blank lines, so it shrank significantly, I think to about 750 lines when I removed comments and blank lines.

I know this project doesn't officially support windows, but I thought I'd bring this up 'cause it doesn't seem like it has anything to do with actual code (which was completely unchanged!!!), but maybe some random windows quirk.

**Comment by serge-sans-paille** [comment]
Hi @gamask. that's a super strange one. I fail to understand the link between the long path and the size of the file... can you report the actual error, with backtrace? I'm indeed not very fluent in Windows, but it's worth having a look!

**Comment by gamask** [comment]
CRITICAL: Chair to keyboard interface error
E: stat: path too long for Windows

That's it.
I got it to happen with some dummy code just now.
Below is the code I used to generate the source file that I then tried compiling.
When looping to 400 it worked. When looping to 600 it gave the same error as my real code.

DEL_generator.py:
```python
print ('import numpy')
print ('import math')

for i in range(600):
    print ('''
#pythran export f_%d
def f_%d ():
    return 123 + %d
    ''' % (i, i, i))
```

python3.7.exe DEL_generator.py | Out-File DEL_source.py -encoding ASCII

Then try compiling DEL_source.py.

**Comment by serge-sans-paille** [comment]
Can you confirm #1545 fixes your issue?

**Comment by gamask** [comment]
It does.
