### ISSUE TITLE
use pocket fft in pythran

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1560]
Both scipy and numpy have moved to pocketfft for their implementations, which are significantly faster for power-2 length ffts. In particular the scipy implementation uses the c++ version using pybind11, which might be relatively easy to integrate in pythran. I was wondering if there's plans/interest in changing the implementation to use that instead of the current fftpack? I'm not a c++ programmer (and I just had a look and the pocketfft code does not straight forward to me), but if there's interest I can try to  learn some c++ and contribute, unless someone else is quicker.

**Comment by serge-sans-paille** [comment]
I like that the source seems easy to vendor, esp. as pythran is a header-only library. I'd be very happy if you try to port it, and I'd also happily guide you in the process.

**Comment by cycomanic** [comment]
Ok, I'm a bit flat out the next two weeks, but will start to look into this after

**Comment by serge-sans-paille** [comment]
great!

**Comment by serge-sans-paille** [comment]
@cycomanic I think you can close this one thanks to your work on #1689 and #1705
