### ISSUE TITLE
cblas.h not found if only openblas installed

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1562]
I've just installed a new PC  using opensuse and did not install cblas, but only openblas. When I was trying to compile some code I got a compilation error that cblas.h was not found. For openblas `cblas.h` is found under `/usr/include/openblas/` and the system installed numpy does not return include dirs for `numpy.distutils.system_info.get_info("openblas")`, hence the file is not found. 

As a workaround installing cblas headers or adding /usr/include/openblas to the include_dirs will work. Not sure what the best long-term fix for this is. It seems to me like numpy really should be returning the include_dir. It might be worth putting a pointer into the documentation about his though.

**Comment by serge-sans-paille** [comment]
Yeah, it's disturbing that we cannot rely on numpy. And feeding your `.pythranrc` correctly is not a satisfying solution either.And I'm not very comfortable with shipping the headers. Maybe I should just package openblas in pip?

**Comment by serge-sans-paille** [comment]
There's also the pythran-openblas package, but it implies linking with the static version of openblas, not super-satisfying. I'll update the doc.
