### ISSUE TITLE
Problem still exist with resizing an array previously declared in a tuple.

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1572]
Pythran still misbehaves with the code below:
self[0] is initializes as a (1,1) array, then when an attempt is made to give it a shape of (100,100) this fails.
```
# pythran export test()
import numpy as np

def A():
    self_xx = np.zeros((1,1))
    self = tuple([self_xx])
    return self

def B(self, D, C):
    print(D, C)
    self[0] = np.zeros((D, C))
    print('self[0]', self[0].shape)

def test():
    fr = A()
    B(fr, 100, 100)
```

**Comment by jeanlaroche** [comment]
OK my bad. Adding a print('fr[0]', fr[0].shape) in test() fixes the issue. Argh. I was trying to isolate a real issue I'm seeing along these lines. CRAP

**Comment by jeanlaroche** [comment]
Question:
why is:
```
(BuildVEnv) jlaroche-mbp:Freeze(devel)$ pythran -lblas TD.py --config 'pythran.optimizations=pythran.optimizations.ConstantFolding pythran.optimizations.PartialConstantFolding pythran.optimizations.DeadCodeElimination pythran.optimizations.IterTransformation pythran.optimizations.ComprehensionPatterns pythran.optimizations.ListCompToGenexp pythran.optimizations.LoopFullUnrolling pythran.optimizations.ModIndex pythran.optimizations.PatternTransform pythran.optimizations.RangeLoopUnfolding pythran.optimizations.RangeBasedSimplify pythran.optimizations.Square pythran.optimizations.Inlining pythran.optimizations.InlineBuiltins pythran.optimizations.ListToTuple pythran.optimizations.TupleToShape pythran.optimizations.RemoveDeadFunctions pythran.optimizations.ForwardSubstitution pythran.optimizations.ListToTuple'
```
different than
```
pythran -lblas TD.py
```
The former lists all the optimizations available (from the __init__.py file in the optimizations directory). So I would imagine all of these are on by default, but I get different results in both cases. The former works, the latter does not.

**Comment by serge-sans-paille** [comment]
The list of optimization used is defined in pythran/pythran.cfg. order matters!

**Comment by serge-sans-paille** [comment]
> Does pythran.optimizations=pythran.optimizations.ListToTuple indicate that that's the only optimization being run?

yes

**Comment by serge-sans-paille** [comment]
As a side note: the code above is not valid Python:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in test
  File "<stdin>", line 3, in B
TypeError: 'tuple' object does not support item assignment
```

**Comment by jeanlaroche** [comment]
Yes, of course, I'm aware of that! I'm bending the rules because pythran allows me to do it (and it's really the only way I can create and use a tuple from the C++ created by pythran!).

**Comment by jeanlaroche** [comment]
Cool. I'm going to check it this pm

**Comment by jeanlaroche** [comment]
Well, it's still not working for me:
This is the typical situation: These values are declared in my __init__ function.
```
        flux                =    np.zeros(0)
        #flux                =    np.zeros(int(0*bogus) # < - this makes it work.
       
```
Later in my code, during run time, I get this assertion:
```
Assertion failed: (N == v && "consistent init"), function check_type, file /Users/jlaroche/pyent.py3.Darwin.x86_64/lib/python3.7/site-packages/pythran-0.9.6-py3.7.egg/pythran/pythonic/include/types/tuple.hpp, line 157.
```
The code, again, is too complex to post here. But maybe that will give you an idea for what's going on?

**Comment by serge-sans-paille** [comment]
@jeanlaroche can you double check if this is fixed or not in the latest release?

**Comment by jeanlaroche** [comment]
@serge-sans-paille Nope. I get exactly the same assert with the latest release. I *might* be able to make a pruned-down example if that's useful.

**Comment by jeanlaroche** [comment]
I'm going to close this, and open a new bug that has a smaller example.
