### ISSUE TITLE
np.sort is slower in pythran than in numpy

### ISSUE THREAD

**Issue by exenGT** [serge-sans-paille/pythran#1580]
Hi,

I found that np.sort is slower in pythran than in native numpy. The test code is the following:

sort_pythran.py:
```
# pythran export fastsort(float [:,:])
import numpy as np

def fastsort(A):
    return np.sort(A)
```

sort_pythran_main.py:

```
import numpy as np
from timeit import default_timer as timer
from sort_pythran import fastsort

A = 10 * np.random.rand(1000, 100)

start_1 = timer()
A_sorted_1 = np.sort(A)
end_1 = timer()

start_2 = timer()
A_sorted_2 = fastsort(A)
end_2 = timer()

print("time spent are {}, {}".format(end_1 - start_1, end_2 - start_2))
```

The sort_pythran.py is compiled using:

`pythran -march=native -DUSE_XSIMD sort_pythran.py -o sort_pythran.so`

with pythran version 0.9.5, python version 3.7.7, gcc and g++ version 9.3, numpy version 3.19.0.

A typical result shows:

`time spent are 0.004469064064323902, 0.006822462659329176`

corresponding to the numpy and pythran results.

**Comment by serge-sans-paille** [comment]
Thanks for the report, I'll try to reproduce that timings :-)
