### ISSUE TITLE
Regression on argsort

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1611]
I'm getting a compilation error on this using the latest master.

```
import numpy as np

def B(U):
    U[0] = np.ones(100, dtype=int)
    idx = np.argsort(-U[1][U[0]])
    print(idx)

#pythran export fakeFreeze()
def fakeFreeze():
    B([np.zeros(100),np.zeros(100)])
```

**Comment by serge-sans-paille** [comment]
No issue for me on master (da7ff57779336912e5ff9883b5d8e8ef5ffd484f)

**Comment by jeanlaroche** [comment]
Got the latest master, still fails to compile on macos. https://pastebin.com/Buy7m2EV

**Comment by jeanlaroche** [comment]
FYI
```
    idx = np.argsort(-U[1][U[0].astype(int)])
```
Fixes the compilation error.

**Comment by serge-sans-paille** [comment]
Well, the actual issue with your code is that `[np.zeros(100),np.zeros(100)]` is a list of array of double. When you do
`U[0] = np.ones(100, dtype=int)` you're not changing anything to that type information, so pythran still thinks U[0] is an array of double, thus the issue.

I cannot fix that :-)

**Comment by serge-sans-paille** [comment]
btw, thanks for the compilation error log, that helped a lot.

**Comment by jeanlaroche** [comment]
OK no worries,I'll fix my code. I know it's not easy but I wonder if it would be possible to alert the user when he/she's redefining a variable with a different type.
I've been burned by that many times.
But I've learned my lesson (apparently not 100% though! :D)
