### ISSUE TITLE
Blas issue

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#1614]
The latest master seems to behave backward when it comes to blas.
If I have 
```
[compiler]
blas=none
```
(and nothing else). In my pythran.rc, I get a compilation error. 
`/Users/jlaroche/pyent.py3.Darwin.x86_64/lib/python3.7/site-packages/pythran-0.9.5-py3.7.egg/pythran/pythonic/numpy/dot.hpp:14:10: fatal error: 'cblas.h' file not found
#include <cblas.h>`
To avoid it, I must add:
`include_dirs=/usr/local/opt/openblas/include` even though I've selected the blas=none option.

Then, if I then compile my code to create a .so file without including the -lblas flag, I get a run-time error: `ImportError: dlopen(/Users/jlaroche/Dev/Looper/TD.cpython-37m-darwin.so, 2): Symbol not found: _cblas_dgemm`
So the code is linked without blas, but still makes calls into the library.

**Comment by serge-sans-paille** [comment]
#1616 should do the trick, can you confirm?

**Comment by jeanlaroche** [comment]
No, I now get a different error:
https://pastebin.com/tkEPDaTh

```
[compiler]
blas=none
```

**Comment by jeanlaroche** [comment]
I confirm that if I use
```
[compiler]
blas=pythran-openblas
```
Things compile and run fine.

**Comment by jeanlaroche** [comment]
Also, FYI:
```
[compiler]
blas=openblas
include_dirs=/usr/local/opt/openblas/include
ldflags=-L/usr/local/opt/openblas/lib
```
If I don't add -lblas to my call to pythran, I get a run-time error `ImportError: dlopen(/Users/jlaroche/Dev/Looper/TD.cpython-37m-darwin.so, 2): Symbol not found: _cblas_dgemm`.
It seems to me that if we have any blas in the pythranrc, the -lblas flag should automatically be there, but it's not.

**Comment by serge-sans-paille** [comment]
I've been rethinking a bit about it, and event current patch shouldn't be needed. Why do you include "dot.hpp" ? Seems like you're using a feature that requires blas in the end...

**Comment by jeanlaroche** [comment]
> I've been rethinking a bit about it, and event current patch shouldn't be needed. Why do you include "dot.hpp" ? Seems like you're using a feature that requires blas in the end...

I didn't realize some features do require blas, I thought there were plain options for all the routines.
