### ISSUE TITLE
Awesome project!

### ISSUE THREAD

**Issue by fwsGonzo** [serge-sans-paille/pythran#1625]
I just want to give some praise where due: This project is amazing.

I am using it inside an emulated RISC-V emulator with a unique C++ environment. And now I can have Python syntax!
The only thing I'm trying to figure out now is how to "import" C++ functions into Python.

Feel free to close this. : )

**Comment by serge-sans-paille** [comment]
I'll close this as *WONT FIX* as being awesome is probably something we want to keep :-)

Concerning using third-party C++ functions, the only way to do that is through ctypes and pycapsules, as described in this document:

https://pythran.readthedocs.io/en/latest/examples/Third%20Party%20Libraries.html
