### ISSUE TITLE
Support for key argument in list.sort and sorted

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1657]
I work on improving a poor Python code that has been rewritten in C++ (with a 20x speedup!). It seems that there is a not understood bug in the C++ version. Since the C++ code is for us harder to modify/improve, I'd like to see if we can get similar speedup by rewriting it in better Python and using Pythran. The code involves manipulating many small Python objects so it is not easy. By cheating a bit, I managed to approach the C++ performance (my py version is now only ~1.5 times slower that the C++ version). For details see https://github.com/turbulencelyon/4d-ptv/pull/1

I see that it would be very useful if one can compile this will Pythran:

```
def fun():
    l = [(3, 0), (0, 3), (1, 1)]
    l.sort(key=(lambda elem: elem[1]))
    return l
```

@serge-sans-paille do you think Pythran could support this?

**Comment by serge-sans-paille** [comment]
Yes, we can.
