### ISSUE TITLE
performance regression 0.9.5 -> 0.9.6 (still present in 0.9.7 and master)

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1668]
I see a significant performance regression going from version 0.9.5 to version 0.9.7, which also is not fixed in current master. 

Pythran code
```python
import numpy as np

def apply_filter_pt1(E, wx):
    Xest = np.sum(E*np.conj(wx))
    return Xest

#pythran export cma_pt1(complex128[][], complex128[][][], float64, float64, int)
def cma_pt1(E, wxy, mu, R, os):
    pols, L = E.shape
    assert wxy.shape[0] == pols
    assert wxy.shape[1] == pols
    assert E.shape[1] <= wxy.shape[-1]
    ntaps = wxy.shape[-1]
    N = (L//os//ntaps-1)*ntaps
    err = np.zeros((pols, L), dtype=np.complex128)
    for k in range(pols):
        for i in range(N):
            X = E[:, i*os:i*os+ntaps]
            Xest = apply_filter_pt1(X, wxy[k])
            err[k,i] = (R-abs(Xest)**2)*Xest
            wxy[k] += mu*np.conj(err[k,i])*X
    return err, wxy 

def apply_filter_pt2(E, wx):
    Xest = 0+0j
    for i in range(E.shape[0]):
        for j in range(E.shape[1]):
            Xest += E[i,j] * wx[i,j].conj()
    return Xest

#pythran export cma_pt2(complex128[][], complex128[][][], float64, float64, int)
def cma_pt2(E, wxy, mu, R, os):
    pols, L = E.shape
    assert wxy.shape[0] == pols
    assert wxy.shape[1] == pols
    assert E.shape[1] <= wxy.shape[-1]
    ntaps = wxy.shape[-1]
    N = (L//os//ntaps-1)*ntaps
    err = np.zeros((pols, L), dtype=np.complex128)
    for k in range(pols):
        for i in range(N):
            X = E[:, i*os:i*os+ntaps]
            Xest = apply_filter_pt2(X, wxy[k])
            err[k,i] = (R-abs(Xest)**2)*Xest
            for j in range(pols):
                for l in range(ntaps):
                    wxy[k, j, l] += mu*np.conj(err[k,i])*X[j,l]
    return err, wxy  
```

test code:

```python
from scipy import signal
import numpy as np
from cma import cma_pt1, cma_pt2
from timeit import default_timer as timer

s = np.random.choice([1/np.sqrt(2)+1j/np.sqrt(2), -1/np.sqrt(2)+1j/np.sqrt(2),
                      -1/np.sqrt(2)-1j/np.sqrt(2), 1/np.sqrt(2)-1j/np.sqrt(2)],
                     10**5*2).reshape(2,-1)
s2 = signal.resample_poly(s, 2, 1, axis=-1)
s3 = s2 + 1e-1*(np.random.randn(*s2.shape)+1j*np.random.randn(*s2.shape))
s3 = s3.reshape(2,-1)

wxy0 = np.zeros((2,2,21), dtype=np.complex128)
wxy0[0][0][21//2] =1
wxy0[1][1][21//2] = 1

wxyin = wxy0.copy()
start = timer()
err, wxy = cma_pt1(s3, wxyin, 1e-3, 1., 2)
end=timer()
t_pythran1 = end-start
wxin = wxy0.copy()
start = timer()
err, wxy = cma_pt2(s3, wxyin, 1e-3, 1., 2)
end=timer()
t_pythran2 = end-start 
print("t1 = {}".format(t_pythran1))
print("t2 = {}".format(t_pythran2)) 
```

On linux (opensuse tumbleweed), relevant `.pythranrc` (previously tested for optimum performance):
```
[compiler]
CC=gcc
cxx=g++
blas=openblas
cflags: -O3 -ffast-math -mfpmath=sse -funroll-loops -march=native -fopenmp -std=c++14 -fno-math-errno -w -fvisibility=hidden -fno-wrapv -DUSE_XSIMD -DNDEBUG 
```

On my Ryzen 3600 system running the test I get:
```
t1 = 0.03784733099928417
t2 = 0.016423582999777864
```
When I use 0.9.7 
```
t1 = 0.045351794999078265
t2 = 0.1492349899999681
```
(0.9.6 and current master yields similar numbers). 

As you can see on the second function, where the vectorised functions have written explicitly I get a 10x performance regression. 

Doing a bit more digging I find that a significant part of the slowdown comes from the `-fopenmp` flag. If I recompile without the flag I get:
```
t1 = 0.030497308000121848
t2 = 0.04165376300079515
```
This somewhat reduces the impact, but is still more than a factor of 2.

**Comment by cycomanic** [comment]
Also on 0.9.5 removing the `-fopenmp` flag does not change the performance

**Comment by serge-sans-paille** [comment]
Thanks for reporting! I'll have a look and try to reproduce / investigate. Can you just check if, by change, #1671 has any impact?

**Comment by cycomanic** [comment]
With #1671  I see a small performance gain for t1 but no change for t2. The times on my i7 laptop are:

On 0.9.7:
```
t1 = 0.061820434988476336
t2 = 0.24748538702260703
```

#1671 :
```
t1 = 0.054640783986542374
t2 = 0.23640463699121028
```

These times are without `-DUSE_XSIMD` with `-DUSE_XSIMD` I actually get a slight performance regression as well (I don't think that was the case for the Ryzen system, but I can't test right now):
#1671
```
t1 = 0.07991087599657476
t2 = 0.23107781197177246
```
0.9.7
```
t1 = 0.08903820102568716
t2 = 0.24394032801501453
```

For comparison 0.9.5:
With `-DUSE_XSIMD`:
```
t1 = 0.04120065498864278
t2 = 0.02420520002488047
```
without `-DUSE_XSIMD`
```
t1 = 0.04207319999113679
t2 = 0.023693742987234145
```

So the performance regression with -DUSE_XSIMD is also gone

**Comment by cycomanic** [comment]
To add one more data point. 
If I compile without `-fopenmp` in cflags in 0.9.7 I get:
```
t1 = 0.05275357898790389
t2 = 0.10119961499003693
```
So that is a factor of two speedup. I'm not quite sure what is being parallelised, because the loops are explicit.

**Comment by serge-sans-paille** [comment]
Please tell me #1674 solves your issue :-)

**Comment by cycomanic** [comment]
Yes this fixes it. It also yields a bit of a speedup for the t1 case which is nice. However, there is still a small slowdown for using `-fopenmp` in the t1 case. I think this might be helped if it was possible prevent parallising some numpy functions in tight loops  (I mentioned this in a message to the list).  New numbers:

0.9.5 with `-fopenmp`
```
t1 = 0.038911096833180635
t2 = 0.02348867036635056
```
0.9.5 without `-fopenmp`
```
t1 = 0.03102979496664678
t2 = 0.02626108646703263
```

#1674 with `-fopenmp`
```
t1 = 0.03462139940044532
t2 = 0.02114343720022589
```
#1674 without `-fopenmp`
```
t1 = 0.025248845065167794
t2 = 0.02234717596632739
```

**Comment by cycomanic** [comment]
OK one more data point. Seems like gcc is smarter than clang:
using gcc with `-fopenmp` I get:
```
t1 = 0.021930013234183813
t2 = 0.02186594866604234
```
and without `-fopenmp`
```
t1 = 0.020138169933731357
t2 = 0.02148005299968645
```
