### ISSUE TITLE
write text files in pythran fails

### ISSUE THREAD

**Issue by mgirardis** [serge-sans-paille/pythran#1699]
In its manual page, [pythran says it supports the method `write` from `TextIOWrapper`][1]

However, trying to compile this simple file

file: `mylib.py`

    #pythran export write_test(str,bool)
    #pythran export fake_write(str)
    
    def write_test(fname,r):
        if r:
            print('writing %s'%fname)
            f = open(fname,'w')
            #write_line = f.writelines
            write_line = f.write
        else:
            print('NO FILE WILL BE WRITTEN')
            write_line = fake_write
        for i in range(10):
            write_line(str(i) + '\n')
        if r:
            f.close()
    
    def fake_write(s):
        return 0

with the command line

> pythran mylib.py -o mylib.so -O3 -march=native -v

fails with the message:

> mylib.py:9:21 error: Unsupported attribute 'write' for this object

Pythran version: `0.9.8.post2`

Python version: `3.8.5`

Using Ubuntu 20.04.1 LTS

  [1]: https://pythran.readthedocs.io/en/latest/SUPPORT.html#io

**Comment by serge-sans-paille** [comment]
Pythran indeed supports the `write` method from `TextIOWrapper`. There's a bug elsewhere, let me investigate, and thanks for reporting!

**Comment by serge-sans-paille** [comment]
Ok, two problems spotted. First pythran doesn't support bound methods as it should. Second pythran's `write` method doen't return an integer. I'll fix these two, until then, the following works:

```python
#pythran export write_test(str,bool)
#pythran export fake_write(str)

def write_test(fname,r):
    if r:
        print('writing %s'%fname)
        f = open(fname,'w')
        #write_line = f.writelines
        write_line = lambda s: f.write(s)
    else:
        print('NO FILE WILL BE WRITTEN')
        write_line = fake_write
    for i in range(10):
        write_line(str(i) + '\n')
    if r:
        f.close()

def fake_write(s):
    return None
```

**Comment by serge-sans-paille** [comment]
@mgirardis can you confirm https://github.com/serge-sans-paille/pythran/pull/1701 fixes your issue?

**Comment by mgirardis** [comment]
@serge-sans-paille I'm not the most savvy with github, here is what I've done:

Yesterday, after posting the issue, I had uninstalled the pythran 0.9.8.post2 and cloned this repository to try and see if the issue was still there... And the error persisted...

so now after you posted this fix, I did the following

> git pull

in the pythran clone directory I have in my local machine

then, I installed pythran (I did NOT uninstall the previous pythran)

> python setup.py install --user

and I still have the error with code I posted... The code you suggested works, though.

Maybe I need to do something different from what is here to fix the issue in my local copy?

**Comment by serge-sans-paille** [comment]
Almost there! The PR was based on branch `feature/support-bound-method` so you had to `git checkout feature/support-bound-method` first. The install step was correct.

**Comment by mgirardis** [comment]
Great! It worked now :) thanks! and keep up the good work!
