### ISSUE TITLE
Pythran twice as slow compared to native numpy when filling numpy array

### ISSUE THREAD

**Issue by rickbeeloo** [serge-sans-paille/pythran#1708]
<h2>Background</h2>
We have a function were we cannot use numba as `int()` is not supported yet. Hence we were excited to try pythran! :). This really sped up our code, however, when we perform NumPy operations, such as filling an array, native Numpy is significantly faster. This seems counterintuitive so I wonder whether we are missing something here.

---

<h2>Pythran much slower when we fill numpy arrays</h2>

For ease, I also created a google colab notebook [here](https://colab.research.google.com/drive/1oMf_kruQrVNFfAsWay4saJ7Y4ZdLEmDd?usp=sharing) where I put all the code. 
**Generate some testdata**

```
import random
random.seed(10)
np.random.seed(10)
def test_str():
    arr  = np.random.randint(10000, size=10000000)
    sign = np.random.choice(['+','-'], size=10000000)
    return ' '.join(["{}{}".format(a,b) for a,b in zip(arr, sign)])

```
**The native numpy function**
```
def test1(l):
  numbers = np.array([int(k[:-1]) for k in l.split(' ')])
  signs = np.array([(k[-1] == '+') for k in l.split(' ')]) * 2 - 1
  N = len(numbers)
  arr = np.empty(shape = (N, 3), dtype = np.int64)
  arr[:, 0] = numbers
  arr[:, 1] = signs
  arr[:, 2] = np.arange(N)
  return arr
```
**The Pythran function**

_Just the same function but with the pythran export :)_
```
%%pythran
#pythran export test2(str)
import numpy as np
def test2(l):
  numbers = np.array([int(k[:-1]) for k in l.split(' ')])
  signs = np.array([(k[-1] == '+') for k in l.split(' ')]) * 2 - 1
  N = len(numbers)
  arr = np.empty(shape = (N, 3), dtype = np.int64)
  arr[:, 0] = numbers
  arr[:, 1] = signs
  arr[:, 2] = np.arange(N)
  return arr
```
**TIMING**

```
ts = test_str()
%timeit test1(ts)
%timeit test2(ts)
1 loop, best of 3: 5.84 s per loop
1 loop, best of 3: 13.7 s per loop
```
<h2>Pythran is MUCH faster when we skip the array filling</h2>

```
def test3(l):
  numbers = np.array([int(k[:-1]) for k in l.split(' ')])
  signs = np.array([(k[-1] == '+') for k in l.split(' ')]) * 2 - 1
  N = len(numbers)
  arr = np.empty(shape = (N, 3), dtype = np.int64)
```
and:

```
%%pythran
#pythran export test4(str)
import numpy as np
def test4(l):
  numbers = np.array([int(k[:-1]) for k in l.split(' ')])
  signs = np.array([(k[-1] == '+') for k in l.split(' ')]) * 2 - 1
  N = len(numbers)
  arr = np.empty(shape = (N, 3), dtype = np.int64)

```
```
1 loop, best of 3: 6.01 s per loop
The slowest run took 6.42 times longer than the fastest. This could mean that an intermediate result is being cached.
100 loops, best of 3: 6.51 ms per loop
```

**Interestingly**, when we add a single fill to the end of the above functions, e.g. `arr[:,0] = numbers` Pythran will be slower again. Any idea why this occurs? are we missing something?

**Comment by jeanlaroche** [comment]
Keep in mind that pythran does lazy evaluation: when something isn't needed, it's just not computed. In your case, (test4) since signs are not used anywhere, they're not computed by pythran. I'm assuming you're also returning arr otherwise pythran will just skip everything! :)
If you add return(arr,signs), then you force signs to be computed. This way the only difference between test4 and test2 is the filling of arr.

**Comment by rickbeeloo** [comment]
@jeanlaroche thanks for the quick response! Indeed then we get:
```
1000 loops, best of 3: 516 µs per loop
1000 loops, best of 3: 867 µs per loop
```
So pythran is slower but it's not the array filling, so guess we cannot speed this up with pythran?

**Comment by jeanlaroche** [comment]
Also, you could use numpy.sign()... I'm not sure if I understand what you're doing, but I guess signs is supposed to contain +1 or -1 depending on the sign of numbers, correct?

**Comment by rickbeeloo** [comment]
@jeanlaroche  the `S=l.split(' ')` didn't do much, you're right regarding the signs however the numbers column should not contain them anymore. So `234+` should be `234` in numbers, and `+` in signs

**Comment by jeanlaroche** [comment]
Oh, I see, the signs are after the numbers. I missed that.

**Comment by paugier** [comment]
I confirm that it has nothing to do with the creation of the last array ("fill"), which seems fast with Pythran.

```python
import random
import numpy as np
from transonic import boost
from transonic.util import timeit_verbose as timeit

random.seed(10)
np.random.seed(10)

def make_str():
    arr = np.random.randint(10000, size=1000)
    sign = np.random.choice(["+", "-"], size=1000)
    return " ".join(["{}{}".format(a, b) for a, b in zip(arr, sign)])

def parse0(l: str):
    tmp = l.split(" ")
    numbers = np.array([int(k[:-1]) for k in tmp])
    signs = np.array([(k[-1] == "+") for k in tmp]) * 2 - 1
    N = len(numbers)
    arr = np.empty(shape=(N, 3), dtype=np.int64)
    arr[:, 0] = numbers
    arr[:, 1] = signs
    arr[:, 2] = np.arange(N)
    return arr

def parse_nofill(l: str):
    tmp = l.split(" ")
    numbers = np.array([int(k[:-1]) for k in tmp])
    signs = np.array([(k[-1] == "+") for k in tmp]) * 2 - 1
    return numbers, signs, np.arange(len(numbers))

parse0_pythran = boost(parse0)
parse_nofill_pythran = boost(parse_nofill)

ts = make_str()

glo = globals()

norm = timeit("parse0(ts)", globals=glo)
timeit("parse0_pythran(ts)", norm=norm, globals=glo)
timeit("parse_nofill(ts)", norm=norm, globals=glo)
timeit("parse_nofill_pythran(ts)", norm=norm, globals=glo)
```
gives
```
parse0                           :     1 * norm
norm = 0.000348 s
parse0_pythran                   :   1.4 * norm
parse_nofill                     : 0.989 * norm
parse_nofill_pythran             :   1.4 * norm
```

**Comment by serge-sans-paille** [comment]
Hi folks, and thanks @rickbeeloo for reporting. The problem lies in the support of string in pythran, which leaves a lot of room for optimization. I played with your code yesterday evening and managed to get a decent speedup, let me test the optimizations and release a bug fix!

**Comment by rickbeeloo** [comment]
Aaah so it was a problem with the string and not the array - sorry for that! 
@serge-sans-paille cool! Excited for that :)

**Comment by serge-sans-paille** [comment]
Can you confirm #1708 fixes your issue?

**Comment by rickbeeloo** [comment]
Can I install this using `pip install git+https://github.com/serge-sans-paille/pythran.git`? I installed it using that line and put the same test code in [this colab](https://colab.research.google.com/drive/11-OBagSHw0WdLE2w1KnS2lSiolhN1p4C?usp=sharing) but I don't see much difference, am I missing something?

**Comment by rickbeeloo** [comment]
@serge-sans-paille I commented a bit too quick so edited it now (just so you get the notification :) )

**Comment by paugier** [comment]
I think you can try the branch `feature/fast-str-chr` (PR https://github.com/serge-sans-paille/pythran/pull/1710).

For example like that: `pip install git+https://github.com/serge-sans-paille/pythran.git@feature/fast-str-chr`.

**Comment by paugier** [comment]
With master:
```
parse0                           :     1 * norm
norm = 0.000348 s
parse0_pythran                   :   1.4 * norm
parse_nofill                     : 0.989 * norm
parse_nofill_pythran             :   1.4 * norm
```

With `feature/fast-str-chr`
```
parse0                           :     1 * norm
norm = 0.000356 s
parse0_pythran                   : 0.301 * norm
parse_nofill                     : 0.986 * norm
parse_nofill_pythran             :  0.31 * norm
```
Pythran is no longer slower than CPython & Numpy!

**Comment by rickbeeloo** [comment]
Yesss same for me!
```
5.74 ms ± 12 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.07 ms ± 27.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
Amazing :) thanks!!
