### ISSUE TITLE
negative power of integer

### ISSUE THREAD

**Issue by jb-leger** [serge-sans-paille/pythran#1730]
In python, `int ** int` return a `int` when the exponent is positive, and a `float` when the exponent is negative. With pythran, it return 0 (as a integer) when the exponent is negative. This produces inconsistency between the python result and the pythran one.

Minimal example:
```python
#pythran export testfun(int, int)
def testfun(a, b):
    return a ** b
```

In the following, `test1` is python, `test2` is compiled with pythran:
```
In [1]: import test1
   ...: import test2

In [2]: test1.testfun(12, 5)
Out[2]: 248832

In [3]: test2.testfun(12, 5)
Out[3]: 248832

In [4]: test1.testfun(12, -5)
Out[4]: 4.018775720164609e-06

In [5]: test2.testfun(12, -5)
Out[5]: 0
```

_I found this behavior when I was studied why python function and pythran one did'nt give the same results for the discrepency computation for `L2-star` method in scipy/scipy#13576_

**Comment by serge-sans-paille** [comment]
mmmh, interesting and problematic behavior, as there's no way in native mode to use a different type based on a runtime value... if the exponent is known at compile-time we can match python behavior, but for runtime value, we can't... and the safest approah is to use float in that case, I guess?

**Comment by jb-leger** [comment]
Sometime exact computations are need, especially for large int. But in pythran, integer are int64, so we have a similar problem with integer overflow:

```
In [27]: test1.testfun(2,62)         
Out[27]: 4611686018427387904

In [28]: test2.testfun(2,62)         
Out[28]: 4611686018427387904

In [29]: test1.testfun(2,63)         
Out[29]: 9223372036854775808

In [30]: test2.testfun(2,63)         
Out[30]: -9223372036854775808
```

So, using floats seems a better solution imho.
