### ISSUE TITLE
Pythran uses %USERPROFILE%\ to locate .pythranrc on Windows

### ISSUE THREAD

**Issue by carlkl** [serge-sans-paille/pythran#1740]
Pythran uses `%USERPROFILE%` to locate `.pythranrc` on Windows instead of  `%HOME%\.pythranrc` as described in the documentation. This is due to the behaviour of `os.path.expanduser()` on Windows.
For use of pythran in the msys2 environment i.e. it would be better to use the `HOME` variable if exists and `USERPROFILE` (via `os.path.expanduser`) only in the case `HOME` is not defined.

**Comment by serge-sans-paille** [comment]
I have limited Windows knowledge: is `%HOME%` somehow standard on msys2 environment?

**Comment by carlkl** [comment]
With `MSYSTEM=MINGW64` or `MSYSTEM=MINGW32` one can detect the `msys2` environment. Within this environment  `HOME` is always defined.
