### ISSUE TITLE
unable to assign to slice of transposed array

### ISSUE THREAD

**Issue by treverhines** [serge-sans-paille/pythran#1763]
I believe I found another issue with transposed arrays. If I create an array, transpose it, and then assign to a slice of the array, I do not see the new values in the original array. The below code reproduces the issue:

```python
import numpy as np                                      
                                                        
# pythran export assign_to_slice()                      
def assign_to_slice():                                  
    # only an issue when size >= 16                     
    base = np.zeros((16, 16)).T                           
    base[:1, :1] = 1.0                                  
    print(base[0, 0]) # prints 0 instead of 1 
```

Side note: I am transposing the array after creating it because I would like it to be fortran contiguous (so that the array can be used with blas/lapack). Am I correct in assuming that transposing a matrix created by zeros/empty/ones/full will always be fortran contiguous? Would it be possible to add support for the "order" argument for the array creation functions?

Thank you so much for your help!

**Comment by serge-sans-paille** [comment]
Another transpose bug :-) looks like that code area wasn't tested enough, thanks for providing a btter coverage ;-)

`np.ones` and the like always create C contriguous memory in pythran (just like numpy). supporting the `order` parameter is non trivial (it's a runtime value that influences the type of the function output, pythran uses different type for Fortran and C layout). So your approach is a good alternative!

Note that pythran only supports Fortran layout for 2D numpy  vector :-/

**Comment by treverhines** [comment]
> np.ones and the like always create C contriguous memory in pythran (just like numpy). supporting the order parameter is non trivial (it's a runtime value that influences the type of the function output, pythran uses different type for Fortran and C layout). So your approach is a good alternative!

> Note that pythran only supports Fortran layout for 2D numpy vector :-/

That works for me. Thanks for explaining.
