### ISSUE TITLE
 ‘import_array’ was not declared in this scope

### ISSUE THREAD

**Issue by cagev** [serge-sans-paille/pythran#1781]
just add "np_pythran=True"  to a sample hello.pyx 

gcc complains : 

hello.cpp: In function ‘int __pyx_pymod_exec_hello(PyObject*)’:
hello.cpp:1955:7: error: ‘import_array’ was not declared in this scope
 1955 |   if (import_array() < 0) __PYX_ERR(0, 1, __pyx_L1_error)
      |       ^~~~~~~~~~~~
In file included from pythran/pythran/pythonic/include/operator_/add.hpp:5,
                 from pythran/pythran/pythonic/include/types/numpy_operators.hpp:5,
                 from pythran/pythran/pythonic/include/types/ndarray.hpp:972,
                 from pythran/pythran/pythonic/types/ndarray.hpp:4,
                 from pythran/pythran/pythonic/types/tuple.hpp:13,
                 from pythran/pythran/pythonic/builtins/bool_.hpp:7,
                 from pythran/pythran/pythonic/types/NoneType.hpp:8,
                 from pythran/pythran/pythonic/types/slice.hpp:5,
                 from pythran/pythran/pythonic/core.hpp:29,
                 from hello.cpp:643:

**Comment by serge-sans-paille** [comment]
`import_array` should come with `numpy.h` . I *guess* you should `cimport numpy` ?

**Comment by cagev** [comment]
works, thanks.
