### ISSUE TITLE
error: 'malloc' was not declared in this scope

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1796]
Strange, isn't it ?

```
    fluidfft/fft2d/__pythran__/operators.cpp:792:163:   required from here
    /home/augier3pi/Dev/pythran/pythran/pythonic/types/raw_array.hpp:22:25: error: 'malloc' was not declared in this scope
       22 |       : data((T *)malloc(n * sizeof(T))), external(false)
          |                   ~~~~~~^~~~~~~~~~~~~~~
    /home/augier3pi/Dev/pythran/pythran/pythonic/types/raw_array.hpp:1:1: note: 'malloc' is defined in header '<cstdlib>'; did you forget to '#include <cstdlib>'?
      +++ |+#include <cstdlib>
```

Context: I'm trying a strange install procedure of fluidfft mixing libs from conda, from the system and from modules. But I don't know what to do with this error coming from Pythran.

**Comment by serge-sans-paille** [comment]
>     fluidfft/fft2d/__pythran__/operators.cpp:792:163:   required from here
>     /home/augier3pi/Dev/pythran/pythran/pythonic/types/raw_array.hpp:22:25: error: 'malloc' was not declared in this scope
>        22 |       : data((T *)malloc(n * sizeof(T))), external(false)
>           |                   ~~~~~~^~~~~~~~~~~~~~~
>     /home/augier3pi/Dev/pythran/pythran/pythonic/types/raw_array.hpp:1:1: note: 'malloc' is defined in header '<cstdlib>'; did you forget to '#include <cstdlib>'?
>       +++ |+#include <cstdlib>

The fix is correct, can you submit it?
