### ISSUE TITLE
argmin causes segfault

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#1797]
Hi I'm encountering a segmentation fault when using 0.9.11 using both llvm and gcc on linux.

Pythran code:
```python
import numpy as np
#pythran export make_decision_pt3(complex128[], complex128[])
def make_decision_pt3(signal, alphabet):
    out = np.zeros_like(signal)
    d = np.abs(signal[None,:]-alphabet[:, None])
    idx = np.argmin(d, axis=0)
    return idx
```

calling with:

```python
x=np.random.randn(5)+1j*np.random.randn(5)
y=np.random.choice(x, 10**5)
make_decision_pt3(y,x)
```
Crashes reproducably. If I remove the `idx = np.argmin(d, axis=0)` line from the make_decision function everything is working fine.

**Comment by serge-sans-paille** [comment]
I can reproduce the issue, thanks for submitting a clean reproducer!
