### ISSUE TITLE
Frightening error message even when everything is fine

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#1798]
During Pythran execution, one can get this message

```
/tmp/tmppilay8qq/source.c:1:10: fatal error: cblas.h: No such file or directory
    1 | #include <cblas.h>
      |          ^~~~~~~~~
compilation terminated.
```

This is just an output problem because the actual compilation is fine. However, users can be afraid. When everything is fine, it's not too bad. But when there is actually another error, it's bad because people tend to focus on `cblas.h`.

Would it be possible to hide this error log ?

**Comment by serge-sans-paille** [comment]
can you share your .pythranrc, the .py and list the installed blas deps so that
I can reproduce?

Thanks!

**Comment by paugier** [comment]
Empty .pythranrc

.py with just

```
# pythran export toto
toto = 1
```

Pythran installed with:

```
conda create -n env_pythran pythran networkx=2.5.1
conda activate env_pythran
```

If I install pythran from source in this conda environment, I also get the error log.

**Comment by serge-sans-paille** [comment]
@paugier I failed to reproduce locally, but does #1799 fixes your issue? maybe with changing `redirect_stdout` into `redirect_stderr` ?

**Comment by paugier** [comment]
Nop, it does not suppress the message and gives a error in `numpy.distutils.system_info`!

I can get the message just with:
```
import numpy.distutils.system_info as numpy_sys
numpy_sys.get_info("blas")
```

But I can't find a way to redirect it. I guess this message does not go through `sys.stdout` or `sys.stderr`.

**Comment by serge-sans-paille** [comment]
I submitted a lower level approach in #1799, I think it works as expected :-)

**Comment by paugier** [comment]
I confirm that here the message is correctly suppressed by `silent`. Thanks!
