### ISSUE TITLE
keep_dims is not supported in np.mean()

### ISSUE THREAD

**Issue by charlotte12l** [serge-sans-paille/pythran#1820]

**Comment by rgommers** [comment]
Thanks @charlotte12l. Xref previous issue on this: gh-1564. As we discussed on Monday, this is a structural issue related to boolean keywords which change return type or the dimensionality of the returned ndarray. I made a suggestion in gh-1842 for how to resolve this.

**Comment by serge-sans-paille** [comment]
Should be fixed once #1869 gets merged.
