### ISSUE TITLE
The dependencies of pythran are very confusing.

### ISSUE THREAD

**Issue by whenyd** [serge-sans-paille/pythran#1837]
When I compile scipy 1.7.0, an error occured that says "ModuleNotFoundError: No module named 'pythran'". Then I execute `pip install pythran`, something confusing happened.

**17 packages been installed**:

`pythran decorator beniget ply networkx gast six numpy pandas scipy matplotlib python-dateutil pytz cycler kiwisolver pillow pyparsing`

Even the scipy is in the list, and other scientific packages include `numpy pandas matplotlib pillow`.

First, is it a cyclic dependency for scipy?
Second, pythran is just a compiler to efficiently compile scientific programs, why these packages are installed as its dependencies.

environment:
Python: 3.9.2
Pip: 21.1.3
numpy: 1.20.1
Cython: 0.29.21
pybind11: 2.6.2

**Comment by rgommers** [comment]
Yes it is a cycle, this is due to `networkx` 2.6.0 which was released yesterday. That added numpy, scipy, matplotlib, pandas. We're trying to fix the issue. If you use `--no-build-isolation` with `pip` and install `networkx==2.5.1`, that should work around the problem you are seeing.

**Comment by whenyd** [comment]
yes, it works, thank you

**Comment by serge-sans-paille** [comment]
#1839 should fix this mess: no more deps on networkx, six or decorator. the only remaining dependencies are:

- gast (I maintain that one, no extra requirement on that one)
- beniget (I maintain that one, it only depends on gast)
- numpy (this is a hard dep)
- scipy (optional)

**Comment by jarrodmillman** [comment]
I just yanked 2.6 and 2.6.1 from PyPI until we resolve networkx/networkx#4967.

**Comment by serge-sans-paille** [comment]
Fixed by #1839
