### ISSUE TITLE
Incorrect code generated for simple loop

### ISSUE THREAD

**Issue by fuglede** [serge-sans-paille/pythran#1861]
This is my first real excursion into Pythran-land, so please bear with me if I'm asking something silly.

Consider the below example in which we answer "What's the lowest input for the [Collatz conjecture](https://en.wikipedia.org/wiki/Collatz_conjecture) whose sequence has a given target length"; the implementation is completely naive, but this plays a role as the issue at hand depends on the minor details:

```python
#pythran export collatz(int)
def collatz(target):
    start = 1
    while True:
        i = start
        steps = 0
        while True:
            steps += 1
            if i == 1:
                break
            if i % 2 == 0:
                i = i // 2
            else:
                i = 3 * i + 1
        if steps == target:
            return start
        start += 1
```

Works like a charm. Suppose we now decide to shift `target` by one. The simplest way to do that is to move the inner loop counter to the end of the loop; i.e. just move `steps += 1` down a bit:

```python
#pythran export collatz(int)
def collatz(target):
    start = 1
    while True:
        i = start
        steps = 0
        while True:
            if i == 1:
                break
            if i % 2 == 0:
                i = i // 2
            else:
                i = 3 * i + 1
            steps += 1
        if steps == target:
            return start
        start += 1
```

The Python function still works as expected, but the Pythran-generated (Pythran 0.9.12.post1) version never halts.

I didn't dig into exactly why this is happening, but perhaps a diff between the code generated by those two cases is helpful:

```diff
$ diff collatzpythran_first.cpp collatzpythran_second.cpp
69d68
<         steps += 1L;
83a83
>           steps += 1L;
86c86
<       if (pythonic::operator_::eq(steps, target))
---
>       if (pythonic::operator_::eq(0L, target))
```

In particular, the `eq(0L, target)` smells.

Is this a Pythran bug or am I doing something I shouldn't be doing?

Curiously, something very similar happened to me with Numba: https://github.com/numba/numba/issues/5273

**Comment by serge-sans-paille** [comment]
Looks like a defect in the range analysis. I'll have a look, thanks for digging into it!

**Comment by serge-sans-paille** [comment]
Can you confirm #1861 fixes your issue?

**Comment by fuglede** [comment]
Indeed it does:

```
$ cat testpythran.py
#pythran export collatz(int)
def collatz(target):
    start = 1
    while True:
        i = start
        steps = 0
        while True:
            if i == 1:
                break
            if i % 2 == 0:
                i = i // 2
            else:
                i = 3 * i + 1
            steps += 1
        if steps == target:
            return start
        start += 1

$ pythran testpythran.py

$ python -c 'import testpythran; print(testpythran.collatz(10))'
24
```
