### ISSUE TITLE
Remove outdated use of setup_requires=pytest-runner

### ISSUE THREAD

**Issue by mkoeppe** [serge-sans-paille/pythran#1871]
As per https://pypi.org/project/pytest-runner/:
pytest-runner depends on deprecated features of setuptools and relies on features that break security mechanisms in pip. [...] It is recommended that you:
Remove 'pytest-runner' from your setup_requires, preferably removing the setup_requires option.[...]

**Comment by serge-sans-paille** [comment]
Sure, can you propose a patch for that?

**Comment by mkoeppe** [comment]
Thanks a lot!
