### ISSUE TITLE
"Function that modifies its Dict argument..." on non-modifying function

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#1906]
Iterating over a dictionary values or keys triggers a warning:

`WARNING: Exporting function 'f' that modifies its Dict argument. Beware that this argument won't be modified at Python call site`

Iterating over the keys directly doesn't.

```
#pythran export f(str: int  dict)
def f(xx):
    total = 0
    for x in xx.values():
        total += x
    return total

#pythran export f2(str: int  dict)
def f2(xx):
    return sum(x for x in xx.values())

#pythran export f3(str: int  dict)
def f3(xx):
    return sum(len(x) for x in xx.keys())
```

This works without a warning, but it is equivalent to `f3`
```
#pythran export f4(str: int  dict)
def f4(xx):
    return sum(len(x) for x in xx)
```

I have tested with Pythran release and master. All the functions generated seem to be correct, though.

**Comment by serge-sans-paille** [comment]
Thanks for reporting! #1907 should do the trick.
