### ISSUE TITLE
Make the potential `int` size pitfall more prominent

### ISSUE THREAD

**Issue by adeak** [serge-sans-paille/pythran#1916]
I was perusing the docs when [I found among the Limitations](https://pythran.readthedocs.io/en/latest/MANUAL.html#limitations)
> There is no BigInt support. All integer operations are performed on long (probably int64_t on a 64 bit machine.)

If this is indeed the case, there's [an infamous pitfall that NumPy has to deal with](https://github.com/numpy/numpy/issues/9464), namely that a C `long` on 64-bit Windows is 32-bit. This causes terrible surprises, for instance `np.arange` giving you int32 values even on 64-bit Windows.

If the note about `long` is still true, perhaps a more prominent warning should be put next to that bullet point, raising awareness of this underlying issue (i.e. that you get 32-bit ints on a 64-bit system). I have a Windows virtual machine somewhere, I can also experiment myself to check if the behaviour is indeed the same.

Probably related issue: https://github.com/serge-sans-paille/pythran/issues/1811

**Comment by serge-sans-paille** [comment]
Thanks for raising that point. Maybe it would be better to use uint64_t everywhere instead?

**Comment by adeak** [comment]
Well, maybe not _unsigned_ :) I'm a linux user _and_ a 64-bit user, so I'm not a reliable source in the matter. I guess the least surprising behaviour would be to match the word size(?) of the OS, but I also suspect that's more difficult than it sounds.

Since the issue is hopefully fairly well known in numpy, it's probably also manageable to just point this out in the docs (as a worst case).

**Comment by serge-sans-paille** [comment]
Yeah, definitively not signed :-). On windows, what's the output of

```python
import numpy as np
print(np.int_ is np.int64)
print(np.int_ is np.int32)
```

?

**Comment by adeak** [comment]
```py
(tmp_test_env_3.9) C:\Users\lou>python
Python 3.9.8 (tags/v3.9.8:bb3fdcf, Nov  5 2021, 20:48:33) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print(np.int_ is np.int64)
False
>>> print(np.int_ is np.int32)
True
```

Virtual windows 10 running on qemu on a debian host:
```
Device name	DESKTOP-[...]
Processor	Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz   1.80 GHz
Installed RAM	4.00 GB
Device ID	[...]
Product ID	[...]
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```
