### ISSUE TITLE
pythran compilation takes longer than a minute on "for i in range(1000000):"

### ISSUE THREAD

**Issue by certik** [serge-sans-paille/pythran#1929]
If I try this:
```
def myf(a, b):
    c = 0
    for i in range(1000000):
        c = (c + a)*b
    return c

def main():
    print(myf(3, 4))
```
then pythran compilation takes forever, I killed it after about a minute and a half:
```
$ pythran b.py 
WARNING:root:No pythran specification, nothing will be exported
```

For smaller values of the range, the generated C++ code contains hundreds of lines like:
```c++
      typedef decltype(pythonic::operator_::mul(std::declval<__type262>(), std::declval<__type3>())) __type264;
      typedef decltype(pythonic::operator_::add(std::declval<__type264>(), std::declval<__type1>())) __type266;
      typedef decltype(pythonic::operator_::mul(std::declval<__type266>(), std::declval<__type3>())) __type268;
      typedef decltype(pythonic::operator_::add(std::declval<__type268>(), std::declval<__type1>())) __type270;
      typedef decltype(pythonic::operator_::mul(std::declval<__type270>(), std::declval<__type3>())) __type272;
      typedef decltype(pythonic::operator_::add(std::declval<__type272>(), std::declval<__type1>())) __type274;
...
pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(pythonic::operator_::add(pythonic::operator_::mul(...
```
So it seems it is unrolling the loop. That would explain why it takes forever.

**Comment by serge-sans-paille** [comment]
I thought there was a limit to what unroll can do... I'm checking that

**Comment by serge-sans-paille** [comment]
Actually got it, it's a funny one: `myf` is a pure function, and pythran understands it. It's called with constant arguments, so pythran actually evaluates `myf` (using python `eval`) so it takes as long as `myf` takes to execute. :-)

**Comment by serge-sans-paille** [comment]
I'm not sure about the right way to improve the situation though. Setting a timeout is going to raise tons of portability issue, putting a warning whenever I evealuate a constant function may be too verbose...

**Comment by certik** [comment]
It seems that constant function should not be evaluated at compile time, unless you know that the loop has less than N iterations and each iteration is not long. N can be something like 20.

**Comment by serge-sans-paille** [comment]
Unfortunately, predicting the complexity of a function is difficult (because of while loops and recursion). What I could try would be to implement some kind of python evaluator with a limit on number of instructions...

@vstinner I wonder how difficult it would be to implement *`eval` with timeout*?

**Comment by vstinner** [comment]
> @vstinner I wonder how difficult it would be to implement eval with timeout?

On Unix, you can use ``signal.alarm()`` to raise ``SIGALRM`` in N seconds, or ``signal.setitimer()`` which supports sub-second resolution.

When I wrote a sandbox, I ended with using a subprocess. It's the only reliable and portable way to "kill" a function/program if it takes longer than N seconds.

See also the https://en.wikipedia.org/wiki/Halting_problem ;-)

**Comment by certik** [comment]
I am pretty sure you can determine if a given function only has a loop up to N, and does not call any other function and thus ends quickly. Then you can extend this logic if it calls other functions, as long as there is no mutual recursion and all called functions also end quickly (or you just inline them first and then run the analysis).

For every other case you do not call the function at compile time.

**Comment by vstinner** [comment]
The Linux kernel has an interesting problem with bounding the maximum execution time of a BPF program:
"A different approach to BPF loops"
https://lwn.net/Articles/877062/
