### ISSUE TITLE
Bug in slicing and assinging lists

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#1935]
The following function returns `[16807, 32768, 59049]` but `[-1, -1, 59049]` when compiled with Pythran.
```
def f():
    past = [-1, -1, -1]
    for i in range(10):
        past[:2] = past[1:]
        past[2] = i ** 5
    return past
```
Assigning to a temporary variable is not enough.
```
def f_2():
    past = [-1, -1, -1]
    for i in range(10):
        tmp = past[1:]
        past[:2] = tmp
        past[2] = i ** 5
    return past
```
In fact, `pythran -P` reduces it to the same as above.

Using tmp, on the other hand, solves the issue:
```
def f_3():
    past = [-1, -1, -1]
    for i in range(10):
        tmp = past[1:]
        print(tmp)
        past[:2] = tmp
        past[2] = i ** 5
    return past
```

In this case, Pythran knows the number of iterations at compile time, so it unrolls the loop. Here it isn't known, but the problem persists:

```
def g():
    past = [-1, -1, -1]
    i = 0
    while sum(past) < 1000:
        past[:2] = past[1:]
        past[2] = i ** 5
        i += 1
    return past
```
The earlier trick now works, going through the temporary variable works, and Pythran doesn't gobble it up:
```
def g_2():
    past = [-1, -1, -1]
    i = 0
    while sum(past) < 1000:
        tmp = past[1:]
        past[:2] = tmp
        past[2] = i ** 5
        i += 1
    return past
```

I am using Python 3.9 on Linux, GCC 11.2.1, and Pythran master and 0.11.

**Comment by serge-sans-paille** [comment]
Thanks @Dapid for the consistent error reports you're sharing here :-) I can reproduce and reduce that to the following
```
#pythran export f()
def f():
    past = [-1, -1, -1]
    past[2] = 0
    past[:2] = past[1:]
    past[2] = 1
    return past
```

I'm on it!
