### ISSUE TITLE
Pythran regression post 0.9.0

### ISSUE THREAD

**Issue by DerWeh** [serge-sans-paille/pythran#1940]
I have some code, which doesn't compile with new versions of Pythran anymore.
The code is (generated using transonic, `.txt` ending because GitHub doesn't allow code)
[exactdiag.pythran.txt](https://github.com/serge-sans-paille/pythran/files/7653711/exactdiag.pythran.txt)
[exactdiag.py.txt](https://github.com/serge-sans-paille/pythran/files/7653712/exactdiag.py.txt)

Using the following old version, my code compiles without a problem
```
beniget==0.3.0
gast==0.4.0
pythran==0.9.9
```

However, with the recent version
```
beniget==0.4.1
gast==0.5.3
pythran==0.10.0
```
I get the following error:
```
WARNING: Compilation error, trying hard to find its origin...
CRITICAL: I am in trouble. Your input file does not seem to match Pythran's constraints...
exactdiag.py:None:None error: Specification for `annihilation_0up_matvec` does not match inferred type:
expected `Callable[[Sized, Sized, Iterable[Iterable[T0]], List[Array[0 d+, T1]], float], none]`
got `Callable[[Array[1d, float], Array[1d, float], Array[1d, int], Array[1d, int], int], ...]`
```

**Comment by serge-sans-paille** [comment]
Your code compiles just nice on current master (5d48856f39a2dc0b07aacc6308666f107cad5097)

Can you confirm?

**Comment by DerWeh** [comment]
Thanks for the fast response.

I tried using `pip install https://github.com/serge-sans-paille/pythran/archive/5d48856.zip`
Giving: `Successfully installed beniget-0.4.1 gast-0.5.3 pythran-0.11.0.dev0`.

However, I still get the same error. But, it seems, that this might depend on the Python version.
I currently use `Python 3.9.7`. I still have an old Python environment lying around `Python 3.7.3`,
installing `pythran-0.11.0.dev0` on that environment compiles the code.

**Comment by serge-sans-paille** [comment]
Tested with 3.10: no issue, I'll check with 3.9... meanwhile can you share the output of compilation with `pythran -v exactdiag.py` ?

**Comment by serge-sans-paille** [comment]
tested with 3.9, no issue either :-)

**Comment by DerWeh** [comment]
Sorry, I thought that I included the command I used to compile:

I used `pythran  -march=native -DUSE_XSIMD -Ofast --config compiler.blas=pythran-openblas exactdiag.py`.
But now I cannot reproduce the error anymore, I am very sorry for wasting your time.

Using however
`pythran -v exactdiag.py` 
gives the error, this is the [log](https://github.com/serge-sans-paille/pythran/files/7660237/log.txt).
The issue seem to be that BLAS is not found.

`pythran -v --config compiler.blas=mkl exactdiag.py` gives the same error 
[log_mkl](https://github.com/serge-sans-paille/pythran/files/7660238/log_mkl.txt),
apparently, MKL has to be linked explicitly.

I'll try to figure out what was previously different using `compiler.blas=pythran-openblas`, but I am not sure if I can reconstruct what let to the issue.

**Comment by serge-sans-paille** [comment]
Thanks for sharing the log error. I see there a `-DPYTHRAN_BLAS_BLAS` while you specified `-config compiler.blas=pythran-openblas`. That's unexpected, this config flag should imply `-DPYTHRAN_BLAS_OPENBLAS`. Can you log (through a debugger or some print statements) the path taken by the application in `pythran/config.py` around  line 230 (near the `# blas dependency` comment when running the above command? I'm interested in knowing if `import pythran_openblas as openblas` fails or not.

**Comment by DerWeh** [comment]
It seems to correctly detect `pythran_openblas` now. After installing it, it can be imported. After uninstalling it, a warning is given telling that it defaults to `blas`.

Using `pythran_openblas` correctly compiles, using `pythran -v exactdiag.py` fails with the warning I gave.

**Comment by serge-sans-paille** [comment]
looks like the bug can be considered fixed, right?

**Comment by DerWeh** [comment]
Yes, seems fine. Thank you for your time.
