### ISSUE TITLE
Error when using with sparse matrix format (reshape and intc)

### ISSUE THREAD

**Issue by mzy2240** [serge-sans-paille/pythran#1955]
I have a numba script which takes sparse matrix as input (using data, indices and indptr three numpy array) and I am currently working on moving the script to pythran. The compilation went smooth, however when I tried to call the function the following error occurs:
![image](https://user-images.githubusercontent.com/18620336/150297545-e0200d03-f21c-4bcb-997c-5f377f6ae4cb.png)
The line of code: (Ybus is a scipy sparse matrix, you can reproduce using any random scipy sparse matrix)
```python
dS_dVm, dS_dVa = dSbus_dV_numba_sparse(Ybus.data, Ybus.indptr, Ybus.indices, V, V / abs(V), I)
```
Since performance is the major concern, besides copy, is there any good solution to address this reshape error?
And what is `intc`? What type should I use to annotate a numpy int array?

Thank you in advance!

**Comment by serge-sans-paille** [comment]
intc is a data type that's different from `int` (it maps to  `numpy.intc`) that lookos like the reason for the type mismatch. If that change is not enough, I'd be happy to have a look at your code (I need the calling code and the pythran kernel)

**Comment by serge-sans-paille** [comment]
@mzy2240 did you try the approach suggested above?

**Comment by mzy2240** [comment]
Sorry for the late reply. Yes it solves the issue. Thanks!!
