### ISSUE TITLE
Windows 10 clang-cl builds: COMMAND LINE OPTIONS IGNORED - no OpenMP or optimizations are possible

### ISSUE THREAD

**Issue by mattslezak-shell** [serge-sans-paille/pythran#1964]
Setup: Windows 10, NumPy 1.21.5 w/ OpenBLAS, Pythran 0.11.0, Clang version 12 (part of MSVC 2019 build tools), Python 3.10.2.  Issue: example function does not work with OpenMP on Windows.  In fact when generating the cpp file with: pythran -e arc_distance.py and: pythran -e DUSE_XSIMD -fopenmp -march=native arc_distance.py the cpp files are EXACTLY the same.  Although I think the compiler tweaks happen after the cpp file is created, still I included both files here.

When I compile the example "arc_distance.py" and pass it: pythran -v -DUSE_XSIMD -fopenmp -march=native arc_distance.py there is no change in the output PYD file, so OpenMP is not working.  Since clang-cl.exe expects MSVC like arguments, Clang arguments are supposed to be passed like this: -Xclang -fopenmp ... and any other Clang-style arguments after the -Xclang statement.  I'm pretty sure that's the issue, as I put all the openmp .lib and .dll files in the same directory with no change...  The other strange thing I noticed is link.exe is used instead of the LLVM linker, but the module still works.  I uploaded the build log as well.  Quick summary of what a pythran -v shows: clang-cl.exe [PYTRAN OPTIONS] [INCLUDES] [OUTPUT] -fopenmp -march=native

I think it should look like: clang-cl.exe [PYTRAN OPTIONS] [INCLUDES] [OUTPUT] -Xclang -fopenmp -march=native

Now I can go in and change the ../Anaconda3/envs/openblas/Lib/site-packages/pythran/pythran-win32.cfg and add the items to the end of the cflags statment: cflags=/std:c++14 /w -Xclang -fopenmp -march=native 

This shows the flags passed to the compiler properly... but when I run the compiled PYD, there isn't any sign of OpenMP being used, as the speed is the same, processor % allocation is the same in the task manager.  Is this just a case of the documentation showing an OpenMP accelerated routine that actually doesn't benefit at all from using OpenMP???  Then please correct it and give an actual example that does.

It's pretty easy to replicate just take the example .py file:

    #pythran export arc_distance(float[], float[], float[], float[])
    import numpy as np
    def arc_distance(theta_1, phi_1, theta_2, phi_2):
        """
        Calculates the pairwise arc distance
        between all points in vector a and b.
        """
        temp = (np.sin((theta_2-theta_1)/2)**2
               + np.cos(theta_1)*np.cos(theta_2) * np.sin((phi_2-phi_1)/2)**2)
        distance_matrix = 2 * np.arctan2(np.sqrt(temp), np.sqrt(1-temp))
        return distance_matrix

Then on a Windows machine run the compile statement:  pythran -v -DUSE_XSIMD -fopenmp -march=native arc_distance.py

Run it complied with no -fopenmp and with it on a Windows 10 machine, and you will see the code runs the same speed, so no parallel operations are actually occurring.  This can also be inferred from the -v flag when compiling that the string flag to the clang-cl.exe compiler does not look correct.  I also confirmed in this environment I can build OpenMP Cython modules that utilize all cores without any issues.

    from arc_distance import arc_distance
    import numpy as np
    import timeit
    a=np.random.randint(100,size=(20000000))*0.1
    b=np.random.randint(100,size=(20000000))*0.1
    c=np.random.randint(100,size=(20000000))*0.1
    d=np.random.randint(100,size=(20000000))*0.1
    %timeit arc_distance(a, b, c, d)

Logs and source files: [pythran_test.zip](https://github.com/serge-sans-paille/pythran/files/8097804/pythran_test.zip)

**Comment by cycomanic** [comment]
I think I ran into the same issue some time ago. There are 2 solutions IIRC you can setup clang-cl to use the clang linker (I managed to do that at some point, but I don't recall how, I don't really use windows just compile on it some times). The other option is to set the linker and compile flags separately. 

If you use setuptools you can use something like this:
```python
from pythran.dist import PythranExtension

pythran_module = PythranExtension(name="your_module", sources["your_module.py"],  
    extra_compile_args=COMPILE_ARGS_IN_CLANG_FORMAT,
    extra_link_args=LINKER_ARGS_IN_CL_FORMAT)
```
Using the `pythran` commandline client use `pythran -L LINKER_FLAGS` IIRC. You can also set the different settings in `pythranrc` so for openmp you should have:
```
ldflags=\openmp 
```
in your `pythranrc`.

**Comment by mattslezak-shell** [comment]
Unfortunately adding the `pythran -L \openmp` doesn't seem to do anything (at least there is no speed increase vs. no OpenMP).  Editing the pythran.rc (on Windows `pythran-win32.cfg`) with the `ldflags=\openmp` just comes back with an error: LINK : fatal error LNK1181: cannot open input file 'openmp.obj' which basically happens whatever `\lib` I put there - unless I explicitly state a lib like libiomp5md.lib or libomp.lib, but still, no OpenMP parallel operation occurring.  

As for changing the linker over to the LLVM `lld-link.exe` I was able to hack that by modifying [Python]\Lib\site-packages\setuptools\_distutils\_msvccompiler.py and replacing `link.exe` with `lld-link.exe` and then commenting out ldflags: `'/LTCG'` as that's not an option understood by the LLVM linker (and so it will throw an error).  Still after all the imaginable hacks here, after a couple hours, there is no parallel operation.  

I'm starting to wonder - do others following the example for arc_distance.py actually see an OpenMP speedup as the documentation shows?  I'm pretty sure I saw an online example doing that same one with OpenMP on Linux or OSX and it was certainly faster.  Although all the things I've tried to get this working have failed, I just want to ensure that the example itself is not the problem....

**Comment by serge-sans-paille** [comment]
@mattslezak-shell Thanks for reporting, and sorry for the slight delay.

At some point, I decided that implicit parallelization was not the right approach, esp; as profitability depends on whether you're already in a parallel section, if the array size is large enough, and other parameters. 

So basically, **no** implicit parallelization ever happen.

You can still do explicit parallelization, through:

```
#pythran export arc_distance(float[], float[], float[], float[])
import numpy as np
def arc_distance(theta_1, phi_1, theta_2, phi_2):
    """
    Calculates the pairwise arc distance
    between all points in vector a and b.
    """
    size = theta_1.size
    distance_matrix = np.empty_like(theta_1)
    #omp parallel for
    for i in range(size):
        temp = (np.sin((theta_2[i]-theta_1[i])/2)**2 + np.cos(theta_1[i])*np.cos(theta_2[i]) * np.sin((phi_2[i]-phi_1[i])/2)**2)
        distance_matrix[i] = 2 * np.arctan2(np.sqrt(temp), np.sqrt(1-temp))
    return distance_matrix

```

yields the expected speedup on my machine

**Comment by mrslezak** [comment]
Thanks so much @serge-sans-paille I was losing my mind on that example, seems the documentation is in need of a refresh.  Not by a PC now but I'll try out that example as soon as I am.  I noticed the docs example didn't explicitly call OpenMP pragmas and was thinking that was probably the issue, thanks for providing another example that should work.

**Comment by mattslezak-shell** [comment]
@serge-sans-paille do you have a sample setup file (for Windows) or command line build string you pass to get OpenMP working for the new example you posted?  I spent another few hours trying to change parameters passed to clang-cl, the linker, switched between link.exe and lld-link.exe, and still have not been successful getting any speed up with OpenMP (which tells me it's being ignored).  Things like -fopenmp=libomp or -fopenmp=libiomp5md or just -fopenmp don't remedy it.  Adding the files to ldflags:\libomp.lib or \libiomp5md don't help either.  I have to believe someone has a working configuration for Windows out there... Appreciate your time.

**Comment by mattslezak-shell** [comment]
So after getting OpenBLAS working on Windows 10, I decided to get MKL working too.  There are some interesting, unexplainable differences, but this setup works.  Since Anaconda3 comes with MKL backed NumPy / SciPy / etc. it's already installed with the distribution on Windows.  So no need to download the `pythran-openblas` package.

In pythran-win32.cfg:
include_dirs='C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\Llvm\x64\lib', 'C:\Users\[username]\Anaconda3\Library\include'
cflags=/std:c++14 /w -Xclang -fopenmp
ldflags=\libomp.lib
blas=mkl

Why you need to use `libomp.lib` instead of `libiomp5md.lib` I don't know, but it works.  Since no one documented using MKL, this setup just works on a system with `clang-cl` installed from Visual Studio 2019 Build Tools, with Anaconda3 installed.  Probably a good time to update the documentation for Windows users with the setups above, at least for the next release of Pythran.  It could save a lot of users the headache of figuring these things out by trial and error.

**Comment by serge-sans-paille** [comment]
@mattslezak-shell Thanks for going that far. I don't have a windows machine to reproduce / test, but I'd gladly accept a PR from you to update the documentation on the windows part; Would you mind doing so?

**Comment by mattslezak-shell** [comment]
Sure when I get a chance I'll update the documentation with a PR.  The MKL bit gets a bit tricky since the "cblas.h" presents itself when including functions like np.dot, so the "hack" is a dummy `cblas.h` file that just does a `#include "mkl_cblas.h"` with a compiler argument -I"location_of_MKL_includes" along with an MKL download from here: https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl.html for the headers.  The setup I've come up with for MKL and OpenBLAS on Windows 10 will cover most simple functions - I do have a complex 100 line function I've been trying to compile that fails on both, but it's quite an odd one, I'd say that's another issue altogether.
