### ISSUE TITLE
Argsort does not support axis

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#2014]
I have managed to minimise the code that triggers #2013 in isolation. It is due to argsort being passed the axis argument.

```
import numpy as np

# pythran export c3(float64[:])
def c3(data: np.ndarray):
    all_indexes = data.argsort(axis=0)
    return all_indexes
```

The issue also happens when `data` is 2D, for all valid values of the `axis` argument, and regardless of wether I use the array method or the numpy function.

**Comment by serge-sans-paille** [comment]
Can you confirm 1a517ac2048eb85c3ca6e4cea4927066f0a7734b fixed that issue?

**Comment by Dapid** [comment]
It does, thanks.
