### ISSUE TITLE
xsimd makes broadcasting function much slower

### ISSUE THREAD

**Issue by jzluo** [serge-sans-paille/pythran#2016]
Hi, I'm running into a strange slowdown for this function if using xsimd that makes it 3x slower than numpy. This is with Pythran 0.11.0
```python
import numpy as np
from pythran_ex import get_XW_pythran
from pythran_ex_simd import get_XW_pythran_simd

def get_XW(X, preds):
    rootW = np.sqrt(preds * (1 - preds))
    XW = rootW[:, np.newaxis] * X
    return XW

np.random.seed(0)
X = np.random.rand(20000,20)
preds = np.random.random(20000)

%timeit get_XW(X, preds)
%timeit get_XW_pythran(X, preds)
%timeit get_XW_pythran_simd(X, preds)
```
```
228 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
91.7 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
776 µs ± 265 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```
For the pythranised functions I did:
```
pythran -O3 -march=native pythran_ex.py 
pythran -O3 -march=native -DUSE_XSIMD pythran_ex_simd.py
```

**Comment by jzluo** [comment]
Oh I just saw #1952, is that the cause?

**Comment by serge-sans-paille** [comment]
Do you have the issue with the master branch?

**Comment by jzluo** [comment]
Actually, both are worse on master... I did a git bisect to see where the regression for the non-SIMD version happens and the bad commit is 6266d5ac3c8ee732c4a2561b4e5703473c3ba34a.

Timing below are in order of:
Numpy
-O3 -march=native
-O3 -march=native -DUSE_XSIMD

```python
master
241 µs ± 4.71 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
422 µs ± 2.06 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
504 µs ± 1.38 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

[6266d5ac3c8ee732c4a2561b4e5703473c3ba34a] Reactivate xsimd fast path
233 µs ± 3.74 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
423 µs ± 2.55 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
203 µs ± 350 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

0.11.0 from pypi
236 µs ± 1.52 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
111 µs ± 572 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
776 µs ± 52.4 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

**Comment by jzluo** [comment]
Yes, looks like that fixed sequential regression!
```python
243 µs ± 4.67 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
111 µs ± 160 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
502 µs ± 52.5 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each
```

**Comment by serge-sans-paille** [comment]
@jzluo the situation should be better now with the latest change in #2017. Very small least dimension (20 in your case) is not enough to completely hide the vectorization overhead, but that's still better. Using clang instead of GCC also helps in my experience.
I'm curious about the timing in your case.

**Comment by jzluo** [comment]
Thanks so much for all your work. It is much improved and for my case of 20 is no longer slower than Numpy. I played around with it a little more and tested an equivalent `(X.T * rootW).T` (call it `XtW`) in addition to the original `rootW[:, np.newaxis] * X` (call it `XW`).  Please see the plot - I find that `XtW` has no performance hit with simd, whereas `XW` actually is still slower than Numpy if larger than dimension size 20 in my example. However at some point (>200 cols in my case) they all become much slower for some reason, which I suppose belongs in a different issue.

```python
#pythran export XW_pythran(float[:,:], float[])
def XW_pythran(X, preds):
    rootW = np.sqrt(preds * (1 - preds))
    XW = rootW[:, np.newaxis] * X
    return XW

#pythran export XtW_pythran(float[:,:], float[])
def XtW_pythran(X, preds):
    rootW = np.sqrt(preds * (1 - preds))
    XW = (X.T * rootW).T
    return XW

# for plot
import perfplot

np.random.seed(0)
preds = np.random.random(20000)
perfplot.show(
    setup=lambda n: np.random.rand(20000, n),
    kernels=[
        lambda X: get_XW(X, preds),
        lambda X: XW_pythran(X, preds),
        lambda X: XW_pythran_simd(X, preds),
        lambda X: XtW_pythran(X, preds),
        lambda X: XtW_pythran_simd(X, preds)
    ],
    labels=["np", "pythran_XW", "pythran_simd_XW", "pythran_XtW", "pythran_simd_XtW"],
    n_range=[i for i in range(20, 280, 20)],
    xlabel="n_cols",
    relative_to=0,
)
```

![Screenshot from 2022-09-13 00-22-30](https://user-images.githubusercontent.com/20971593/189808192-759d6001-e593-4c92-879b-18520e511e4d.png)

**Comment by serge-sans-paille** [comment]
Thanks for the great feedback! Can you duplicate the above post in another issue? This threshold effect at 200 is fascinating, probably a cache effect or something, I want to find the reason behind this! You're triggering my curiosity :-)

**Comment by serge-sans-paille** [comment]
@jluzo thanks for opening the new issue. I've fixed an other performance bug in  #2017 (no the threshold effect), can you check the impact on your setup?

**Comment by jzluo** [comment]
Great! It now matches the sequential version.

![Screenshot from 2022-09-15 16-58-26](https://user-images.githubusercontent.com/20971593/190507616-9f22480a-4715-46dd-b58a-d5c8e3ade263.png)

**Comment by serge-sans-paille** [comment]
Thanks a lot for the reports your provided during this bug o/
