### ISSUE TITLE
np.fft.fftn Unknown

### ISSUE THREAD

**Issue by Sifyrena** [serge-sans-paille/pythran#2023]
A quick attempt to put some code of mine through Pythran gave me 

`error: Attribute 'fftn' unknown`

I see that in the documentation only 1D Fourier is supported at the moment. Will this change?

Thanks, Sifyrena

**Comment by serge-sans-paille** [comment]
Hi @Sifyrena, pythran currently relies on pocketfft to implement fft operations. Let me check if `fftn` can be implemented through it.
