### ISSUE TITLE
Same timings for matmul example using python or compiled function 

### ISSUE THREAD

**Issue by ljmartin** [serge-sans-paille/pythran#2027]
Hi again Pythran, 
I'm enjoying using the library! However I can't see any speedup cf regular python, so potentially I'm missing something here. 

Actually, using the matrix_multiply function from the user manual, I see almost the exact same times. So close that I wonder if it's falling back to regular python - is that possible?

Some code to reproduce:

Here's the exact matmul file, as it is given in the user manual, named `mm.py` and compiled with `pythran mm.py`:
```fortran
#pythran export matrix_multiply(float list list, float list list)
def zero(n,m): return [[0]*n for col in range(m)]
def matrix_multiply(m0, m1):
    new_matrix = zero(len(m0),len(m1[0]))
    for i in range(len(m0)):
        for j in range(len(m1[0])):
            for k in range(len(m1)):
                new_matrix[i][j] += m0[i][k]*m1[k][j]
    return new_matrix
``` 

Now a timing script:
```python
import mm
import numpy as np
import matplotlib.pyplot as plt

def zero(n,m): return [[0]*n for col in range(m)]
def matrix_multiply_python(m0, m1):
    new_matrix = zero(len(m0),len(m1[0]))
    for i in range(len(m0)):
        for j in range(len(m1[0])):
            for k in range(len(m1)):
                new_matrix[i][j] += m0[i][k]*m1[k][j]
    return new_matrix

times_pythran = []
times_python = []

for n in [10, 30, 100, 300]:
    print(n)
    
    m0 = np.random.random([n,100])
    m1 = np.random.random([100,n])
    
    #measure time taken for the pythran-compiled function:
    before = time.time()
    _ = mm.matrix_multiply(m0, m1)
    now = time.time()
    
    times_pythran.append(now-before)
    
    #measure time taken for the regular python function:
    before = time.time()
    _ = matrix_multiply_python(m0, m1)
    now = time.time()
    
    times_python.append(now-before)
    
    
plt.plot([10, 30, 100, 300], times_pythran, label='pythran')
plt.plot([10, 30, 100, 300], times_python, label='python')
plt.xlabel('n')
plt.ylabel('time (s)')
plt.xscale('log')
plt.legend()
```

we can see that the times closely match - almost too close! Any idea what's lacking here?
Thanks for your time. 
Lewis

<img width="535" alt="Screen Shot 2022-10-11 at 8 01 29 pm" src="https://user-images.githubusercontent.com/8262765/195046763-a5330724-4688-489a-b492-6295d18f261f.png">

**Comment by jzluo** [comment]
Your `#pythran export matrix_multiply(float list list, float list list)` specifies python lists, whereas you create ndarrays in your setup:
```python
m0 = np.random.random([n,100])
m1 = np.random.random([100,n])
```
Running your code as-is errors for me as expected:
```
Traceback (most recent call last):
  File "/home/jon/projects/blah/timing.py", line 26, in <module>
    _ = mm.matrix_multiply(m0, m1)
TypeError: Invalid call to pythranized function `matrix_multiply(float64[:, :], float64[:, :])'
Candidates are:

    - matrix_multiply(float list list, float list list)
```

If you change your setup to create lists:
```python
m0 = [[random.random() for i in range(n)] for j in range(100)]
m1 = [[random.random() for i in range(100)] for j in range(n)]
```
or, change the specification to ndarray: `#pythran export matrix_multiply(float[:, :], float[:, :])`, it will run as expected. Plot for the list setup:

![Figure_1](https://user-images.githubusercontent.com/20971593/195412143-d305b594-7611-44c0-bf2b-77b587907a9a.png)

So I guess the next question is why yours didn't give a TypeError.

**Comment by serge-sans-paille** [comment]
Thanks @jzluo for the detailed answer <3
@ljmartin you can check if you're using the pytrhanized version of `mm` by checking if it has a `__pythran__` attribute.

**Comment by ljmartin** [comment]
Thanks @jzluo for taking the time to look through my code - and the note on types!

@serge-sans-paille - thanks for that tip. Indeed there is no `mm.__pythran__` attribute. Perhaps this answers both questions (timing and lack of TypeError)? 

Unfortunately it looks like I was just importing `mm.py`. Running `pythran mm.py` writes only one file - named `mm.cpython-310-darwin.so`. Would you expect it to write `mm.so`? If I remove `mm.py` to another directory then the import fails with Module Not Found. 

Thanks 
Lewis

**Comment by ljmartin** [comment]
Alright, just renaming the `.so` file to the expected name `mm.so` works, and the timing is as expected. I'm happy manually changing the file name, but if you feel this presents a problem please lmk!

**Comment by paugier** [comment]
> Unfortunately it looks like I was just importing `mm.py`. Running `pythran mm.py` writes only one file - named `mm.cpython-310-darwin.so`. Would you expect it to write `mm.so`? If I remove `mm.py` to another directory then the import fails with Module Not Found.

IMHO, this should be considered as a bug, and the issue should not be closed. Pythran has to produce an importable file, without need for renaming!
