### ISSUE TITLE
Warnings with the main development branch of numpy

### ISSUE THREAD

**Issue by WarrenWeckesser** [serge-sans-paille/pythran#2041]
I have Pythran 0.12.0 installed.  When building SciPy with the numpy main branch (e.g. `'1.25.0.dev0+11.ga872fd73e'`), *many* repetitions of this warning are generated:

```
/home/warren/py3.10.8/lib/python3.10/site-packages/pythran/tables.py:4555: FutureWarning: In the future `np.bytes` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
  obj = getattr(themodule, elem)
```

NumPy has been cleaning up its namespace, so it is not surprising that issues like this show up.

**Comment by serge-sans-paille** [comment]
can you confirm #2041 fixes the issue?

**Comment by WarrenWeckesser** [comment]
I think you meant gh-2043, and yes, it appears to have fixed the warnings--thanks!

Is there a reason the development version of pythran still has version 0.12.0?  I would have expected that to be bumped to something like 0.12.1.dev0 or 0.13.0.dev0 after 0.12.0 was released.  As it is now, an extra command or two is needed to switch back to 0.12.0 from PyPI.

**Comment by serge-sans-paille** [comment]
I did meant #2043 :-) and yeah I forgot to bump the revision number.

**Comment by serge-sans-paille** [comment]
5c91deda2afbad751ddeebea3298446ba5ca7fb7 bumped the revision number. Sorry for the inconvenience.
