### ISSUE TITLE
pythran constraints None:None error: Specification for `xx` does not match inferred type

### ISSUE THREAD

**Issue by Antares-Wu** [serge-sans-paille/pythran#2051]
in my ubuntu machine, use python3.8,  pythran0.12.0
use command: **pythran trans_test.py**
there are two relatively simple function written in trans_test.py that l got the error:

``` 
#pythran export value_fill_max(str, int:int dict)
def value_fill_max(x,dic):
    l = list(dic.keys())
    if type(l[0]) == int:
        x = int(x)
    if type(l[0]) == str:
        x = str(x)
    if x not in l:
        x = max(l)
    return x
```
trans_test.py:None:None error: Specification for `value_fill_max` does not match inferred type:
expected `Callable[[Collection[T0, T1], Dict[Collection[T0, T1], T2]], Collection[T0, T1]]`
got `Callable[[str, Dict[int, int]], ...]`

```
#pythran export value_fill_min(str, int:int dict)
def value_fill_min(x,dic):
    l = list(dic.keys())
    if type(l[0]) == int:
        x = int(x)
    if type(l[0]) == str:
        x = str(x)
    if x not in l:
        if -999 in l:
            l.remove(-999)
        x = min(l)
    return x
```

trans_test.py:None:None error: Specification for `value_fill_min` does not match inferred type:
expected `Callable[[int, Dict[int, T0]], int]`
got `Callable[[str, Dict[int, int]], ...]`

l tried deleting some of the code in the function, turns out that only 
`l = list(dic.keys())` 
does not have a problem.
I've been digging for the answer for a while, could anyone help me with the right coding style?

**Comment by serge-sans-paille** [comment]
Thanks for this interesting test case! There a re several issues with pythran in the way it would handle it, fix being crafted.
The prettiest (to me) way to write this code would be

```
#pythran export value_fill_max(str, int:int dict)
def value_fill_max(x, dic):
    key_type = type(next(iter(dic)))
    x = key_type(x)
    return x if x in dic else max(dic.keys())
```

And it's also more efficient than your approach that performs a copy to a list.

In both cases this requires a patch in Pythran, keep in touch.
