### ISSUE TITLE
numpy.clip does not have a way to specify only max for clip

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#2054]
The numpy clip function allows None for either min or max arg to specify no clipping on the corresponding bound.
pythran clip does not seem to allow None.
pythran clip does seem to allow specifying only min, avoiding max (from my reading of the code clip.hpp)
But there is no way to specify only a max, and not a min.

**Comment by serge-sans-paille** [comment]
Indeed. Thanks for reporting this, I'll have a look.

**Comment by nbecker** [comment]
For now my workaround is use np.inf or -np.inf for one limit, but probably
slower

**Comment by serge-sans-paille** [comment]
Fix available, that should indeed be slightly faster
