### ISSUE TITLE
On mac os, pythran -v no longer shows the compilation command

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#2069]
Title says it all.

**Comment by serge-sans-paille** [comment]
Maybe something changed at the setuptool level along those lines: https://github.com/serge-sans-paille/pythran/blob/master/pythran/toolchain.py#L309 ?
Can you modify that part to always pass ``--verbose`` and report if it has the expected effect?

**Comment by jeanlaroche** [comment]
OK I'll try

**Comment by jeanlaroche** [comment]
I don't get it. It seems to work normally now... I don't know what was going on when I reported this but now I get the compiler command when I use -v. Closing this...
