### ISSUE TITLE
compilation error with 2nd overload

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#2071]
For this small code:

https://gist.github.com/nbecker/18006c9a478d1a53e7210c4969c38f3f

If the 2nd overload is present compilation fails.
The lines 
 ```
theta = np.array (theta)
phi = np.array (phi)
```
were added to allow scalar values of the values theta and phi to be used.

testing a python version is OK
```
getArrayFactor (W, px, py, 0., 0., L)
Out[115]: 1024.0
```

**Comment by serge-sans-paille** [comment]
#2073 should do the trick if you replace `theta.shape` by `np.shape(theta)`

**Comment by serge-sans-paille** [comment]
Actually should work without a change :-)

**Comment by nbecker** [comment]
I think I have correctly updated to this version, but I still get compile error (both gcc and clang) on the example I posted (gist).  Can you verify it compiles without change?  Otherwise somehow I failed on updating.
