### ISSUE TITLE
Problems when broadcasting with ones in the shape

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#2086]
This works in Python, but sends Pythran calling for Jack:

```
import numpy as np

# pythran export f
def f():
    data = np.zeros(5)
    data[:] = np.ones([1, 5])
    return data
```

This modification compiles successfully:

```
# pythran export f
def f():
    data = np.zeros(5)
    return data * np.ones([1, 5])
```
but coredumps when importing it.

It is odd because this is the Python version pythran spits out:

``` 
def f():
   return __pythran_import_numpy.array(((0.0, 0.0, 0.0, 0.0, 0.0),), __pythran_import_numpy.float64)
```

**Comment by Dapid** [comment]
The backtrace isn't very illuminating for me, but maybe it will give you a hint:

https://gist.github.com/Dapid/989e12bef7702b85b3439f2bddb3d897

**Comment by serge-sans-paille** [comment]
Ahhh, this Jack, he's always lurking around :-) I'll have a look. Thanks for reporting!

**Comment by serge-sans-paille** [comment]
```
# pythran export f
```
should be 
```
# pythran export f()
```

that solves the second issue, not the first (but we should warn about this, exporting a function as a global variable is not allowed)

**Comment by serge-sans-paille** [comment]
Hey Dapid, can you tell me if #2088 fixes both the incorrect annotation and the original issue? Thanks!

**Comment by Dapid** [comment]
It does, thank you!
