### ISSUE TITLE
GCC error with list comprehension

### ISSUE THREAD

**Issue by albatros69** [serge-sans-paille/pythran#2109]
Compiling the below code leads to a GCC error:
```python
#pythran export f(int list)
def f(l):
    return [ p for _,p in enumerate(l) if p%2 ]
```

It seems this is the combination of `enumerate` with the filter that makes the compilation choke:
 - Removing the `if` statement is sufficient to make the error disappear ;
 - Removing the call to `enumerate` too.

**Comment by serge-sans-paille** [comment]
Thanks for reporting! I'll have a look.

**Comment by serge-sans-paille** [comment]
And I can confirm the issue :-)
