### ISSUE TITLE
Reversing a range

### ISSUE THREAD

**Issue by radkoff** [serge-sans-paille/pythran#2135]
It seems if you reverse a range bigger than size 256, you can't properly turn it into an ndarray because the type stays range_iterator.

```
# Works
# pythran export foo()
def foo():
    arr = np.array(list(reversed(range(0, 255))))
    print(arr + 1.0)

# Does not work
# pythran export bar()
def bar():
    arr = np.array(list(reversed(range(0, 256))))
    print(arr + 1.0)
```

```
>>> unsupported operand type(s) for +: 'range_iterator' and 'float'
----
    print(arr + 1.0)
          ^~~~ (o_0)
----
```

Not a big deal because I realized I can just use `range(255, -1, -1)`, but I thought I'd report because it took a while to track down what was happening.

Version `0.13.1`, mac OS

**Comment by serge-sans-paille** [comment]
Thanks for reporting! #2137 should do the trick
