### ISSUE TITLE
New warnings: "Overriding pythran description with argspec information"

### ISSUE THREAD

**Issue by rgommers** [serge-sans-paille/pythran#2139]
I just noticed a ton of these warnings with pythran `master` and Cython 3.0:
```
[16/1588] Generating 'scipy/_lib/_ccallback_c.cpython-312-x86_64-linux-gnu.so.p/_ccallback_c.c'
WARNING: Overriding pythran description with argspec information for: numpy.random.binomial
WARNING: Overriding pythran description with argspec information for: numpy.random.bytes
```
I'm unsure if this is a Pythran or a Cython issue, and what to do with these warnings. Just opening it here in case this looks familiar, because the warning explicitly mentions `pythran`.

It's not breaking anything yet as far as I can tell, it's only build log pollution.

**Comment by serge-sans-paille** [comment]
This probably means that a numpy update provided extra type information, so we no longer need to provide them in pythran. I'll have a look.

**Comment by rgommers** [comment]
Ah, that helps. It's probably numpy 2.0 + cython 3.0, which cause Cython to now prefer https://github.com/numpy/numpy/blob/main/numpy/__init__.cython-30.pxd over the `numpy.pxd` that it has itself.

**Comment by serge-sans-paille** [comment]
mmh what's that numpy 2.0 ? Not part of pypi, right? In that case I can't fix this unless i add a hook for the WIP version of numpy, which is not something I'd like to do.

**Comment by rgommers** [comment]
It should be due to https://github.com/numpy/numpy/pull/21975, which also got backported to 1.26.0b1.

**Comment by rgommers** [comment]
I'm working on a fix for this.
