### ISSUE TITLE
supported numpy kwarg?

### ISSUE THREAD

**Issue by ogauthe** [serge-sans-paille/pythran#2172]
Hi,

I want to call a stable `argsort` on a numpy array. I note that `argsort` works both as a numpy function and as a ndarray method (the second is not mentioned as implemented but I observe it works), but the kwarg `kind` does not seem to be supported.

My question here is: is any numpy optional kwarg supported in pythran? Could the documentation specify this or which ones are supported?

pythran `0.12.2`

Thanks!

**Comment by serge-sans-paille** [comment]
We have kwarg support in Pythran, both at user and package level. It relies on the `inspect` module to automagically discover values, and sometimes need a bit of help from the compiler. Let me have a look for argsort.

**Comment by serge-sans-paille** [comment]
ok, in the case of `numpy.argsort` it's just that I haven't added support for the `kind` keyword argument in `pythonic` (the native backend). `inspect` does its job as expected (otherwise you'd get a syntax error because kwargs are statically checked).
