### ISSUE TITLE
No support for Python 3.12

### ISSUE THREAD

**Issue by haampie** [serge-sans-paille/pythran#2204]
I see some claims that pythran supports Python 3.12, but it uses `distutils` so it doesn't:

https://github.com/serge-sans-paille/pythran/blob/b37f5842aa22239dec078e4c05427e2f08da5e1f/pythran/run.py#L13

causing

```
ModuleNotFoundError: No module named 'distutils'
```

when running `pythran --version`.

This happens for example [in scipy during meson configure](https://github.com/scipy/scipy/blob/7dcd8c59933524986923cde8e9126f5fc2e6b30b/meson.build#L138), resulting in build failure.

Code changes are required to continue to use `distutils`, you cannot rely on `import distutils` to work even if you add a dummy dependency on `setuptools`. See https://github.com/cython/cython/pull/5754#issuecomment-1752102480 for why not.

**Comment by serge-sans-paille** [comment]
Thanks for the report. I believe #2205 fixes most of the issues (?)

**Comment by haampie** [comment]
Fixes it :+1:

**Comment by serge-sans-paille** [comment]
Fixed by #2205

**Comment by haampie** [comment]
Hi @serge-sans-paille, would it make sense to backport this in a patch release? Does pythran have patch releases?

**Comment by serge-sans-paille** [comment]
no patch release, but I plan a release in the forthcoming weeks, I need to have a look at https://github.com/serge-sans-paille/pythran/issues/2203 first though.
