### ISSUE TITLE
[request]python2rust

### ISSUE THREAD

**Issue by okrightall** [serge-sans-paille/pythran#2221]
Translate Python subset to Rust subset.

**Comment by serge-sans-paille** [comment]
Pythran focuses on translating Python code to native code. C++ is just a convenient intermediate representation. What would be the benefit of using rust as an intermediate representation?

Note that given the amount of already written runtime code, this is a theoretical question, in practice I won't have the time to do that. There are a few users of the C++ backend, so I can see some people translating to Rust for the same reasons. That would be greatly beneficial for Pythran (it would enforce a clean split between middle end and backend) but I don't have the time for this.
