### ISSUE TITLE
Support for array module 

### ISSUE THREAD

**Issue by peekxc** [serge-sans-paille/pythran#2226]
I was surprised to find that the [array](https://docs.python.org/3/library/array.html) module is not supported. Is there a reason for this? Seems like a natural and simple candidate to support

**Comment by serge-sans-paille** [comment]
It could! There is some check to be done because the constructor requires a runtime typecode, and we need to make sure it's a literal one, otherwise should be an easy catch.

**Comment by serge-sans-paille** [comment]
See https://github.com/serge-sans-paille/pythran/pull/2227 (just started)
