### ISSUE TITLE
Pythran cannot compile when print numpy.array

### ISSUE THREAD

**Issue by yuancheng2013** [serge-sans-paille/pythran#224]
Compile error when printing arrays in some cases, this might 

For example:
```python
#pythran export foo()
import numpy as np

def foo():
    a = np.ones((6, 8))
    b = np.ones((2, 4))
    d = a[1:3, 4:] + b[:, :]
    print d

foo()
```

This is mainly due to temporary expressions generated in pythran.
To avoid this problem for the moment, we can print 2 times the same array.

**Comment by serge-sans-paille** [comment]
This has been fixed a long time ago. The attached code snippet works like a charm on master, I'm closing this BR.
