### ISSUE TITLE
Compilation error on simple array definition

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#2245]
The latest version of pythran 0.17.0 on Mac M1 does not like this:

```
import numpy as np

#pythran export test()
def test():
    sRate = 1000
    dur = (np.array([.2,.4,1,2.1,.02])*sRate).astype(int) # <-  1 is interpreted as an int. Replace with 1. and things are good.
    return dur
```
I have a workaround but just in case you want to fix it.
Thanks a million for the new release, just the same!!!

**Comment by serge-sans-paille** [comment]
That's an interesting one! I can reproduce.

**Comment by jeanlaroche** [comment]
I think it's new though, did not happen with previous versions, I think.
