### ISSUE TITLE
Updating Conda/Mamba instructions to just use Miniforge

### ISSUE THREAD

**Issue by jakirkham** [serge-sans-paille/pythran#2246]
Currently Pythran's README has [the following text]( 
https://github.com/serge-sans-paille/pythran/blob/bb5e0f118983dc2d0f3bc2d7e9b51e42a8eff7fd/README.rst?plain=1#L49 ):

> 1. Using ``mamba`` (https://github.com/conda-forge/miniforge#mambaforge) or ``conda`` (https://github.com/conda-forge/miniforge) 

However in conda-forge the Miniforge and Mambaforge installers were combined into a single Miniforge installer, which has both. Also the Mambaforge installer is being deprecated. More details in [these FAQs]( https://github.com/conda-forge/miniforge?tab=readme-ov-file#faq )

Would recommend simplifying this instruction to just point at Miniforge for both use cases

**Comment by serge-sans-paille** [comment]
On Thu, Oct 31, 2024 at 06:08:36PM -0700, jakirkham wrote:
> Currently Pythran's README has [1]the following text:
> 
>      1. Using mamba ([2]https://github.com/conda-forge/miniforge#mambaforge) or
>         conda ([3]https://github.com/conda-forge/miniforge)
> 
> However in conda-forge the Miniforge and Mambaforge installers were combined
> into a single Miniforge installer, which has both. Also the Mambaforge
> installer is being deprecated. More details in [4]these FAQs
> 
> Would recommend simplifying this instruction to just point at Miniforge for
> both use cases

Could you submit a PR?
