### ISSUE TITLE
Question about pythran support + LowLevelCallables

### ISSUE THREAD

**Issue by peekxc** [serge-sans-paille/pythran#2254]
Pythran is great, and it covers many of my own use-cases: python/numpy + pythran = efficient and maintainable code. 

Occasionally, though, I want to pythranize a function that has an input parameter whose type is either not directly supported by Pythran (but maybe can be, via something like #2089) or is simply not known ahead-of-time. Use-cases include sparse matrix multiplication (the former) or a user-supplied function (the latter). Supporting one of the two above options would extend that coverage. 

So, I had to ask, is it feasible, planned, or even in Pythrans philosophy to eventually extend support to: 
 a) something like [LowLevelCallables](https://docs.scipy.org/doc/scipy/reference/generated/scipy.LowLevelCallable.html)
 b) arbitrary [Callables](https://docs.python.org/3/library/functions.html#callable)

I realize (b) is probably much harder to support than (a), and maybe both are out of scope. For example, I think (b) would involve expanding Pythran to support running arbitrary Python code via the interpreter. Nonetheless, there are situations where its useful to have the ability to invoke the interpreter in the middle or otherwise natively compiled code. 

Other libraries used in similar contexts to pythran tend to support these features to some extent. Cython supports (b) of course (and I think (a)), and Numba supports (b) via [object mode](https://numba.pydata.org/numba-doc/dev/glossary.html#term-object-mode). Like Cython, pybind11 supports both (b) via [invoking the interpreter](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/object.html#calling-python-functions) and also supports something close to (a) when the C function is stateless and its signature is known (see the 'warning' section [here](https://pybind11.readthedocs.io/en/stable/advanced/cast/functional.html)).

**Comment by serge-sans-paille** [comment]
Is a) be close to https://pythran.readthedocs.io/en/latest/MANUAL.html#capsule-corp ?
Pytrhan-generated modules release the GIL once they have parsed the exported function arguments, which is incompatible with b) as far as I understand.

**Comment by peekxc** [comment]
Going off [this great blog post](https://serge-sans-paille.github.io/pythran-stories/the-capsule-corporation.html), I was hoping to be able to write something like: 

```python
#pythran export capsule f(int32, float64*, float64* )
def f(n, x, cp):
    c = cp[0]
    return c + x[0] - x[1] * x[2]
```

Then, somewhere else (possibly in a different library!), have something like: 

```python
#pythran export my_fancy_nquad(double (int, double *, void *), float64* )
def my_fancy_nquad(func, dat)
   ...
```

Usage would then be like: 

```python
from testlib import f
from otherlib import my_fancy_nquad

c = ctypes.c_double(1.0)
user_data = ctypes.cast(ctypes.pointer(c), ctypes.c_void_p)
func = LowLevelCallable(f, user_data, signature="double (int, double *, void *)")

my_fancy_nquad(func, user_data)
```

**Comment by serge-sans-paille** [comment]
Yes! If that doesn't work, then you should open a bug :-)

**Comment by peekxc** [comment]
I dont believe Pythran supports passing pointers-to-functions, i.e. this doesn't compile: 

```python

#pythran export my_fancy_nquad(double (int, double *, void *), float64* )
def my_fancy_nquad(func, dat) -> float: 
   return 0
```

**Comment by serge-sans-paille** [comment]
It does, and indeed the message you get when trying to compile the above are explicit:
```
 error: Unexpected identifier `double` at that point
```

then

```
error: Unexpected identifier `void` at that point
````

but the following compiles ok:

```
#pythran export my_fancy_nquad(float64 (int, float64 *, int *), float64* )
def my_fancy_nquad(func, dat) -> float:
   return 0
```

**Comment by serge-sans-paille** [comment]
(note: https://github.com/serge-sans-paille/pythran/pull/2255 should avoid the confusion between double and float64, etc)

Should I consider this issue closed then?

**Comment by peekxc** [comment]
yes, sorry I didn't realize I was making a simple mistake
