### ISSUE TITLE
segfault on nested list

### ISSUE THREAD

**Issue by pbrunet** [serge-sans-paille/pythran#238]
Has I am looking at some long code, I found a segfault.

The code is : pythran/tests/cases/matmul.py

The test case it : `python -c "import matmul; a=[ [ float(i) for i in xrange(600)] for j in xrange(400)]; matmul.matrix_multiply(a, a)`

It is really weird as : `python -c "import matmul; a=[ [ float(i) for i in xrange(600)] for j in xrange(600)]; matmul.matrix_multiply(a, a)` works.

**Comment by serge-sans-paille** [comment]
Ok, the problem was just related to an invalid parameter for a matmul,
