### ISSUE TITLE
compile failure: isinstance not supported

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#310]
``` python
import numpy as np

def conj (x):
    if x.dtype == complex:
        return x.real - 1j*x.imag
    else:
        return x

#pythran export mag_sqr(float64[])
#pythran export mag_sqr(complex128[])
def mag_sqr (x):
    return x * conj(x)
```

---

/tmp/tmpVJcDTS.cpp:39:183: error: no matching function for call to  getattr(pythonic::types::ndarray<double, 1ul>) 
       typedef decltype(pythonic::**builtin**::getattrpythonic::types::attr::REAL(std::declval<typename std::remove_cv<typename std::remove_reference<argument_type0>::type>::type>())) __type0;

**Comment by serge-sans-paille** [comment]
That was an old one :-)
