### ISSUE TITLE
abs vs np.abs

### ISSUE THREAD

**Issue by pbrunet** [serge-sans-paille/pythran#321]
These 2 functions should have the same behavior but np.abs is the only one working on numpy array.

**Comment by serge-sans-paille** [comment]
The following snippet:
```python
#pythran export ab(float [], float)
import numpy as np
def ab(a, b):
    return np.abs(a), abs(a), np.abs(b), abs(b)
```

works like a charm since 2de7ece1772eaf83366806c9d53563f309d903d7

**Comment by zhyiyu** [comment]
I think now (October 2020) `abs` also works on `numpy` arrays.
