### ISSUE TITLE
Do not evaluate list on numpy_expr

### ISSUE THREAD

**Issue by pbrunet** [serge-sans-paille/pythran#361]
We perform a list to array conversion when list is use in a numpy_expr.
It could be avoid implementing some extra field like : shape, fast, ...

Once it is done, we could try to forward np.copy to np.asarray to avoid extra copy.

**Comment by serge-sans-paille** [comment]
It's been a while since we implemented the « lists are no longer copied when passed as numpy expr parameter » behavior.

#1518 implements some extra np.copy elision, let's consider it fixes that Issue!
