### ISSUE TITLE
Extra need of PYTHONPATH

### ISSUE THREAD

**Issue by lisqlql** [serge-sans-paille/pythran#403]
Hi,

It seems that `PYTHONPATH` **must** be passed to `pythran` when compiling some `.py` file.

Here is a little example:

## foo.py
```python
import bar

#pythran export foo()
def foo():
    print "foo"
    bar.bar()

foo()
```
- - -

## bar.py
```python
#pythran export bar()
def bar():
    print "bar"
```
- - -

Here is how you normally use `pythran` (without any options):
```
pythran foo.py
``` 

Here is the [output](http://pastebin.com/cHpxanYa).

And now, here is a workaround to make it work:
```
PYTHONPATH=$(pwd) pythran foo.py
```

**Comment by pbrunet** [comment]
Fixed with #406
