### ISSUE TITLE
Better tracking of modules when an error occurs

### ISSUE THREAD

**Issue by lisqlql** [serge-sans-paille/pythran#404]
Hi,

When `pythran` find an error in an imported module, the output is not very 'complete' and there is no information about which module contains the error.

## foo.py
```python
import bar

#pythran export foo()
def foo():
    print bar.bar()

foo()
```
- - -

## bar.py
```python
import baz

#pythran export bar()                                                           
def bar():                                                                      
    print baz.k 
```
- - -

## baz.py
```python
k = 10
```
- - -

Here is the output when running `pythran foo.py`:

```
CRITICAL I am in trouble. Your input file does not seem to match Pythran's constraints...
E: Attribute 'k' unknown (line 5)
```

This is a simple case, so it is easy to track the error by yourself, but when you have much more modules, it could be very difficult to track in which module the error comes from.

**Comment by serge-sans-paille** [comment]
Bug #404 : page not found
