### ISSUE TITLE
is_integer

### ISSUE THREAD

**Issue by pbrunet** [serge-sans-paille/pythran#420]
is_integer use modf. Cast may be faster than this.

**Comment by serge-sans-paille** [comment]
We now use ``std::trunc`` and casting is not an option if the double is greater than an integer (think ``2e65``).

that's the approach of CPython:

```
    PyFPE_START_PROTECT("is_integer", return NULL)
    o = (floor(x) == x) ? Py_True : Py_False;
    PyFPE_END_PROTECT(x)
```

So that should be ok
