### ISSUE TITLE
dict and unordered_map

### ISSUE THREAD

**Issue by pbrunet** [serge-sans-paille/pythran#424]
dict use as a container boost::unordered_map. Why do we use this instead of the std implementation? Or just std::map?

**Comment by serge-sans-paille** [comment]
On Thu, Apr 02, 2015 at 12:21:58AM -0700, pbrunet wrote:
> dict use as a container boost::unordered_map. Why do we use this instead of the std implementation? Or just std::map?

I've benchmarked the implementations and boost's is faster on the
problem I benchmarked.

**Comment by serge-sans-paille** [comment]
Fixed by 88a16dc631ff1481051e3a721b679a71b74b20e5 . Timing may depends based on the implementation, but using the standard library allows us to bundle less boost header.
