### ISSUE TITLE
None type as input type

### ISSUE THREAD

**Issue by pbrunet** [serge-sans-paille/pythran#427]
We do not support None type as inputs for exported function:
```
#pythran export foo(int none)
```

**Comment by pbrunet** [comment]
Here is an implementation:
#549

It doesn't combine types as input as proposed but accept:

```
#pythran export foo(int)
#pythran export foo(none)
```

**Comment by serge-sans-paille** [comment]
any reason you don't combine type as input? This looks better to me

**Comment by pbrunet** [comment]
It doesn't looks to be really typed syntax to me. We don't support ```foo(int float)``` to support both int and float.

**Comment by serge-sans-paille** [comment]
I agree!
