### ISSUE TITLE
None step to have continuous slice

### ISSUE THREAD

**Issue by pbrunet** [serge-sans-paille/pythran#428]
None step are not concidere as a continuous slice.
The reason is that we check for None instead of `__builtin__.None`.

**Comment by serge-sans-paille** [comment]
The second part of your statement seems incorrect to me:

```python
>>> a = range(10)
>>> a[8:1]
[]
>>> a[1:8]
[1, 2, 3, 4, 5, 6, 7]

**Comment by pbrunet** [comment]
Fixed
