### ISSUE TITLE
implement numpy.squeeze

### ISSUE THREAD

**Issue by coyotte508** [serge-sans-paille/pythran#455]

**Comment by serge-sans-paille** [comment]
Unfortunately, that's impossible in pythran, as the number of dimension is part of the type in pythran, and squeeze changes it dynamically.

**Comment by coyotte508** [comment]
What about creating a new type for a squeezed array that would behave dynamically?

**Comment by pbrunet** [comment]
This could be a solution but IMO it is too expensive for us.
Looking at the numpy module, most implementation rely on the depth parameter for every array like.
It means that we should provide a new implementation without this information for every function so pythran code will be too big for serge and me.
The other solution could be to change the array like implementation to not have this parameter but it is really useful to have performance (looks unrolling and others thinks can be done a compile time thanks to this). Also, depths of an array looks to be part of the type. You will never have int[] or int[][] for the same signature in C/C++ functions.

**Comment by serge-sans-paille** [comment]
Theoretically, arrays could have a dynamic number of dimensions. If I
remember correctly how it's done in nt2, they have a large number of
fixed dimensions, and then dynamically manage the real dimension, that
needs to be lwoer than the fixed one.

We don't have the time / will to go that far ;-) But maybe coyott wants
to screw his PhD and do it ;-)

**Comment by coyotte508** [comment]
Well... ^^

Too bad for this.
