### ISSUE TITLE
implement numpy.random.binomial

### ISSUE THREAD

**Issue by coyotte508** [serge-sans-paille/pythran#456]

**Comment by serge-sans-paille** [comment]
@artas360 do you plan to do this any soon?

**Comment by artas360** [comment]
I ll get to it, sorry I missed the mail...

**Comment by artas360** [comment]
@coyotte508 the implementation has been pushed. Can you check if it's what you expected?

**Comment by artas360** [comment]
@serge-sans-paille can you close this issue?
