### ISSUE TITLE
Support passing functions to pythran functions

### ISSUE THREAD

**Issue by fsteinmetz** [serge-sans-paille/pythran#461]
It would be nice to be able to pass function (ideally, pythranized functions) to pythran functions.
This would allow accelerate optimization functions (see http://docs.scipy.org/doc/scipy/reference/optimize.html for examples).

**Comment by serge-sans-paille** [comment]
thanks @fsteinmetz for the bug report / feature request!

Just so you know, calling a pythran function as a function parameter of a python function should work nice.

Calling a pythran function as parameter of a pythran function from a pythranized module should work too.

What does not work now is taking a Python function as parameter of a pythran function.

I wonder what kind of signature would be expected, let me propose

```
#pythran export fool((int -> int))
```

for  a function named `foo` that takes a function as first parameter, where the function takes an int and returns an int.

Note that technically, the return type of the first argument could be inferred by pythran, but it looks like a common syntax to declare a function argument.

What do you think?

**Comment by fsteinmetz** [comment]
Thanks for your answer, Serge.
> Calling a pythran function as parameter of a pythran function from a pythranized module should work too.

Now I realize that if you have a module foo where you "from bar import bar", pythranizing foo will also pythranize function bar (or not ?). So actually I think it's perfectly fine for my use case: the function to be minimized would be defined in foo, and passed as argument to the minimization function bar. Looks good!

In the case you are referring to,
> What does not work now is taking a Python function as parameter of a pythran function.

the python function would (?) not be compiled, so this does not seem very interesting (at least, I can see no obvious use case for that).
So as I understand it now, this issue is not really an issue :)

**Comment by serge-sans-paille** [comment]
On Wed, Jun 03, 2015 at 07:40:26AM -0700, François Steinmetz wrote:
> Thanks for your answer, Serge.
> > Calling a pythran function as parameter of a pythran function from a pythranized module should work too.
> 
> Now I realize that if you have a module foo where you "from bar import bar", pythranizing foo will also pythranize function bar (or not ?). So actually I think it's perfectly fine for my use case: the function to be minimized would be defined in foo, and passed as argument to the minimization function bar. Looks good!

That's correct, although that's not the most tested feature of Pythran.
report bug if any!

Calling Python function would implie a back-to-the-interpreter mode, indeed. I'm not 100% sure that would be great, there are also potential problems of threading / exceptions etc in that case :-)

**Comment by serge-sans-paille** [comment]
For all the above reason, I'm closing the issue :-)
