### ISSUE TITLE
Runtime detection of optimized module

### ISSUE THREAD

**Issue by decabyte** [serge-sans-paille/pythran#467]
Hi all,

I was wondering if it will be possible to detect at runtime if the imported module is the native python version or instead the "compiled" one using pythran. 

This is a nice to have in production system as well as during development stages. The rationale is detecting at runtime if the current system is running or not with the support of the optimized version of your code. 

Currently this is possible using a snippet like:
```python
import mymodule

if not mymodule.__file__.endswith('.so'):
    print('loaded .py module')
```

I'm not sure this is the way to go but I was wondering if it may be possible to add a set of globals to the generated module. This will allows the users to quickly check if the optimized version is available or not (e.g. __PYTHRAN) and to inspect some metadata regarding the compilation process (e.g compiler version, flags, timestamp and hash of the original .py file).  Several examples can be found for these flags. The hash one can provide a quick way to check if a given compile module still refer to actual version of its .py counterpart.

For instance as pseudocode:
```python
import hashlib

def check_source(mymodule):
    import mymodule

    if not mymodule.__file__.endswith('.so'):
        return False

    h = hashlib.sha1()
    
    with open('mymodule.py') as fp:
         h.update(fp.read())
    
    return mymodule.__PYTHRAN_HASH == h.hexdigest()
```

Then on the command line:
```
$ pythran --check mymodule.py
>> Compiled module (mymodule.so) matches (mymodule.py) source version.
```

**Comment by serge-sans-paille** [comment]
+1 for providing a ``__pythran__`` global variable that holds the sha1 and a few flags. The ``--check`` flag looks like something to be ``implemented`` outside of pythran though.

**Comment by serge-sans-paille** [comment]
Does

```pythran
In [1]: import a

In [2]: dir(a)
Out[2]: ['__doc__', '__file__', '__name__', '__package__', '__pythran__', 'a']

In [3]: a.__pythran__
Out[3]: 
('0.7.1',
 '2015-07-23 11:15:44.339971',
 '80c392232a7c6fb929b6959a6a7ff6bfe6c89db8528807755dac4bcb9579c4e4')
```

looks like a good scenario to you?

**Comment by serge-sans-paille** [comment]
#468 implements this!

**Comment by decabyte** [comment]
Hello Serge,

that looks very good. ;)

V.

--
Valerio De Carolis - http://decabyte.it
