### ISSUE TITLE
python3.5 typehint

### ISSUE THREAD

**Issue by hainm** [serge-sans-paille/pythran#483]
since python3.5 has type hint, is this a good idea to support it in future (to avoid write pythran directive)?

https://www.python.org/dev/peps/pep-0484/

**Comment by serge-sans-paille** [comment]
I would say yes, but python3 support is *really* a huge task, because it changes the inputs of pythran, the semantic of some buitlins and thus some of our optimizations... And we cannot drop python2 support because it's still used a lot in the scientific community.

**Comment by hainm** [comment]
Agree. 

I think python developers made wrong decision when back-porting python 3's features to py2.

Hopefully people move to py3 since it is much better.

Hai
