### ISSUE TITLE
pythran conda: why must I upgrade to py3.5?

### ISSUE THREAD

**Issue by hainm** [serge-sans-paille/pythran#488]
I am not sure if this is conda issue or your build issue.

```bash
$ python -c 'import sys; print(sys.version)'
2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:50:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
```

```bash
$ conda install -c serge-sans-paille pythran
Fetching package metadata: ..........
Solving package specifications: ..............
Package plan for installation in environment /mnt/raidc2/haichit/anaconda3/envs/py2-pythran:

The following NEW packages will be INSTALLED:

    boost:      1.57.0-4
    cloog:      0.18.1-1
    decorator:  4.0.4-py35_0
    gcc_49:     4.9.1-6
    isl:        0.12.2-0
    mpc:        1.0.1-0
    mpfr:       3.1.2-0
    networkx:   1.10-py35_0
    numpy:      1.9.3-py35_0
    ply:        3.8-py35_0
    pythran:    0.7.1-np19_3

The following packages will be UPDATED:

    pip:        7.1.2-py27_0  --> 7.1.2-py35_0
    python:     2.7.10-1      --> 3.5.0-0
    setuptools: 18.3.2-py27_0 --> 18.3.2-py35_0
    wheel:      0.26.0-py27_1 --> 0.26.0-py35_1

Proceed ([y]/n)?
```

**Comment by serge-sans-paille** [comment]
mmmh, there is not a single mention of python3.5 in pythran's conda recipe...

**Comment by hainm** [comment]
so I guess this is conda issue. I once build a package that specify building all python version but conda only build py3.5. Not sure how to fix this for pythran.

**Comment by serge-sans-paille** [comment]
I am not specifying to build only python2.7 version. that may be the
issue, I'll check this.

**Comment by serge-sans-paille** [comment]
@hainm I uploaded a new revision that explicitly states python2.7. please tell me if that solves your issue!

**Comment by hainm** [comment]
I think not yet

```bash
The following packages will be UPDATED:

    pip:        7.1.2-py27_0  --> 7.1.2-py35_0
    python:     2.7.10-1      --> 3.5.0-0
    setuptools: 18.3.2-py27_0 --> 18.3.2-py35_0
    wheel:      0.26.0-py27_1 --> 0.26.0-py35_1
```

Use `conda install -c serge-sans-paille pythran`

**Comment by serge-sans-paille** [comment]
I get

```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pythran-0.7.1              |                4         1.3 MB

The following NEW packages will be INSTALLED:

    pythran:   0.7.1-4      

The following packages will be UPDATED:

    decorator: 3.4.2-py27_0 --> 4.0.4-py27_0 
    networkx:  1.9.1-py27_0 --> 1.10-py27_0  
    numpy:     1.9.2-py27_0 --> 1.10.0-py27_0
    ply:       3.6-py27_0   --> 3.8-py27_0 
```

so the problem does not seem related to pythran, as far as I understand...

**Comment by hainm** [comment]
yes, seems to be conda problem.

**Comment by serge-sans-paille** [comment]
ok, I'll close the ticket

**Comment by hainm** [comment]
@serge-sans-paille 

I have a trick to make the installation easier for this case.

+ first, use conda to install cmake, gcc, boost, ... from your channel. I got trouble installing pythran from source before since I did not have correct (most updated) versions for those.

+ git clone your pythran and `python setup.py install`

It's still better than using `sudo-apt`.

**Comment by hainm** [comment]
and when building pythran, did you use

`conda build --python=2.7 pythran`?

**Comment by serge-sans-paille** [comment]
On Mon, Oct 12, 2015 at 05:16:30AM -0700, Hai Nguyen wrote:
> and when building pythran, did you use
> 
> `conda build --python=2.7 pythran`?

no, just conda build pythran. I'll try with the flag

**Comment by hainm** [comment]
> no, just conda build pythran. I'll try with the flag

so I guess that's why conda bumped to py3.5 in my machine.

**Comment by bermanmaxim** [comment]
I have an issue related to this, installing pythran through conda on a python 2.7 environment installs pythran to 
"./lib/python3.6/site-packages/pythran/"
instead of
"./lib/python2.7/site-packages/pythran/"
any idea on how to fix this? Thanks

**Comment by serge-sans-paille** [comment]
wow, that means bad packaging from my side, I'll try to fix this soon, thanks for reporting!

Or... maybe that's an implicit message telling « move to python3 » ?

**Comment by serge-sans-paille** [comment]
@bermanmaxim should be fixed, can you confirm?

**Comment by bermanmaxim** [comment]
Hi Serge, yes it installs the correct version, merci!
