### ISSUE TITLE
boost/python/docstring_options.hpp: No such file or directory

### ISSUE THREAD

**Issue by hainm** [serge-sans-paille/pythran#491]
so I was able to install pythran from source, using the cmake and boost from your channel.

Try pythran and got above error.

```bash
$ pythran/pythran/tests/cases (setuptools_pkgdata) $ pythran ln.py

/tmp/tmpivW9UZ.cpp:3:46: fatal error: boost/python/docstring_options.hpp: No such file or directory
 #include <boost/python/docstring_options.hpp>
                                              ^
compilation terminated.
/tmp/tmpivW9UZ.cpp:3:46: fatal error: boost/python/docstring_options.hpp: No such file or directory
 #include <boost/python/docstring_options.hpp>
                                              ^
compilation terminated.
CRITICAL Cover me Jack. Jack? Jaaaaack!!!!
E: ('error: Command "g++ -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE_GMP -DENABLE_PYTHON_MODULE -I/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/site-packages/pythran-0.7.1-py2.7.egg/pythran -I/mnt/raidc2/haichit/anaconda3/envs/py2/lib/python2.7/site-packages/numpy/core/include -I/mnt/raidc2/haichit/anaconda3/envs/py2/include/python2.7 -c /tmp/tmpivW9UZ.cpp -o /tmp/tmpWdeGqG/tmp/tmpivW9UZ.o -std=c++11 -fno-math-errno -w" failed with exit status 1',)
```

**Comment by hainm** [comment]
by the way? can you add your conda build recipe somewhere so I can have look at it?

**Comment by hainm** [comment]
My boost does exist

`anaconda3/envs/py2/include/boost/python/docstring_options.hpp`

**Comment by hainm** [comment]
ok, problem solved by 
`pythran ln.py -I  /mnt/raidc2/haichit/anaconda3/envs/py2/include/`

I thought pythran would automatically include this as default?

**Comment by serge-sans-paille** [comment]
We never tested pythran integration with anaconda3. I'll add this conda recipe (available here https://github.com/serge-sans-paille/conda-recipes/tree/pythran-support/pythran btw)

**Comment by serge-sans-paille** [comment]
to do so I need to understand : the `envs/py2` directory is something you created or it's a default behavior of anaconda ?

**Comment by hainm** [comment]
>  the envs/py2 directory is something you created or it's a default behavior of anaconda ?

it's created from `conda create -n py2 python=2.7 ....`

**Comment by hainm** [comment]
I think you can use `sys.path` to add the include file.

**Comment by serge-sans-paille** [comment]
On Sun, Oct 11, 2015 at 09:22:54PM -0700, Hai Nguyen wrote:
> ok, problem solved by 
> `pythran ln.py -I  /mnt/raidc2/haichit/anaconda3/envs/py2/include/`
> 
> I thought pythran would automatically include this as default?

I uploaded a new version created with the switch you proposed, if this
still is not enough, you can just add the following lines to your
~/.pythranrc:

[compiler]
include_dirs=/mnt/raidc2/haichit/anaconda3/envs/py2/include/

**Comment by hainm** [comment]
>  uploaded a new version created with the switch you proposed,

work for me now. thanks.
```bash
$ pythran sexy_primes.py
WARNING: Disabling color, you really want to install colorlog.
(py2-pythran)hnguyen@bell ~/programs/pythran/pythran/tests/cases (master) $ ls sexy_primes.so
sexy_primes.so
```

**Comment by serge-sans-paille** [comment]
I'm closing the issue then. PR #499 should make the install easier, no more boost dependencies \o/
