### ISSUE TITLE
Code example in README should use a more common code style

### ISSUE THREAD

**Issue by pkoch** [serge-sans-paille/pythran#501]
Hello!

It took me quite a while to realize the code under the README's "Basic Usage" section was, in fact, Python.

Why is it written in such an esoteric style? Any reason to not make it PEP8 compliant?

Cheers!

**Comment by serge-sans-paille** [comment]
Hi and thanks for the report. there is indeed an indentation issue, but I have the feeling there is more than this. The actual code written in a PEP8 style is:

```
'''
Naive dotproduct! Pythran supports numpy.dot
'''
#pythran export dprod(int list, int list)
def dprod(l0, l1):
    '''
    WoW, generator expression, zip and sum
    '''
    return sum(x * y for x, y in zip(l0, l1))
```

Does that sounds ok to you? Feel free to propose a PR on ``pythran/README.rst`` or discuss it here.

Maybe you though something more numpy-centric would be a better example?

**Comment by pbrunet** [comment]
I think it is about the PEP257 included in the PEP8 (but not checked with
the pep8 command).
It required `"""` to delimitate comment instead of `'''` and for a one
sentence comment, it should be on one line only and finish with a `.`.

Is it what you expected.

```Python
""" Naive dotproduct! Pythran supports numpy.dot. """


#pythran export dprod(int list, int list)
def dprod(l0, l1):
    """ WoW, generator expression, zip and sum. """
    return sum(x * y for x, y in zip(l0, l1))
```


2015-11-16 10:47 GMT+01:00 serge-sans-paille <notifications@github.com>:

**Comment by pkoch** [comment]
It's what pbrunet put here, except the docstrings' contents should not be surrounded by spaces.

Happy to open a PR if you feel it's adequate and we've agreed on what to change to.

**Comment by serge-sans-paille** [comment]
Agreed, let's open a PR :-)

**Comment by pkoch** [comment]
#504 is in. Thanks, guys! :)
