### ISSUE TITLE
support tuple of int as dict keys ?

### ISSUE THREAD

**Issue by LuisBL** [serge-sans-paille/pythran#528]
support tuple of int as dict keys ?

Perhaps I'm not using pythran correctly I describe the issue here: 

http://stackoverflow.com/questions/35240168/pythran-export-dict-with-tuples-as-key

**Comment by serge-sans-paille** [comment]
I answered on stackoverflow, but basically, it seems to me the issue is not related to the tuple of int dict, which works fine.

**Comment by serge-sans-paille** [comment]
#529 improves the error reporting in your case!

**Comment by LuisBL** [comment]
The tuples of int for dict work very well, I fix it with a dedicated ccomplie.py for pythran functions.
