### ISSUE TITLE
import pythran module in a python packages with PythranExtension

### ISSUE THREAD

**Issue by LuisBL** [serge-sans-paille/pythran#530]
With a setup.py like this
    ext_modules=[PythranExtension("ccompile", ["ccompile.py"])],

the `python setup.py install` succed to compile but put the ccompile.so in the site-packages/proj-egg/ directly so we can't import it from the proj package without manualy moving it

Details on  http://stackoverflow.com/q/35248795/3313834

**Comment by LuisBL** [comment]
The projet snipet if that can help.

    proj
    ├── ccompile.py
    ├── Makefile
    ├── proj
    │   ├── __init__.py
    │   └── lib.py
    └── setup.py

[proj.zip](https://github.com/serge-sans-paille/pythran/files/120619/proj.zip)

**Comment by serge-sans-paille** [comment]
This helps a lot. I have a solution that requires the following layout:

```
proj
├── Makefile
├── proj
│   ├── __init__.py
│    ├── ccompile.py
│   └── lib.py
└── setup.py
```

which looks nicer to me. Any thought?

**Comment by LuisBL** [comment]
yes this is the "normal" way to do it, but it does not work with pythran it gave the traceback I expose on  http://stackoverflow.com/q/35248795/3313834

**Comment by LuisBL** [comment]
If on the other hand we keep the same `ext_modules` line in setup.py:

    proj$ grep ccom setup.py
          ext_modules=[PythranExtension("ccompile", ["ccompile.py"])],

With ccompile.py in the proj module:

    (lab)luis@spinoza:~/lab/sandbox/proj$ tree .
    .
    ├── Makefile
    ├── proj
    │   ├── ccompile.py
    │   ├── __init__.py
    │   └── lib.py
    └── setup.py

We get this traceback:

    proj$ python setup.py install
    ccompile.cpp
    Traceback (most recent call last):
      File "setup.py", line 7, in <module>
        ext_modules=[PythranExtension("ccompile", ["ccompile.py"])],
      File "~/venv/local/lib/python2.7/site-packages/pythran/dist.py", line 47, in __init__
        assert os.path.exists(output_file)
    AssertionError
    proj$

**Comment by serge-sans-paille** [comment]
On Sun, Feb 07, 2016 at 03:10:12AM -0800, Luis wrote:
> yes this is the "normal" way to do it, but it does not work with pythran it gave the traceback I expose on  http://stackoverflow.com/q/35248795/3313834

You'll have A PR with the fix soon ;-)

**Comment by LuisBL** [comment]
:)

For the `from distutils.extension import Extension`
The doc is here : https://docs.python.org/2/distutils/examples.html#single-extension-module 
and the code : https://bitbucket.org/pypa/setuptools/src
setuptools/dist.py

Let me know if I can help/test something.

**Comment by serge-sans-paille** [comment]
@LuisBL can you confirm #531 fixes the issue?

**Comment by LuisBL** [comment]
Just tested on a big project
It's working like a charm !
