### ISSUE TITLE
have some way to inform on progression inside a pythran loop.

### ISSUE THREAD

**Issue by LuisBL** [serge-sans-paille/pythran#532]
I have a big/long loop in a pythran function.
I look for a way to print a timestamp info.
If I give a python calculated datetime to the pythran function I will not have the inside loop info.

PS: we have now a pythran tag on stackoverflow ;)

**Comment by serge-sans-paille** [comment]
time.time is supported, is this enough?

> PS: we have now a pythran tag on stackoverflow ;)
great :-)

**Comment by LuisBL** [comment]
yes time.time is enough, we can close this.
BTW where can I found the list of what is covered and what is not covered by pythran ?
e.g. I'm askiing myself if   `from collections import Counter` is supported.

**Comment by serge-sans-paille** [comment]
https://pythonhosted.org/pythran/SUPPORT.html
