### ISSUE TITLE
a way to print an array slice ? 

### ISSUE THREAD

**Issue by LuisBL** [serge-sans-paille/pythran#535]
Today the print **darray[:2,0:15]** above gave a `CRITICAL Cover me Jack. Jack` errror

    # pythran export update_darray(int[][], int[][])
    def update_darray(darray, day_matrix):
        elements = day_matrix.shape[0]
        for i in range(elements):
            darray[day_matrix[i][0]][day_matrix[i][1]] += 1
        print 'darray \n', darray[:2,0:15]
        return darray

Are there a way to print an array slice ?

**Comment by serge-sans-paille** [comment]
It's a bug! I'll check this this evening.

**Comment by serge-sans-paille** [comment]
#536 should fix this!

**Comment by LuisBL** [comment]
that fix the Pb in my case, 
thanks
