### ISSUE TITLE
traceback at compilation time with 3D array

### ISSUE THREAD

**Issue by LuisBL** [serge-sans-paille/pythran#537]
I have this function that merge a 3D array shape [32, 3, 300]::

    $ cat cc.py
    # pythran export merge_results(int[][][])
    def merge_results(shared_res):
        num_game_pairs = {}
        for darray in shared_res:
            for line in darray.T:
                x, y, v = line
                key = (x, y)
                if v == 1:
                    if key in num_game_pairs:
                        num_game_pairs[key] += 1
                    else:
                        num_game_pairs[key] = 1
        return num_game_pairs

When I try to pythran it I get this traceback::

    $ pythran cc.py
    cc.py None None
    /tmp/user/1000/tmpkpzIu1.cpp: In instantiation of ‘typename __pythran_cc::merge_results::type<argument_type0>::result_type __pythran_cc::merge_results::operator()(const argument_type0&) const [with argument_type0 = pythonic::types::ndarray<long int, 3ul>; typename __pythran_cc::merge_results::type<argument_type0>::result_type = pythonic::types::dict<pythonic::types::array<long int, 2ul>, long int>]’:
    /tmp/user/1000/tmpkpzIu1.cpp:98:42:   required from here
    /tmp/user/1000/tmpkpzIu1.cpp:73:228: error: conversion from ‘pythonic::types::numpy_iexpr<const pythonic::types::ndarray<long int, 2ul>&>’ to non-scalar type ‘pythonic::assignable<pythonic::types::numpy_gexpr<const pythonic::types::ndarray<long int, 2ul>&, pythonic::types::contiguous_slice, long int> >::type {aka pythonic::types::numpy_gexpr<const pythonic::types::ndarray<long int, 2ul>&, pythonic::types::contiguous_slice, long int>}’ requested
                 typename pythonic::assignable<typename pythonic::assignable<typename std::remove_cv<typename std::iterator_traits<typename std::remove_reference<__type1>::type::iterator>::value_type>::type>::type>::type __tuple0 = line;

                                          ^
    /tmp/user/1000/tmpkpzIu1.cpp: In instantiation of ‘typename __pythran_cc::merge_results::type<argument_type0>::result_type __pythran_cc::merge_results::operator()(const argument_type0&) const [with argument_type0 = pythonic::types::ndarray<long int, 3ul>; typename __pythran_cc::merge_results::type<argument_type0>::result_type = pythonic::types::dict<pythonic::types::array<long int, 2ul>, long int>]’:
    /tmp/user/1000/tmpkpzIu1.cpp:98:42:   required from here
    /tmp/user/1000/tmpkpzIu1.cpp:73:228: error: conversion from ‘pythonic::types::numpy_iexpr<const pythonic::types::ndarray<long int, 2ul>&>’ to non-scalar type ‘pythonic::assignable<pythonic::types::numpy_gexpr<const pythonic::types::ndarray<long int, 2ul>&, pythonic::types::contiguous_slice, long int> >::type {aka pythonic::types::numpy_gexpr<const pythonic::types::ndarray<long int, 2ul>&, pythonic::types::contiguous_slice, long int>}’ requested
                 typename pythonic::assignable<typename pythonic::assignable<typename std::remove_cv<typename std::iterator_traits<typename std::remove_reference<__type1>::type::iterator>::value_type>::type>::type>::type __tuple0 = line;

                                          ^
    CRITICAL Cover me Jack. Jack? Jaaaaack!!!!
    E: ('error: Command "c++ -pthread -DNDEBUG -g -fwrapv -O2 -Wall -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DUSE_GMP -DENABLE_PYTHON_MODULE -I/home/luis/lab/local/lib/python2.7/site-packages/pythran-0.7.4.post1-py2.7.egg/pythran -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c /tmp/user/1000/tmpkpzIu1.cpp -o /tmp/user/1000/tmpkJ8J_b/tmp/user/1000/tmpkpzIu1.o -std=c++11 -fno-math-errno -w" failed
    with exit status 1',)
    $

I try to modify it like this::

    # pythran export merge_results(int[][][], (int, int):int dict)
    def merge_results(shared_res, num_game_pairs):
        for darray in shared_res:
            for line in darray.T:
                x, y, v = line
                key = (x, y)
                if v == 1:
                    if key in num_game_pairs:
                        num_game_pairs[key] += 1
                    else:
                        num_game_pairs[key] = 1

With no more success ;(

**Comment by serge-sans-paille** [comment]
Thanks for this new report, it's nice to have that many bugs spotted, although that means more PR to review for @pbrunet :-)

**Comment by serge-sans-paille** [comment]
#539 should do the trick, right?

**Comment by LuisBL** [comment]
just tested the fix/normalized-tuple-inefficient branch.
work perfectly for me !

**Comment by serge-sans-paille** [comment]
Closed as #539 is now in master branch
