### ISSUE TITLE
int[:, :, :]: cython style?

### ISSUE THREAD

**Issue by hainm** [serge-sans-paille/pythran#538]
What do you think about adding parsing for cython syntax style?

```python
int[:, :, :] # same as int[][][]
```

IMO, looks prettier.

**Comment by serge-sans-paille** [comment]
You mean for pythran export signature, right? That looks fine to me.

Do you think we should support both syntax or only the more pythonic one
you propose?

**Comment by hainm** [comment]
> You mean for pythran export signature, right? That looks fine to me.

yeah.

> Do you think we should support both syntax or only the more pythonic one
you propose?

if you don't care about breaking backward compatibility, you can choose the cython syntax.
But if there is not too much work, I think it's fine to use both and encourage users to use one over another. (cython website is very clear about this: http://docs.cython.org/src/userguide/memoryviews.html#comparison-to-the-old-buffer-support)

**Comment by pbrunet** [comment]
Just for information. For now, we use int[::][::][::] as a slice syntax for
numpy array. Would it be harder to read the difference between these syntax?

2016-02-18 23:56 GMT+01:00 Hai Nguyen <notifications@github.com>:

**Comment by hainm** [comment]
`int[::][::][::]` seems easier to read than `int[][][]`, but what is the purpose of `::`?

**Comment by serge-sans-paille** [comment]
int [::][::] means we accept strided input, while int [][] does not

**Comment by serge-sans-paille** [comment]
@hainm should be fixed in #542

**Comment by hainm** [comment]
:+1:
