### ISSUE TITLE
trivial case don't work on arch

### ISSUE THREAD

**Issue by louptheron** [serge-sans-paille/pythran#544]
Hi,

I am having issue when importing an .so on archlinux (Linux version 4.3.3-2-ARCH)

I'm on pythran master::

    git log
    commit f8a6d5d72529beb194e092466ff859140340c56a
    Merge: 35cacff 2dc9621
    Author: pbrunet <pierrick.brunet@telecom-bretagne.eu>
    Date:   Sun Feb 21 10:50:00 2016 +0100
    
        Merge pull request #534 from serge-sans-paille/feature/generalized-return-alias
        
        return alias draft support for user functions
    
    commit 35cacff72cff6e23d14e828b73669de159050bb4

With this simple example::

    cat ccompile.py
    """
    Naive dotproduct! Pythran supports numpy.dot
    """
    #pythran export dprod(int list, int list)
    def dprod(l0,l1):
        """WoW, generator expression, zip and sum."""
        return sum(x * y for x, y in zip(l0, l1))
   

Pythran version::

    0.7.4.post1

Import::

    In [2]: from ccompile import dprod
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-2-95f753224c27> in <module>()
    ----> 1 from ccompile import dprod
    
    ImportError: dynamic module does not define module export function
    (PyInit_ccompile)

**Comment by serge-sans-paille** [comment]
Looks like your ipython version uses python3?

**Comment by louptheron** [comment]
After launching ipython with : `python -m IPython`, you are right, it now use the python from my env, thank you !

**Comment by serge-sans-paille** [comment]
note that python3 partial support exist, as mentioned in th doc

http://pythonhosted.org/pythran/MANUAL.html#python3-compatibility
