### ISSUE TITLE
looking for numpy.h in wrong venv place

### ISSUE THREAD

**Issue by LuisBL** [serge-sans-paille/pythran#558]
Hello Pythran team,

I have a strange bug with arrayobject.h

I have not system numpy::

    sudo apt-get remove python-numpy

But a pip install of numpy on my tfox virtualenv

I get this error::

    /home/luis/tfox/local/lib/python2.7/site-packages/pythran-0.7.4.post1-py2.7.egg/pythran/pythonic/include/types/ndarray.hpp:52:31:
    fatal error: numpy/arrayobject.h: Aucun fichier ou dossier de ce type
    compilation terminated.

In my virtualenv numpy include is on venv/local/lib/::

    In [1]: import numpy
    In [2]: numpy.__version__
    Out[2]: '1.11.0'
    In [3]: numpy.get_include()
    Out[3]: '/home/luis/tfox/local/lib/python2.7/site-packages/numpy/core/include'

But the arrayobject.h is in **venv/lib/python2.7** not in venv/local/lib/...

    $ locate arrayobject.h
    /home/luis/tfox/lib/python2.7/site-packages/numpy/core/include/numpy/ndarrayobject.h

**Comment by LuisBL** [comment]
Same error after a numpy reinstall::

    pip uninstall numpy
    pip install numpy

**Comment by serge-sans-paille** [comment]
Can you give us the output of ``pythran -v my_module.py``, to verify if the ``-I`` are correct?

**Comment by LuisBL** [comment]
here::

    $ pythran -v ccompile.py > out.txt
[out.txt](https://github.com/serge-sans-paille/pythran/files/222307/out.txt)

    INFO     customize UnixCCompiler
    INFO     customize UnixCCompiler
    INFO     Generated module: ccompile
    INFO     Output: ~/.../

ccompile.so

**Comment by LuisBL** [comment]
vi pythran it seem to work, the original Error came from:

    python setup.py install

with::

    $ git grep ccom setup.py
    setup.py:      ext_modules=[PythranExtension("oat.ccompile", ["oat/ccompile.py"])],

**Comment by serge-sans-paille** [comment]
oh, right, so that's from PythranExtension... rather strange as it should use the same mechanism. I'll check this next week.

**Comment by LuisBL** [comment]
after a fresh reinstall of a venv everything work well.
I think that the Pb can be reproduce in a very rare case:
- install debian/ubuntu python-numpy
- create a virtualenv with --system-site-packages
- pip install numpy
- apt-get remove --purge python-numpy

I guess that it's a WF rare enought to close this issue.

**Comment by serge-sans-paille** [comment]
I like when problem get solved without a single action on my side :-)
