### ISSUE TITLE
gcc compile fails

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#572]
The following produces gcc compile error (with very long message)
rpm -q gcc
gcc-5.3.1-6.fc23.x86_64

This is fedora 23 x86_64

---

import numpy as np
# pythran export call(complex128[], complex128[], complex128[], complex128[], float[], int, int)

def call (A, y1, y2, y3, ks, M, chunksize):
    sum1s = np.zeros (M, dtype=complex)

```
L = A.shape[0]
zout = np.empty (L-M, dtype=complex)
errs = np.zeros (M, dtype=complex)
for i in range (M//2, L-M//2-1+1):
    z = zout[i-M//2] = y1[i] - np.dot (sum1s, y2[i-(M//2):i+(M//2)+1])

    for j in range (M):
        errs[j] += z * np.conj (y3[i-M//2+j])

    if i % chunksize == chunksize-1:
        for j in range (M):
            sum1s[j] += errs[j] * ks[i-M//2]

        errs[:] = 0

return zout;
```

**Comment by serge-sans-paille** [comment]
Hi @nbecker , welcome back ;-)

I managed to reduce your test case to

```python
import numpy as np
#pythran export call(int)
def call (M):
    errs = np.zeros (M)
    errs[0] = 1
    errs[:] = 0

    return errs
```

I'll keep you in touch

**Comment by serge-sans-paille** [comment]
#573 should fix this

**Comment by serge-sans-paille** [comment]
@nbecker can you confirm the master version fixed this issue?

**Comment by serge-sans-paille** [comment]
No news -> fixed
