### ISSUE TITLE
WARNING  Module : 'np' is imported but not used or can't be imported by Pythran.

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#575]
Lately when I run pythran I get:

 pythran clip3.py
WARNING  Module : 'np' is imported but not used or can't be imported by Pythran.

Should I be concerned?  How can I debug this?

**Comment by serge-sans-paille** [comment]
That's a regression, but it's harmless. So no concern but I have to fix
this.

**Comment by serge-sans-paille** [comment]
#577 fixes the issue. Thanks @pbrunet

**Comment by serge-sans-paille** [comment]
Closed by #577
