### ISSUE TITLE
Symbol not found: OSX

### ISSUE THREAD

**Issue by hainm** [serge-sans-paille/pythran#576]
Hi 

I've just tried pythran on osx (pull newest PR today).

I was able to compile `yin_and_yang.py`test file but got 

``` bash
ImportError: dlopen(./yin_and_yang.so, 2): Symbol not found: __ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE

  Referenced from: ./yin_and_yang.so
  Expected in: flat namespace
 in ./yin_and_yang.so
```

**Comment by hainm** [comment]
using otool

```bash
$ otool -L ./yin_and_yang.so 
./yin_and_yang.so:
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/lib/gcc/6/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

```
$ cat ~/.pythranrc 
[compiler]
CXX=/usr/local/bin/g++-6
CC=/usr/local/bin/gcc-6
```

In my mac, default in /usr/bin/gcc is actually `clang`

**Comment by serge-sans-paille** [comment]
The demangled version of the missing symmbol is actually

    _VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >

looks like you're linking with the wrong libstdc++. Could your try to
link with the one shipped with the compiler you're using in /usr/local ?

**Comment by hainm** [comment]
hi, I will report later. thanks.

**Comment by hainm** [comment]
I just want to say I still on hold this issue. Will report later. :D

**Comment by serge-sans-paille** [comment]
ok, it won't go in next release :-)

**Comment by hainm** [comment]
> looks like you're linking with the wrong libstdc++

yeah. I have not tried with `pythran` yet but I got similiar errors with my projects and it's indeed because of mixing stuff between `g++` , 'clang' and 'libstc++'

mac is evil. close now.

**Comment by btickell** [comment]
Hi, how did you resolve this issue? @hainm

**Comment by hainm** [comment]
hi @btickell this was almost 3 years ago and I can not recall it. 
May be try this suggestion: https://github.com/serge-sans-paille/pythran/issues/576#issuecomment-223742732?
