### ISSUE TITLE
build pythran on fedora 24 (gcc-6.1.1)

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#583]
Didn't get far:

Trying to compile GMP dependencies.
cc -c /tmp/tmpdgxejxv0.cpp -o tmp/tmpdgxejxv0.o
cc tmp/tmpdgxejxv0.o -lgmp -lgmpxx -o a.out
/usr/bin/ld: tmp/tmpdgxejxv0.o: undefined reference to symbol '__gxx_personality_v0@@CXXABI_1.3'
/usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Failed to compile GMP source, disabling long support.

**Comment by nbecker** [comment]
cc -o a.out test_gmp.o -lgmp -lgmpxx
doesn't work, but:

g++ -o a.out test_gmp.o -lgmp -lgmpxx
does work

**Comment by serge-sans-paille** [comment]
what does your pythranrc / CC CXX env var look like?

**Comment by nbecker** [comment]
I don't think these are used for setup.py GMP test

**Comment by serge-sans-paille** [comment]
@nbecker I wonder if #584 fixes the issue?

**Comment by serge-sans-paille** [comment]
@nbecker issue fiex in #584
