### ISSUE TITLE
conversion failed

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#594]
Did the type of z get inferred to be ndarray<std::complex<double>>, where it should have been 
std::complex<double>?

``
 pythran lms_1st_multi2.py
/tmp/tmpg5pi9573.cpp: In instantiation of ‘typename __pythran_lms_1st_multi2::lms_1st_multi::type<argument_type0, argument_type1, argument_type2, argument_type3, argument_type4>::result_type __pythran_lms_1st_multi2::lms_1st_multi::operator()(argument_type0&&, const argument_type1&, const argument_type2&, const argument_type3&, const argument_type4&) const [with argument_type0 = pythonic::types::ndarray<std::complex<double>, 2ul>&; argument_type1 = pythonic::types::ndarray<std::complex<double>, 1ul>; argument_type2 = pythonic::types::ndarray<std::complex<double>, 2ul>; argument_type3 = pythonic::types::ndarray<double, 1ul>; argument_type4 = long int; typename __pythran_lms_1st_multi2::lms_1st_multi::type<argument_type0, argument_type1, argument_type2, argument_type3, argument_type4>::result_type = pythonic::types::ndarray<std::complex<double>, 1ul>]’:
/tmp/tmpg5pi9573.cpp:233:70:   required from here
/tmp/tmpg5pi9573.cpp:162:101: error: conversion from ‘pythonic::types::type_helper<const pythonic::types::ndarray<std::complex<double>, 1ul>&>::type {aka std::complex<double>}’ to non-scalar type ‘pythonic::assignable<pythonic::types::numpy_expr<pythonic::operator_::functor::add, pythonic::types::broadcast<std::complex<double>, std::complex<double> >, pythonic::types::ndarray<std::complex<double>, 1ul> > >::type {aka pythonic::types::ndarray<std::complex<double>, 1ul>}’ requested
           typename pythonic::assignable<typename __combined<__type24,__type43>::type>::type z = y1[i];
                                                                                                     ^
``

``
import numpy as np

#pythran export lms_1st_multi (complex[:,:], complex[:], complex[:,:], float[:], int)
def lms_1st_multi (alphas, y1, inputs, ks, chunksize):
    L = y1.shape[0]
    M = alphas.shape[1]
    n_inputs = inputs.shape[0]
    zout = np.empty (L-M, dtype=complex)
    errs = np.empty ((n_inputs, M), dtype=complex)
    #errs[nd::view()()] = 0

    for i in range (M/2, L-M/2-1+1):
        z = y1[i]
        for inp in range (n_inputs):
            z -= np.dot (alphas[inp,:], inputs[inp, i-M/2,i+M/2+1])

        for inp in range (n_inputs):
            for j in range (M):
                w = inputs[inp,i-M/2+j]
                errs[inp,j] += z * w.conjugate()

        if i % chunksize == chunksize - 1:
            try:
                k = ks[i/chunksize]
            except:
                k = ks

            for inp in range (n_inputs):
                for j in range (M):
                    alphas[inp,j] += errs[inp,j] * k
                errs[inp,j] = 0

        zout[i-M/2] = z

    return zout

``

**Comment by nbecker** [comment]
Sorry, here is the correctly formatted code

```python
import numpy as np

#pythran export lms_1st_multi (complex[:,:], complex[:], complex[:,:], float[:], int)
def lms_1st_multi (alphas, y1, inputs, ks, chunksize):
    L = y1.shape[0]
    M = alphas.shape[1]
    n_inputs = inputs.shape[0]
    zout = np.empty (L-M, dtype=complex)
    errs = np.empty ((n_inputs, M), dtype=complex)
   
    for i in range (M/2, L-M/2-1+1):
        z = y1[i]
        for inp in range (n_inputs):
            z -= np.dot (alphas[inp,:], inputs[inp, i-M/2,i+M/2+1])

        for inp in range (n_inputs):
            for j in range (M):
                w = inputs[inp,i-M/2+j]
                errs[inp,j] += z * w.conjugate()

        if i % chunksize == chunksize - 1:
            try:
                k = ks[i/chunksize]
            except:
                k = ks

            for inp in range (n_inputs):
                for j in range (M):
                    alphas[inp,j] += errs[inp,j] * k
                errs[inp,j] = 0

        zout[i-M/2] = z


    return zout
```

**Comment by nbecker** [comment]
BTW, the original code would have passed either a double or double[:] as ks argument, and I would use hasattr (ks, 'size') instead of the try/except.  I don't know anyway to do this with pythran

**Comment by serge-sans-paille** [comment]
On Thu, Jul 21, 2016 at 07:26:24AM -0700, ndbecker wrote:
> BTW, the original code would have passed either a double or double[:] as ks argument, and I would use hasattr (ks, 'size') instead of the try/except.  I don't know anyway to do this with pythran
> 

That's actually the issue with your code. Pythran will not raise an
exception because of the bad typing, and fail un-gracefully. There's no
easy way to make this code polymorphic in current pythran state, but
that's typically something we should be able to handle with some more
care. Not on the roadmap though...

The only way to deal with this is to give the two functions different
names and duplicate the code, which is not as nice as it should be (or
to use a lambda to avoid the code duplication). there seems to be
another issue with your code though, I'll check this.

**Comment by nbecker** [comment]
Yes, take out the try/except keeping the 1st clause, same compile error

**Comment by serge-sans-paille** [comment]
@nbecker your code seems to be incorrect: ``inputs`` is typed as ``complex[:,:]`` but indexed as ``np.dot (alphas[inp,:], inputs[inp, i-M/2,i+M/2+1])``....

**Comment by nbecker** [comment]
Yes, sorry - there was a typo.  Should say inputs[inp, i-M//2:i+M//2+1]

**Comment by serge-sans-paille** [comment]
On Fri, Jul 22, 2016 at 05:08:01AM -0700, ndbecker wrote:
> Yes, sorry - there was a typo.  Should say inputs[inp, i-M//2:i+M//2+1]

Then the following is the best i can do in current pythran state:


    #pythran export lms_1st_multi_0 (complex[:,:], complex[:], complex[:,:], float[:], int)
    #pythran export lms_1st_multi_1 (complex[:,:], complex[:], complex[:,:], float, int)
    import numpy as np

    def lms_1st_multi_0 (alphas, y1, inputs, ks, chunksize):
        return  _lms_1st_multi (alphas, y1, inputs, ks, chunksize, lambda x, y: x[y])

    def lms_1st_multi_1 (alphas, y1, inputs, ks, chunksize):
        return  _lms_1st_multi (alphas, y1, inputs, ks, chunksize, lambda x, y: x)

    def _lms_1st_multi (alphas, y1, inputs, ks, chunksize, access):
        L = y1.shape[0]
        M = alphas.shape[1]
        n_inputs = inputs.shape[0]
        zout = np.empty (L-M, dtype=complex)
        errs = np.empty ((n_inputs, M), dtype=complex)

        for i in range (M/2, L-M/2-1+1):
            z = y1[i]
            for inp in range (n_inputs):
                z -= np.dot (alphas[inp,:], inputs[inp, i-M/2:i+M/2+1])

            for inp in range (n_inputs):
                for j in range (M):
                    w = inputs[inp,i-M/2+j]
                    errs[inp,j] += z * w.conjugate()

            if i % chunksize == chunksize - 1:
                k = access(ks, i/chunksize)

                for inp in range (n_inputs):
                    for j in range (M):
                        alphas[inp,j] += errs[inp,j] * k
                    errs[inp,j] = 0

            zout[i-M/2] = z


        return zout

:-/
