### ISSUE TITLE
Releasing the GIL

### ISSUE THREAD

**Issue by funnydevnull** [serge-sans-paille/pythran#621]
It is sometime desirable to perform many small BLAS-style operations (vector addition, etc...) that are too small to effectively parallelize (in the underlying BLAS library).  In this case the best speedup is attained by simply running several such operations in parallel.  A very relevant example of this is the significant performance improvements attained by the cythonized version of word2vec in gensim:

https://rare-technologies.com/parallelizing-word2vec-in-python/

I would like to do something similar with pythran but unfortunately, because it does not unlock the GIL, I cannot.  An important constraint here is that there is often a (large) matrix (the weight matrices) that needs to be shared by the threads so multi-processing is not an effective solution.

I'm attaching a notebook that demonstrates the issue.  I specifically wrote it to mimic (one variant) of the word2vec cythonized code from the link above.  I test the code in both single and multi-threaded mode in pure python and pythran and in both cases there is no speedup from multi-threading (because of the GIL).

So my request is to ask if its possible to modify pythran to release the GIL (Serge has already told me the answer should be yes and asked me to post here).

On a sidenote its interesting to compare the pythran vs cython code.  In single threaded mode the (highly optimized) cython code in gensim achieves a rate of 650k words/s while my much simpler looking pythran version gets to ~425k words/s.  I think this is a very strong showing considering how much the cython code has been optimized and how much more readable (and editable) the pythran code is.  Its also not a fair comparison because the timing for the Cython code actually includes additional preprocessing that works against it (but I think this takes very little time).  It might be interesting to figure out if there's some way to get the pythran code closer to the cython timing (note the cython code uses direct C calls to blas libraries).

[pythran_multi-threading_test.ipynb.zip](https://github.com/serge-sans-paille/pythran/files/610081/pythran_multi-threading_test.ipynb.zip)

**Comment by serge-sans-paille** [comment]
I've made some preliminary tests, and it seems possible *and* easy to integrate into current compilation flow , hurray!

I'll have a look to your benchmark later, maybe there's room for improvement in pythran there :-)

**Comment by serge-sans-paille** [comment]
Implemented in #623

**Comment by serge-sans-paille** [comment]
Closed via #623
