### ISSUE TITLE
version in master vs pypi

### ISSUE THREAD

**Issue by baoboa** [serge-sans-paille/pythran#633]
if i build with the tarball from pypi site 

```bash
 wget https://pypi.python.org/packages/4d/43/33ab1c181cc24e3dcc98e017e3281a19e6c789557b86c348e90acc8826e8/pythran-0.8.0.tar.gz#md5=33bb9e7d2580550924250221230e717f
 tar xvf pythran-0.8.0.tar.gz
 cd pythran-0.8.0/
 python setup.py build
 python setup.py test
```

i got that  => collected 0 items / no test 

If i clone the master i got a proper testing
- Is it a change done after the release 0.8, there is no release/or tag in the github repo ;( , hard to say 
- Or the archive in pypi doesn't contain any test ?  

thanks for pythran anyway

**Comment by serge-sans-paille** [comment]
Hi @baoboa There's indeed no tag in the github repo :-/ There's a commit named after the python version though (that's 6428e526ec414cc79a1d2b7399137aa5e1656a2a) , but that's clearly not enough, I'll improve on this next time!

The pypi archive never contained the tests.

**Comment by baoboa** [comment]
ok, merci pour l'info
