### ISSUE TITLE
Dot performance issues?

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#637]
I'm trying to use pythran for my code, and fall on performance issue with the dot operation.

I takes less than 20 seconds with python on my machine ... take more than 1 minutes with pythran (i killed the process...)

Here the example

https://gist.github.com/diorcety/54073473c7df332299bdaec34c4a74c6

**Comment by serge-sans-paille** [comment]
Hi there,

I can reproduce the issue, that's related to the handling of global variables.

And I have a fix, I just need to test and push it :-)

**Comment by diorcety** [comment]
Thanks !

**Comment by serge-sans-paille** [comment]
Just to be sure: the problem lies in the **compilation time** which is too long, not the runtime, that is still below python's if you're patient enough to compile the program ?

**Comment by diorcety** [comment]
Yes the compilation time is huge, but it was not main issue. It seems that I have issue with libblas and cblas with dot operation(bad performances at runtime). I have good performances with openblas on this simple case but not my full computation function (i have a sec fault). I will try to have a simple test case showing this issue.

**Comment by serge-sans-paille** [comment]
oh right. I started to improve the compilation time due to your Issue :-) But that's not lost anyway.

Have a look to #636, this may fix your problem?

**Comment by diorcety** [comment]
Yes i already took that branch. Bad performances with blas and segfault with openblas.(on the complete function not this simple example)

**Comment by serge-sans-paille** [comment]
I'd be happy to have the whole function, as with the simple gist you posted I don't have any issue (no segfault, and no slowdown, actually a x2 speedup)

**Comment by diorcety** [comment]
I try to understand the segfault... 
python test.py         
Reconstructing ...
[1]    11413 segmentation fault  python test.py
python test.py
Reconstructing ...
[1]    11449 segmentation fault  python test.py
python test.py
Reconstructing ...
[1]    11485 segmentation fault  python test.py
python test.py
Reconstructing ...
Compute ...

A valgrind report could be enough?

**Comment by diorcety** [comment]
Hum i maybe understand the issue

https://software.intel.com/en-us/node/529735


m, n, k

    Integers indicating the size of the matrices:

        A: m rows by k columns

        B: k rows by n columns

        C: m rows by n columns

line 228 of dot.hpp:
int m = b.shape()[1], n = a.shape()[0], k = b.shape()[0];


shouldn't be int n = b.shape()[1], m = a.shape()[0], k = b.shape()[0]; ?
Any way by changing this line i have no crash anymore.

**Comment by diorcety** [comment]
I will keep you updated but I had 9,4 s with python and now i have 14,90 .. With my CPU monitor I see that pythran by default only use 1 core with python the 4 of my VM. Is it a normal behaviour?
