### ISSUE TITLE
dot operation on transpose will create an extra array allocation

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#640]
This operation :
np.dot(a.T, a)

will create a temp an extra array which can lead to performance issues if done inside a loop.

**Comment by serge-sans-paille** [comment]
Should be fiex by #642, can you confirm?

**Comment by diorcety** [comment]
Indeed no more allocation but now it takes ages here... maybe it's normal
void pythonic::utils::_broadcast_copy<pythonic::types::novectorizer, 1ul, 0ul>::operator()<pythonic::types::numpy_iexpr<pythonic::types::ndarray<double, 2ul> const&>&, pythonic::types::numpy_gexpr<pythonic::types::ndarray<double, 2ul> const&, pythonic::types::contiguous_slice, long> >(pythonic::types::numpy_iexpr<pythonic::types::ndarray<double, 2ul> const&>&, pythonic::types::numpy_gexpr<pythonic::types::ndarray<double, 2ul> const&, pythonic::types::contiguous_slice, long> const&)

**Comment by serge-sans-paille** [comment]
@diorcety I ran a few benchmarks, namely:

```
#pythran export mm(float[][], float[][])
#pythran export mt(float[][], float[][])
#pythran export tm(float[][], float[][])
#pythran export tt(float[][], float[][])
import numpy as np
def mm(A, B):
    return np.dot(A, B)
def mt(A, B):
    return np.dot(A, B.T)
def tm(A, B):
    return np.dot(A.T, B)
def tt(A, B):
    return np.dot(A.T, B.T)
```

and I get similar timings with or without pythran when I multiply two ``2500, 2500`` matrices in the various transpose configuration. Can you elaborate on your performance issue?

**Comment by serge-sans-paille** [comment]
@diorcety I merged the PR as it fixes the direct issue, feel free to provide more feedback on other perf issues here.
