### ISSUE TITLE
adding annotation in separate file? 

### ISSUE THREAD

**Issue by hainm** [serge-sans-paille/pythran#644]
Hi, may be do that in the future?

There are too many "# pythran export" in source code.

so, just

```bash
# my.py
import numpy as np
def mm(A, B):
    return np.dot(A, B)
def mt(A, B):
    return np.dot(A, B.T)
def tm(A, B):
    return np.dot(A.T, B)
def tt(A, B):
    return np.dot(A.T, B.T)
```

```python
# my.pythran
mm(float[][], float[][])
mt(float[][], float[][])
tm(float[][], float[][])
tt(float[][], float[][])
```

Example was taken from: https://github.com/serge-sans-paille/pythran/issues/640#issuecomment-284969965

**Comment by serge-sans-paille** [comment]
I like the idea, @pbrunet , @diorcety what's your opinion on this

**Comment by diorcety** [comment]
👍  I would need a pythranrc by project

**Comment by serge-sans-paille** [comment]
@diorcety an option to specify the config file path would do the trick, right?

**Comment by diorcety** [comment]
maybe more a ${CWD}/.pythonrc which overload the ${HOME}/.pythonrc
which allows to have project specific settings.
then adding to it the #pythran export ?

**Comment by hainm** [comment]
might be a good idea to look at [python typeshed](https://github.com/python/typeshed)

**Comment by pbrunet** [comment]
I agree with @diorcety that we should look in parent path too. 
Or maybe like for clang-format, which look in parent directory until it find a .pythranrc?

But I think there are two differents problem here.

The pythranrc which is related to the project/directory and signatures which are related to a file except if you want a pythranrc per file but it looks to much for me.

Also, having all the signature in a single file for a full directory looks to be prone to name clashing and hard to update list but may be it is usable for smaller folders?

**Comment by serge-sans-paille** [comment]
@diorcety pythranrc contains informlation about linkage etc and information about compile flags, compilers to use etc. These informations are mostly dependent of the running system, so I would find it strange to have them in a git repo, for instance.

@hainm to what extent is it relevant to this thread?

**Comment by hainm** [comment]
ah, the idea from my 1st post came from that typeshed.

**Comment by diorcety** [comment]
Maybe simply a pythran file next to py file containing pythran directives(without #)? 
like
example.py
example.pythran

pythran will try to look look for the pythran file and include directives?

**Comment by hainm** [comment]
Yeah, this is what I meant.

Hai

**Comment by diorcety** [comment]
I have a proto/PR of implementation  if needed

**Comment by serge-sans-paille** [comment]
@diorcety you can create a PR and I'll review it :-)

**Comment by serge-sans-paille** [comment]
@hainm @diorcety does #656 fix your issue?

**Comment by hainm** [comment]
awesome. thanks.
