### ISSUE TITLE
NoneType implicit conversion

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#648]
There is issue with NoneType<double, true> conversion. For exemple put a variable of this type un the log10 function. There is ambigous error. I suspect the double() long() long long() to be ambigous choices. Souldn't be a T() operator instead of all the others (and me be wrong) operaror? It seems to solve this issue but to create other ones where one of this operator is used for implicit conversion

**Comment by serge-sans-paille** [comment]
Should be fixed by #939, can you confirm?
