### ISSUE TITLE
gmp functions

### ISSUE THREAD

**Issue by pbrunet** [serge-sans-paille/pythran#68]
Some function doesn't work with gmp:
sum
min max
map
xrange et range 
print list
chr
bin
cmp
all
any
hex
oct
pow
round
functions in module math
and may be some others.

It leads to Fail in test for 32bits architecture as pow(15,18) doesn't exist in a 32bits architecture.

**Comment by serge-sans-paille** [comment]
has of #972, I'll be closing that issue as won't fix :-/
