### ISSUE TITLE
Complains about missing BLAS, but lib is installed and a functional .so is generated

### ISSUE THREAD

**Issue by CedricDViou** [serge-sans-paille/pythran#694]
~/nancay/admin/Formation/20170704_Python_avancé/pythran$ pythran collatz.py
WARNING: Disabling color, you really want to install colorlog.
/usr/bin/ld : ne peut trouver -lcblas
collect2: error: ld returned 1 exit status
/usr/bin/ldÂ : ne peut trouver -lcblas
collect2: error: ld returned 1 exit status

But BLAS is installed:
~/nancay/admin/Formation/20170704_Python_avancé/pythran$ sudo apt-get install libgmp-dev libblas-dev
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
libblas-dev is already the newest version (3.6.0-2ubuntu2).
libgmp-dev is already the newest version (2:6.1.0+dfsg-2).

And the .so is produced
~/nancay/admin/Formation/20170704_Python_avancé/pythran$ ls
-rw-rw-r-- 1 cedric cedric   932 juil.  5 12:29 collatz.py
-rwxrwxr-x 1 cedric cedric 14952 juil.  5 12:35 collatz.so*

Thanks for this powerfull tool anyway.

**Comment by serge-sans-paille** [comment]
I tried to fix this in master, can you check?

**Comment by CedricDViou** [comment]
It seems corrected.
No error about missing libs and the .so is functional.

Thanks for the fix.
