### ISSUE TITLE
Vectorization not implemented yet on 2D numpy array broadcasting

### ISSUE THREAD

**Issue by flothesof** [serge-sans-paille/pythran#697]
Hi @serge-sans-paille,

Thanks for your work on pythran. 
As discussed with you in class, when implementing a 2D convolution, the code generated by pythran is not vectorized, although it could be. Minimum working example:
```python
#file convolve.py
#pythran export convolve_mean2_pythran(float[][])
import numpy as np
def convolve_mean2_pythran(image):
    height, width = image.shape
    return 0.25*(image[:-2,:]+image [2:,:]+image[1:-1,:]+image[1:-1,:])
```
We compile with:
`pythran -g -DUSE_BOOST_SIMD convolve.py -march=native -O0`

And run this:
`python -c "import numpy as np; x=np.empty((20, 20)); import convolve; convolve.convolve_mean2_pythran(x)"`

By inspecting the generated code with you, we ended up here in the file **numpy_iexpr.hpp**:

```c++
template <class Arg>
    numpy_iexpr<Arg> &numpy_iexpr<Arg>::operator=(numpy_iexpr<Arg> const &expr)
    {
      assert(buffer);
      return utils::broadcast_copy<numpy_iexpr &, numpy_iexpr const &, value,
                                   value - utils::dim_of<numpy_iexpr>::value,
                                   false /*NIY*/>(*this, expr);
    }
```

Hope you can get it to work! 

Best,
Florian

**Comment by serge-sans-paille** [comment]
Fixed in ced2aeca77200a11067744c05fe563ca8c6d0ce1, with extra speedup if you have AVX enabled!
