### ISSUE TITLE
Precision issue

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#708]
Taking the following code:
```
#pythran export c(int)
def c(N):
    i = 2
    p = 0.0000001 * 1.0
 
    binomial_coef = 1. * factorial(N) / factorial(i) / factorial(N-i)
    pp = binomial_coef * p**i * (1-p)**(N-i)
    return pp
```

calling with print("%.32f" % (diff.c(3**2)))
With python: 0.00000000000035999974800007563044
With pythran: 0.00000000000035999974800007568093

**Comment by diorcety** [comment]
Seems to come from this part (1-p)**(N-i)

**Comment by diorcety** [comment]
The issue come from here: https://github.com/serge-sans-paille/pythran/blob/master/pythran/pythonic/include/numpy/power.hpp#L24

If i force the type of (N-i) to float, i have the same result:
`pp = binomial_coef * p**i * (1-p)**float(N-i)`

**Comment by serge-sans-paille** [comment]
On Tue, Aug 29, 2017 at 06:59:45AM +0000, Diorcet Yann wrote:
> The issue come from here: https://github.com/serge-sans-paille/pythran/blob/master/pythran/pythonic/include/numpy/power.hpp#L24
> 
> If i force the type of (N-i) to float, i have the same result:
> `pp = binomial_coef * p**i * (1-p)**float(N-i)`

OK! Feel free to propose a patch! (maybe double instead of float
though?)

**Comment by diorcety** [comment]
boost::smd seems to cause the issue
