### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#720]
I encounter a problem which seems to be related to memory when I use this function

```
# pythran export myfunc(float64[][])

def myfunc(field):
    return 2*field, 1
```

with this code:

```
import numpy as np
a = np.ones((1024,)*2, dtype=np.float64)

for i in range(2000):
    myfunc(a)
```

The memory consumption increases a lot and the process is stopped by the kernel with a nice explanation:

"Killed"

pythran --version
0.8.2

Same thing with python 2.7, 3.5 and 3.6.

**Comment by serge-sans-paille** [comment]
@paugier can you confirm #721 fixes your issue?

**Comment by paugier** [comment]
I do confirm that #721 fixes the memory leak for my case!

**Comment by serge-sans-paille** [comment]
Thanks for reporting! This did help a lot.
