### ISSUE TITLE
networkx 2.0 deprecated syntax

### ISSUE THREAD

**Issue by ashwinvis** [serge-sans-paille/pythran#722]
I found [one deprecated statement](https://github.com/serge-sans-paille/pythran/blob/8f1bdb8dd64dc1ffd01fbdcebf3774adfff25826/pythran/transformations/false_polymorphism.py#L37) in the `pythran` source, there may be more! [See here for networkx migration guide](https://github.com/networkx/networkx/blob/bbd84d051b4a7266ae66ad3c413a1d7c78b95482/doc/release/migration_guide_from_1.x_to_2.0.rst#migration-guide-from-1x-to-20) which mentions `Digraph.nodes_iter` method has been removed.

I don't know if it is possible to support both APIs. If not, either `networkx>=1.5, <2.0` or `networkx>=2.0` should be set in `requirements.txt`.

**Comment by serge-sans-paille** [comment]
I'll go for the networkx>=2.0, but this requires some other changes.

**Comment by serge-sans-paille** [comment]
Fixed in 37e78bb

**Comment by boileaum** [comment]
Could you please publish the fixed version on PyPI?  Thanks!

**Comment by serge-sans-paille** [comment]
On Fri, Oct 13, 2017 at 07:25:29AM -0700, Matthieu Boileau wrote:
> Could you please publish the fixed version on PyPI?  Thanks!

Will do this weekend!
