### ISSUE TITLE
Support for LowLevelCallable

### ISSUE THREAD

**Issue by maartenbreddels** [serge-sans-paille/pythran#732]
If Pythran could have support for
https://docs.scipy.org/doc/scipy/reference/generated/scipy.LowLevelCallable.html
we can pass it to scipy.integrate.quad etc

**Comment by serge-sans-paille** [comment]
I've played a bit with the idea, I wonder which interface would be the best? I'd like to do

```python
from compiled_module import foo
native = LowLevelCallable(foo.native, "double(double)")
integrate.quad(native, 0, 4)
```

but foo is not a regular PyObject, it's a PyCFunction so it cannot receive any extra attribute.

An alternative would be
```python
from compiled_module import foo, __native__
native = LowLevelCallable(__native__['foo'], "double(double)")
integrate.quad(native, 0, 4)
```

but then, what if foo is an overloaded function, like in

```
#pythran export foo(double)
#pythran export foo(double, double)
def foo(x, y = 1): return x + y
```

Maybe in that cas ``__native__['foo']`` should be a tuple? a dict indexed by the type?

**Comment by maartenbreddels** [comment]
Since the signature is a part of LowLevelCallable argument, maybe it's best to index by that?
```python
from bla import foo, __capsules__
signature = 'double(double)'
native = LowLevelCallable(__capsules__['foo'][signature], signature)
integrate.quad(native, 0, 4)
```

**Comment by serge-sans-paille** [comment]
The problem is that there is no easy, compiler-indpendenat way to retreive the result type of a compiled function in pythran. What about the following:
```python
from bla import foo, __capsules__
signature = 'double(double)'
native = LowLevelCallable(__capsules__['foo(double)'], signature)
integrate.quad(native, 0, 4)
```

that would solve all my issues, at the expenses of requiring the user to provide the signature.

**Comment by maartenbreddels** [comment]
I'd say quite confusing having two 'signatures'. So in the above example of:
```python
#pythran export foo(double)
#pythran export foo(double, double)
def foo(x, y = 1): return x + y
```
You let the compiler work out what the return value type is using auto? Could you maybe force this.. ?
```python
#pythran export foo(double) -> double
#pythran export foo(double, double) -> double
def foo(x, y = 1): return x + y
```
So it's optional, and only this way it will export to __capsule__ with the signatures?

**Comment by serge-sans-paille** [comment]
For the record:

```
22:26 < serge-sans-paille> maartenbreddels: concerning the pycapsule, I think I'm going to export the raw signature -> native ptr dict. This will be more open for later use than the scipy special case.
[...]
11:32 < maartenbreddels> @serge-sans-paille sound like a good compromised, there is more in the world than scipy
```

**Comment by serge-sans-paille** [comment]
@maartenbreddels #737 implements a capsule-compatible solution.

**Comment by serge-sans-paille** [comment]
I finally came up with another solution. one could specify that some function needs to be exported as native function pointer instead of nortmal python function. Something like

```
#pythran native export foo(int*, int)

def foo(x, y): return x[0] + y
```

that would suppress the need for ``natives__`` and allow ``double*`` type only for native signatures.

**Comment by serge-sans-paille** [comment]
Implemnted in #737
