### ISSUE TITLE
Conda recipe for OSX

### ISSUE THREAD

**Issue by alexbw** [serge-sans-paille/pythran#747]
If you point me to the conda recipe, I can build it myself. If I have some time, I can also put it up on conda-forge, which will build for both Linux and OSX continuously.

**Comment by serge-sans-paille** [comment]
I'm using that: https://gist.github.com/serge-sans-paille/f89a0a4b4da41dbebf898981ba97bc2d

Note that because conda used to ship an old version of gcc, I have my own in my channel. Note sur you need that for osx

**Comment by alexbw** [comment]
Hey Serge, I don't have any bandwidth right now to help with this, apologies.

**Comment by serge-sans-paille** [comment]
Closed by #907 \o/
