### ISSUE TITLE
Performance issue numpy.random

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#759]
On my computer, Pythran is slightly slower than numpy for generation of random numbers.

For example, 

```
# pythran export rand2d(int)

def rand2d(n):
    return rand(n, n)

for n in [100, 1000, 2000, 4000, 10000]:
    %timeit np.random.rand(n, n)
111 µs ± 129 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
11 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
44.3 ms ± 1.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
194 ms ± 8.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.22 s ± 55.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

for n in [100, 1000, 2000, 4000, 10000]:
    %timeit rand2d(n)
127 µs ± 2.72 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
12.6 ms ± 56.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
50.2 ms ± 286 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
210 ms ± 1.42 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.38 s ± 62.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
The difference is small but already numpy is not known to be very efficient in generating random numbers (see https://github.com/lemire/fastrand and https://software.intel.com/en-us/blogs/2016/06/15/faster-random-number-generation-in-intel-distribution-for-python). Indeed, the equivalent julia functions are for me much faster by a factor ~10 even though it only uses one core!

Remark: with the option -march=native, pythran and numpy have approximately the same performance.

**Comment by serge-sans-paille** [comment]
> Remark: with the option -march=native, pythran and numpy have approximately the same performance.
Then this looks ok to me, right? I'm not versed into PRNG, but at least I understand I need to be carefull when dealing with that topic. Pythran uses the samed PRNG as numpy, with the same values :-)

One alternative would be to use a vectorized version, generically written with boost.simd. But I need to think more about that first.

**Comment by paugier** [comment]
I close this old issue since Pythran has now a faster random number generator. See issue #1111 and PR #1118
