### ISSUE TITLE
concatenate with axis argument + numpy.linalg.matrix_power

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#761]
Dear Pythran dev,

Another function from the Julia benchmark that Pythran can not yet compile.

```python 

import numpy as np

from numpy import trace, concatenate
from numpy.random import randn
from numpy.linalg import matrix_power

# pythran export rand_mat_stat(int)

def rand_mat_stat(t):
    n = 5
    v = np.empty(t)
    w = np.empty(t)
    for i in range(t):
        a = randn(n, n)
        b = randn(n, n)
        c = randn(n, n)
        d = randn(n, n)
        P = concatenate((a, b, c, d), axis=1)
        Q = concatenate((concatenate((a, b), axis=1),
                         concatenate((c, d), axis=1)), axis=0)
        v[i] = trace(matrix_power(P.T @ P, 4))
        w[i] = trace(matrix_power(Q.T @ Q, 4))
    return np.std(v)/np.mean(v), np.std(w)/np.mean(w)
```

[only_rand_mat_stat.py.txt](https://github.com/serge-sans-paille/pythran/files/1608127/only_rand_mat_stat.py.txt)

We would need:

- the axis argument of the function concatenate
- numpy.linalg.matrix_power

- as a bonus, the python >= 3.5 syntaxic sugar `a @ b` equivalent to `np.dot(a, b)`.
- to be really fast: randn ~ as fast as the Julia randn function...

**Comment by serge-sans-paille** [comment]
All fixed in#767, or so I hope :-)

**Comment by paugier** [comment]
Great! The three first bullets works fine and we get similar or better perf than Julia on these types of benchmarks.

However, Julia's benchmarks bench a lot the rand functions and Pythran and Numpy are really slower than Julia on the rand functions (see [issues/759](https://github.com/serge-sans-paille/pythran/issues/759)).

**Comment by serge-sans-paille** [comment]
Which randomnumber generator is julia using? Can you point me to their
implementation,

Comparing different generators does not make sense...

**Comment by paugier** [comment]
Yes it seems that Julia uses the [Mersenne Twister library](http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/SFMT/#dSFMT) (https://docs.julialang.org/en/latest/stdlib/Random/).

**Comment by serge-sans-paille** [comment]
good, closing the issue as the original problem is solved
