### ISSUE TITLE
Differences with Numpy on reduction on bools

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#780]
Consider `a = np.random.randint(0, 4, (100, 100), dtype=np.int8)` and:

```
# pythran export greater(int8[:, :])
def greater(a):
    return np.sum(a > 0.5)

# pythran export greater_axis(int8[:, :])
def greater_axis(a):
    return np.sum(a > 0.5, axis=1)
```

The first function works in both Pythran and Numpy and yields identical results, the number of elements over 0.5. The second returns an array of bools on Pythran. Explicitely casting recovers Numpy's behaviour.

```
# pythran export greater_axis_fix(int8[:, :])
def greater_axis_fix(a):
    return np.sum((a > 0.5).astype(np.int64), axis=1)
```

In 1D the behaviour is also correct, even with explicit index:

```
# pythran export greater1d(int8[:])
def greater1d(a):
    return np.sum(a > 0.5, axis=0)
```

**Comment by serge-sans-paille** [comment]
#781 should fix that, thanks for the endless stream of bug reports :-/
