### ISSUE TITLE
`python setup.py develop` to work on pythran code?

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#783]
Hi,

I'd like to work on pythran code and I try to use `python setup.py develop`. It would be nice to be able to use this instead of `python setup.py install`.

It does not work because g++ does not find header files.

I remember that I read something about this issue in the documentation but I can not find it anymore. Did I dream?

What is the recommend method to install pythran when one wants to modify its code?

**Comment by serge-sans-paille** [comment]
I usually just do that:

```
> python setup.py build # once, only to copy boost files
```

then ``export PYTHONPATH=$PWD:$PYTHONPATH``

The only things that changes is calling `python -m pythran.run` instead of `pythran`
