### ISSUE TITLE
Enhancement: also print types given to the function for Pythran TypeError

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#784]
It would be convenient to get information about the type of the objects given to the function in such error log:
```
TypeError: Invalid argument type for pythranized function `linear_eigenmode_from_values_1k'.
Candidates are:
   linear_eigenmode_from_values_1k(std.complex<double>,std.complex<double>,std.complex<double>,double,double,double,double)
```
It would be much easier to spot where the problem lies.

**Comment by serge-sans-paille** [comment]
:+1: I'll implement that

**Comment by serge-sans-paille** [comment]
#789 improves the situation, but it's not perfect: it prints ``list`` for a list, ``ndarray`` for a numpy array, whatever their content. Works of for non-container types.
