### ISSUE TITLE
Regression Pythran 0.8.4: np.float64 not recognized as float

### ISSUE THREAD

**Issue by paugier** [serge-sans-paille/pythran#785]
With the module:
```
# pythran export myfunc(float64)

def myfunc(a):
    print(a)
```
we can get anomalous behaviour:

```
In [2]: myfunc(np.float64(1.1))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-f3d6b027bd90> in <module>()
----> 1 myfunc(np.float64(1.1))

TypeError: Invalid argument type for pythranized function `myfunc'.
Candidates are:
   myfunc(double)
```

Remark: same thing with `np.complex128`.

Note that with pythran 0.8.3, it works (even with integer, which was nice):
```
In [2]: myfunc(1.)
1

In [3]: myfunc(np.float64(1.))
1

In [4]: myfunc(int(1))
1
```

**Comment by serge-sans-paille** [comment]
side note : the last case

```python
>>> myfunc(int(1))
````

Is no longer accepted becaused it was incompatible with correct overload. There would be no way to distinguish between

```python
#pythran export myfunc(int, float)
```

and

```python
#pythran export myfunc(float, int)
```

when calling ``myfunc(1, 1)``, so better be slightly more strict.

**Comment by paugier** [comment]
I confirm that the problem is solved with the master branch.

It would be very convenient to have a 0.8.4.post1 release with this bug fix.

**Comment by serge-sans-paille** [comment]
Done! see https://pypi.python.org/pypi/pythran/0.8.4.post0
