### ISSUE TITLE
[doc improvement] state that pythran supports Python 3

### ISSUE THREAD

**Issue by flothesof** [serge-sans-paille/pythran#798]
Hi @serge-sans-paille 
I just noticed that the readme says the following: 
"Pythran supports Python 2.7 and also has a beta Python 3 support."
Wouldn't it be time to remove the word "beta" from the readme?
My point is: this probably scares new users away.
I've used pythran for a couple of months now, exclusively under Python 3, so I feel that saying it's a *beta* is far from the truth: it works very well under Python 3 (I used it on Mac and Windows).
Of course, you're the expert about that, so I'll leave the decision to you!
Best regards,
Florian

**Comment by serge-sans-paille** [comment]
I'd like to 1. obsolete long support and 2. have the whole test suite validate on Python3 before updating the doc. A matter of months, as we are part of http://python3statement.org/

**Comment by flothesof** [comment]
Hi. Thanks for explaining your position on Python 3. Actually, I've just noticed that you don't show your Travis badge in the repo readme. Wouldn't it be a good idea to show that you've deployed CI? 
(side note: how come your tests are taking so long to run on Travis?).
Anyway, I'll close this issue since it's not very useful.

Regards,
Florian

**Comment by serge-sans-paille** [comment]
On Tue, Feb 20, 2018 at 08:13:41PM +0000, Florian LB wrote:
> Hi. Thanks for explaining your position on Python 3. Actually, I've just
> noticed that you don't show your Travis badge in the repo readme. Wouldn't it
> be a good idea to show that you've deployed CI?

probably, yes :-)

> (side note: how come your tests are taking so long to run on Travis?).

validating the whole pythonic API with the corss product of simd, clang
gcc, openmp, python2, python3 :-)
