### ISSUE TITLE
issue with axis argument to argmax/argmin

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#800]
Not sure if I'm doing something wrong but I'm trying to do some work where I need to get the argmax/argmin values along one axis of a 2D array. However I'm getting compilation errors. The simplest test case is:
```python
import numpy as np

#pythran export testargmax(float[][])
def testargmax(x):
    return x.argmax(axis=1)
```
which results in a long list of  `template argument deduction/substitution failed:` errors with the following sections:
```
/home/jschrod/.local/lib/python3.6/site-packages/pythran/pythonic/utils/functor.hpp:13:22: error: no matching function for call to ‘argmax({anonymous}::pythonic::types::numpy_texpr<{anonymous}::pythonic::types::ndarray<double, 2> >, long int)’
         -> decltype(f(std::forward<Types>(types)...))                          \
```
if I understand this correctly pythran assumes it should get a long int not an array from argmax? Same thing happens for argmin.

**Comment by serge-sans-paille** [comment]
Thanks for the bug report, I can reproduce it, it's just that we don't
support argmax along an axis. I'll implemment that!

**Comment by serge-sans-paille** [comment]
Can you confirm #803 fixes your issue?

**Comment by cycomanic** [comment]
Great thanks!

**Comment by cycomanic** [comment]
Sorry, my answer might be not clear enough, yes #803 fixes my issue
