### ISSUE TITLE
Return function or capsule from function 

### ISSUE THREAD

**Issue by cycomanic** [serge-sans-paille/pythran#802]
In my application I have a main processing loop which runs a couple of subfunctions. One of them is an error fct which should be configurable, which in cython I pass to the function as an cdef object. This errorfct always has the same signature, but typically has some different constants associated with it, which I currently set up when creating it. 

Typically the main process function signature would look like this:
```python
def process(field, param1, param2, errfct ...):
    for i in range(field.shape[0]):
        x = subfct1(field, param1)
        field *= subfct2(field, param2)
        ee = errfct(field)
        ...
   return ee
```
I would like to create the error function as return from another function e.g. like this:
```python
def make_errfct(method, param, param2 ...):
    if method == 1:
        X = np.ones(100)*param
        def errfct(field):
             return X-field
        return errfct
    if method == 2:
        X = np.ones(100) + (param*1j)
        def errfct(field):
            return X.real-field.real + 1.j*(X.imag - field.imag)
        return errfct
    ...
```
Now I think this is already possible if I stay within pythran, i.e. I would run this at the beginning of process. However if I export make_errorfct and call it from python I simply get None as return (I guess somewhat expected). Would it be possible to have make_errfct return the errfct inside a capsule instead? That way I could pass it to the process function. 
What I'm trying to avoid is having to pass a lot of (mostly unnecessary) parameters to process, just to initialise the error function, especially because the `X` calculation above in reality relies on external modules which I would have to put into pythran as well then.

Or is there a different way of achieving this? Hope this is understandable.

**Comment by serge-sans-paille** [comment]
Sounds like a very interesting scenario. I don't have time to keep up
with all your issues but I'll check that once the armin/max with axis si
implemented :-)

**Comment by cycomanic** [comment]
No worries. I appreciate how much time you put into this. Unfortunately my C++ is years ago (and even then I was not even using templates. However I have some time after a deadline in 2 weeks, so I might try my hands on some PRs. Also have you considered getting a DOI for pythran? Makes citing easier

**Comment by ashwinvis** [comment]
@cycomanic  There are 2 articles. I don't have a DOI though

```TeX
@inproceedings{guelton_pythran2013,
	title = {Pythran: {Enabling} {Static} {Optimization} of {Scientific} {Python} {Programs}},
	shorttitle = {Pythran},
	urldate = {2017-09-23},
	author = {Guelton, Serge and Brunet, Pierrick and Raynaud, Alan and Merlini, Adrien and Amini, Mehdi},
	year = {2013},
	pages = {46--52},
}

@article{guelton2015pythran,
  title={Pythran: Enabling static optimization of scientific python programs},
  author={Guelton, Serge and Brunet, Pierrick and Amini, Mehdi and Merlini,
                  Adrien and Corbillon, Xavier and Raynaud, Alan},
  journal={Computational Science \& Discovery},
  volume={8},
  number={1},
  pages={014001},
  year={2015},
  publisher={IOP Publishing}
}
```

**Comment by serge-sans-paille** [comment]
@ashwinvis yes, I'll update the doc accordingly.

**Comment by serge-sans-paille** [comment]
Done in 26b0b66a1af00b2c9f59640a2349c4b568040219

**Comment by serge-sans-paille** [comment]
@cycomanic tehre's an issue with your request: although it sounds great, there is no way pythran could generate a capsule from the definition of ``errfct``. Indeed, it's a polymorphic function, something that cannot be represented by a function pointer and thus it cannot be put in a capsule.

**Comment by cycomanic** [comment]
Maybe  I did not make the example clear enough (or I always misunderstood polymorphic functions).
errfct would always have the same signature e.g. complex(complex). 

I was under the impression that a polymorphic function means a function which take input parameters which can have different types (and possibly act accordingly), for the behaviour I'm talking about I would  use global variables in C. Also just to be clear, I want to pass this back to a pythran function, so it does not need to be a generic capsule if there is another way.

**Comment by serge-sans-paille** [comment]
*you* known that ``errfct`` ihas complex(complex) signature, but there is no way to deduce that from the code above. It coul as well be an array of complex. And it could be complex128 complex64.

**Comment by serge-sans-paille** [comment]
first option would be possible but requires a lot of work and that's definitively not in my top priority list. Second option would work, just pass a tuple instead of a struct and that should be OK.

**Comment by cycomanic** [comment]
Oh, this is awesome! I did not realise I can pass tuples to capsules. I assumed only c-types would work. I think this would be a good addition to the manual.
