### ISSUE TITLE
Non determinist compilation error?

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#804]
Here two function doing exactly the same thing the only difference is the input "format.
I had very strange behavour on that, sometime it's compile sometime not.
For example the following example it doesn't compile (something related to __pythran_modone::get_new_image_reference::operator())
but if I remove XXX from `# pXXXythran export aabb(int32[][] list, int[][])`, the compiler doesn't complain anymore on get_new_image_reference ????

```
import numpy as np

# pXXXythran export aabb(int32[][] list, int[][])
# pythran export aabb(float32[][] list, int[][])
def aabb(exdata, nflag):
    Nimgs = len(exdata)

    maxflag = int(np.amax(nflag)) + 1 

    if np.any(nflag >= Nimgs):
        raise Exception("You need %d extra images instead of %d" % (maxflag, Nimgs))

    imref = exdata[0]

    for j in xrange(1, maxflag):
        imref = np.where(nflag == j, exdata[j], imref)

    return imref


# pythran export get_new_image_reference((int32[][], int[][], int32[][] list, float32[][], int))
# pXXythran export get_new_image_reference((int64[][], int[][], int64[][] list, float32[][], int))
# pXXythran export get_new_image_reference((float32[][], int[][], float32[][] list, float32[][], int))
# pXXythran export get_new_image_reference((float64[][], int[][], float64[][] list, float32[][], int))
def get_new_image_reference(reference):
    _, nflag, exdata, _, _ = reference

    Nimgs = len(exdata)

    maxflag = int(np.amax(nflag)) + 1 

    if np.any(nflag >= Nimgs):
        raise Exception("You need %d extra images instead of %d" % (maxflag, Nimgs))

    imref = exdata[0]

    for j in xrange(1, maxflag):
        imref = np.where(nflag == j, exdata[j], imref)

    return imref

```

**Comment by diorcety** [comment]
Doing `imref = np.where(True, exdata[0], exdata[0])  # Pythran fix` this to fix this issue ... but the behaviour is suspect

**Comment by diorcety** [comment]
Not on this example but on the real code, sometime the compilation worked, sometimes not, retry multiple times allow to make it works ... (clang 3.8)

**Comment by diorcety** [comment]
Full error: https://pastebin.com/rH6D21qT

**Comment by serge-sans-paille** [comment]
Hi diorcety. I have commited recently a fix that makes the build more reproducible. Are you using master version?

**Comment by serge-sans-paille** [comment]
Using master version and the code above (with the XXX)

```
while python -m pythran.run dc.py; do echo "OK..." ; done 
```

does not give me any error (yet)

**Comment by diorcety** [comment]
Indeed my branch was less than 2 month old, but rebasing on master make it works. Thanks
