### ISSUE TITLE
Copying in Fortran order

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#805]
The following script fails to compile:

```
import numpy as np

#pythran export f(float[:, :])
def f(matrix):
    matrix_f = np.copy(matrix, order='f')
    return matrix_f.sum()
```

In my application, the memory access is much more suitable for Fortran order. What can we do about it? Is Pythran smart enough to recognise and do the transformation on its own, or should I rewrite the algorithm?

**Comment by serge-sans-paille** [comment]
If the memory order of the input array is in Fortran style, Pythran represents that using a transposed matrix (this may not be a nice choice). We don't dont do anything smart on your case, but we should, as the default behavior of np.copy is to match the original data layout. I'll check that.

**Comment by serge-sans-paille** [comment]
@Dapid does #810 somehow fixes your issue? It's not possible to support the ``order`` argument in Pythran, but as of now, ``np.copy`` at least respect original memory order.

**Comment by Dapid** [comment]
Not quite. I want to change the order of the array. I have adapted the code to use the transpose outside of Pythran.

Any chance changing the alignment will be supported in the future? Otherwise, I think it would be good to document it as a limitation.
