### ISSUE TITLE
Pythran cannot return objects of different types

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#806]
This works:
```
#pythran export f(float[:, :])
def f(matrix):
    return matrix.sum(axis=1), matrix.sum(axis=0)
```

But this doesn't:
```
#pythran export f(float[:, :])
def f(matrix):
    return matrix.sum(), matrix.sum(axis=0)
```

The error message is: `E: function may returns with incompatible types `Tuple[int, T0, T1]` and `Scalar` (a.py, line 8)`

It would be nice to be able to return objects of different types. For now I can return the scalars and write on the vectors, passed as inputs.

**Comment by serge-sans-paille** [comment]
> #pythran export f(float[:, :])
> def f(matrix):
>     return matrix.sum(), matrix.sum(axis=0)

this code works perfectly fine on my setup, which pythran version are
you using?

**Comment by Dapid** [comment]
Strange... I swear it was failing for me, but I cannot longer replicate.

**Comment by Dapid** [comment]
I think I found the original cause of the problem, I'm writing it for future references. I changed a function to return two objects instead of one, but I didn't see it had a special case with an early return, hence the incompatible types.

I do not know why the example was failing, or what made it stop failing.

**Comment by serge-sans-paille** [comment]
ok, got it:

Pythran does not support returning different types. If you write this

```python
def foo(n):
    if n:
        return 1
    else:
        return "1"
```

Then this code is not considered as statically typable, as the return
type depends on runtime value of ``n``.

Is that your situation?

**Comment by Dapid** [comment]
No, it was actually a mistake. Pythran prevented me from a hard crash in a corner case, so that is good.
