### ISSUE TITLE
Compilation error for np.exp and complex numbers

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#809]
I'm seeing a compilation error for this simple code:
`#pythran export adjustRots(complex[])
def adjustRots(rots):
    N = rots.shape[0]
    rr = np.random.random(N)
    for jj in range(N):
        rots[jj] = np.exp(2j * np.pi * rr[jj])  # This does not work
        rots[jj] = np.cos(2 * np.pi * rr[jj]) + 1j * np.sin(2 * np.pi * rr[jj])  # This does work`

I'm using  pythran 0.8.4post0 on MacOs 10.12.6

**Comment by serge-sans-paille** [comment]
I can reproduce the issue, I'm investigating that :-)

**Comment by serge-sans-paille** [comment]
The problem is due to boost.simd that does not support complex number for several operations. I'll use ``std::`` as a fallback.

**Comment by serge-sans-paille** [comment]
@jeanlaroche can you confirm #811 fixes your issue?

**Comment by jeanlaroche** [comment]
Sorry for some reason I didn't get notified of your response! :( Testing now! Thanks a bunch. Will let you know.
