### ISSUE TITLE
Cannot reshape or wrong reshape 

### ISSUE THREAD

**Issue by rolanddenis** [serge-sans-paille/pythran#824]
Hello,

I have some issues while reshaping numpy arrays. Considering this minimal example:
```Python
import numpy as np
#pythran export dummy()
def dummy():
    return np.arange(9).reshape(3,3)
```

I get, using Pythran 0.8.4post0:
```bash
$ pythran test.py
CRITICAL: I am in trouble. Your input file does not seem to match Pythran's constraints...
E: cannot reshape array of size 9 into shape (3,) (test.py, line 4)
```

Considering another shape:
```Python
return np.arange(9).reshape(-1,3)
```
it compiles fine but the array is not reshaped:
```Python
>>> test.dummy()
array([0, 1, 2, 3, 4, 5, 6, 7, 8])
```

**Comment by serge-sans-paille** [comment]
Your reshape call is incorrect (as in *invalid in Python*). Use

```python
np.arange(9).reshape((3,3))
```

**Comment by rolanddenis** [comment]
My bad, I didn't check the doc since it works in Python ...

(Huh, in fact, it is a supported syntax, see https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.reshape.html )

**Comment by serge-sans-paille** [comment]
Got it! The problem comes from pythran that uses np.reshape in place of calling the method. And they have slightly different interface :-/

**Comment by rolanddenis** [comment]
Thanks !
