### ISSUE TITLE
Swapping row does nothing

### ISSUE THREAD

**Issue by rolanddenis** [serge-sans-paille/pythran#825]
Hello (again),

#824 was a step while searching why one of my Python code doesn't output the same result when compiled with Pythran.

Here is a minimal example:
```Python
import numpy as np
#pythran export dummy()
def dummy():
    A =  np.arange(9).reshape((3,3))
    A[[1,2]] = A[[2,1]]
    return A
```
outputs
```Python
>>> test.dummy()
array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])
```
while, using Pythran:
```Python
>>> test.dummy()
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])
```

By the way, I've try to work around using `A[1,:].copy()` but C++ compilation failed. I had to use `tmp = numpy.array(A[1,:])` instead and my code now works fine and much faster :wink: (great job, btw)

**Comment by serge-sans-paille** [comment]
Thanks for the report! I can reproduce the issue, working on it :-)
