### ISSUE TITLE
Add dtype keyword to np.eye

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#831]
Here's the offending line:

    CPM_unpaired_tmp   = np.eye(Zc, dtype=int);
E: function uses an unkown (sic) (or unsupported) keyword argument `dtype` (nr_encoder.py, line 75)

**Comment by serge-sans-paille** [comment]
Welcome back @nbecker ! there was a bug in the argument inspect code, should be fixed by #832. Thanks for reporting!
