### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#837]
This slightly modified version:
https://gist.github.com/nbecker/19b670b0652e9d769bf5e95cd5ba79e2

Gives:
ImportError: ./G.so: undefined symbol: _ZNK12_GLOBAL__N_18pythonic5types7ndarrayIdLm2EEixIlEEDTixdefpTcl3getILi0EEfp_EERKSt5tupleIJT_EE

When compiled with the latest pythran git

**Comment by serge-sans-paille** [comment]
You're playing with a WIP dev branch, don't be afraid :-)

```
% c++filt _ZNK12_GLOBAL__N_18pythonic5types7ndarrayIdLm2EEixIlEEDTixdefpTcl3getILi0EEfp_EERKSt5tupleIJT_EE
decltype ((*this)[(get<0>)({parm#1})]) (anonymous namespace)::pythonic::types::ndarray<double, 2ul>::operator[]<long>(std::tuple<long> const&) const
```

I'll add this missing def at once :-)

**Comment by serge-sans-paille** [comment]
#838 should fix that (?)
