### ISSUE TITLE
Compile error on 2-dim and 3-dim arrays

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#843]
I'm running into this compilation error

```
import numpy as np

# pythran export timeScaleSnippet()
def timeScaleSnippet():
    N = 2
    M = 10
    X = np.zeros((N, M, 2))  # X is NxMx2
    Z = np.zeros((N, M))     # Z is NxM

    XX = X[0,:]              # XX is Mx2
    #R = Z[0,]              # R is M, <- THIS COMPILES.
    R = Z[0,:]               # R is M, <- THIS creates a compile error if the below line is included, but not if you return R
    Y = XX * R[:,None]       # This is where the error occurs!
    return Y
```
NOTE: The error does not occur if I return R instead of Y, so the error is in XX * R[:,None]

[log.txt](https://github.com/serge-sans-paille/pythran/files/1877944/log.txt)

**Comment by serge-sans-paille** [comment]
#846 should do the trick :-)

**Comment by jeanlaroche** [comment]
I confirm that 846 fixes the issue...

**Comment by serge-sans-paille** [comment]
On Thu, Apr 05, 2018 at 07:07:13PM +0000, jeanlaroche wrote:
> I confirm that 846 fixes the issue...

Cool \o/

**Comment by jeanlaroche** [comment]
Release 0.8.5 does not solve this issue.

**Comment by jeanlaroche** [comment]
I confirm that this is fix in master https://github.com/serge-sans-paille/pythran/commit/c3dd1ef72aa7de51d84ab25ea4d936101d8a5802
Both in linux and mac ox. Closing.
