### ISSUE TITLE
long64 vs long

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#848]
I ran into an issue where a pythraned function was declared as
```
pythran export myFunc(int)
```
But was called from python with a numpy int which by default is an int64 whereas the default python int is a regular int. Is there a way to fix that automatically without having to either:
- transform the input param upon calling: int(value)
- declare the function as `pythran export myFunc(int or int64)`

This is especially problematic when you have lots of input, in which case the `int or int64` option is not very good (because it creates too much code).

**Comment by serge-sans-paille** [comment]
I'm puzzled, int (in pythran signature) defaults to a native long, which
can be int32 or int64 depending on the plaform.

Why don't you just force int64 in the pythran export? It should work for
python int and numpy int.

**Comment by jeanlaroche** [comment]
I hadn't thought of that! I tried it, but that breaks something else in pythran. 
`error: no matching function for call to object of type '(anonymous namespace)::pythonic::numpy::functor::empty'
    typedef typename pythonic::assignable<decltype(std::declval<__type44>()(std::declval<__type51>(), std::declval<__type52>()))>::type __type53;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
/var/folders/j6/7t8sg1vj4q97zhh9z5cdmxbm4rz935/T/tmp8JnYFU.cpp:599:82: note: in instantiation of function template specialization '__pythran_rotation::timeScaleSnippet::operator()<(anonymous namespace)::pythonic::types::ndarray<double, 2> &, long long &, long long &, long long &, long long &, long long &, long long &, (anonymous namespace)::pythonic::types::ndarray<double, 2> &, (anonymous namespace)::pythonic::types::ndarray<double, 2> &, long long &, double &>' requested here
                                auto res = __pythran_rotation::timeScaleSnippet()(inputSignal, inLeft, inRight, outLeft, outRight, windowLen, fftSize, window, outputSignal, applyRenorm, maxNormFreq);`
i haven't tried to isolate where the error occurs (always difficult)...

**Comment by serge-sans-paille** [comment]
If you can provide me with the full.py that's ok :-)

**Comment by serge-sans-paille** [comment]
up

**Comment by jeanlaroche** [comment]
Let me close this, I don't think it's relevant any longer
