### ISSUE TITLE
Can't pass int64 to numpy.zeros()

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#849]
This fails to compile, unless you change the declaration from int64 to int. The same occurs for empty() (I'm sure many other function that normally take ints).
```
import numpy as np

# pythran export timeScaleSnippet(int64)
def timeScaleSnippet(N):
    Y = np.zeros((M,M),dtype=float)
    return Y
```

**Comment by serge-sans-paille** [comment]
I fail to reproduce with master version. Can you confirm it's fixed?

**Comment by jeanlaroche** [comment]
Yes it looks like it's fixed.
