### ISSUE TITLE
Coding guidelines for pythonic++

### ISSUE THREAD

**Issue by joker-eph** [serge-sans-paille/pythran#85]
Are there any rules? Pythran has a nice PEP8 compliance rule but what about the C++ code?  I mean for instance you don't accept lines >78 char in Python but >160 is not a problem in C++ ?

**Comment by serge-sans-paille** [comment]
This has been fixed in ccfb3fbea2baa1837c7cfb3cfc3393c97de9a67d

Using clang-format and its default style.
