### ISSUE TITLE
numpy.inf is needed

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#850]
numpy.inf isn't supported by pythran, yet it's a very useful thing to have.
```
import numpy as np
# pythran export test()
def test():
    N = np.inf
```

**Comment by serge-sans-paille** [comment]
This seems to be well supported, what makes you think it is not?

**Comment by jeanlaroche** [comment]
The issues is that np accepts np.Inf (uppercase i) and np.inf, but not pythran. I hadn't realized that when I submitted the bug
```
import numpy as np

# pythran export test(float)
def test(x):
    if x < np.Inf: return 0 # Fails
    if x < np.inf: return 0 # OK
    return 1
```
