### ISSUE TITLE
Compilation error on slice assignment

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#851]
Compilation error on this code. It's a simple slice assignment. Not sure why this breaks.

```
import numpy as np

# pythran export test(float[][],int,float[][],int,int,float[][])
def test(X,M,Y,N1,pOTP,rD):
    LCf = len(rD)
    Y[pOTP:pOTP+N1+LCf,] = X[0:N1+LCf,]  # <- This works
    return test2(X[M:,],Y, N1, pOTP, rD)

#pythran export test2(float[][],float[][],int,int,float[][])
def test2(X,Y,N1,pOTP,rD):
    LCf = len(rD)
    Y[pOTP:pOTP+N1+LCf,] = X[0:N1+LCf,]  # <- Compilation breaks on this
    return 1

# if __name__ == '__main__':
#     X=np.zeros((1000,2))
#     Y=np.zeros((1000,2))
#     rD=np.zeros((100,2))
#     test(X, 10, Y, 10, 20, rD)
```

**Comment by serge-sans-paille** [comment]
@jeanlaroche: both examples compile fine with current master on linux, can you confirm?

**Comment by jeanlaroche** [comment]
Still fails, but only on MacOS :( ...
Here's the pruned down test:
```
import numpy as np

# pythran export test(float[][],int,float[][],int,int)
def test(X,M,Y,N1,N2):
    return test2(X[M:,],Y, N1, N2) # <- This fails

#pythran export test2(float[][],float[][],int,int)
def test2(X,Y,N1,N2):
    Y[N2:N2+N1,] = X[0:N1,]
    return 1
```
And the error:

> error: static_assert failed "Attempted to construct a reference element in a tuple with an rvalue"
        {static_assert(__can_bind_reference<_Tp>(),
         ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/tuple:411:15: note: in instantiation of function template specialization 'std::__1::__tuple_leaf<0, const (anonymous namespace)::pythonic::types::contiguous_slice &, false>::__tuple_leaf<(anonymous namespace)::pythonic::types::contiguous_slice, void>' requested here
            : __tuple_leaf<_Indx, _Tp>(_VSTD::forward<typename tuple_element<_Indx,

>

**Comment by jeanlaroche** [comment]
My bad, this is now fixed on master. Sorry about the confusion.
