### ISSUE TITLE
Provide better debug info for "wrong type of input argument"

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#853]
I often spend a lot of time trying to determine which of my input argument does not match the pythran declaration. That's because during execution, there's no hint provided as to which argument is violating the requirements, and some violation are not easy to find.
For example, passing a view instead of an ndarray creates an error, but nothing in the error indicates where it could come from (the input param is still an ndarray)

**Comment by Dapid** [comment]
Probably the same I am seeing in #842.

@serge-sans-paille, do you think this is a good place to start wading through the code? I would like to get this fixed.

**Comment by serge-sans-paille** [comment]
@Dapid that would be a great contribution. The starting point is https://github.com/serge-sans-paille/pythran/blob/master/pythran/pythonic/python/core.hpp#L50 and more precisely https://github.com/serge-sans-paille/pythran/blob/master/pythran/pythonic/python/core.hpp#L71.

We need a better pretty-printer here.

**Comment by Dapid** [comment]
I have been able to localise the problem to the strides. This patch prints it uglily before crashing:

```
(py36) [david@SQUIDS pythran]🦑 git diff pythran/pythonic/types/ndarray.hpp
diff --git a/pythran/pythonic/types/ndarray.hpp b/pythran/pythonic/types/ndarray.hpp
index 3c842fbf..e08a50b8 100644
--- a/pythran/pythonic/types/ndarray.hpp
+++ b/pythran/pythonic/types/ndarray.hpp
@@ -1406,16 +1406,29 @@ bool from_python<types::ndarray<T, N>>::is_convertible(PyObject *obj)
   auto const *dims = PyArray_DIMS(arr);
   long current_stride = PyArray_ITEMSIZE(arr);
   for (long i = N - 1; i >= 0; i--) {
-    if (stride[i] != current_stride)
+    if (stride[i] != current_stride){
+      std::cerr << i << "  " << stride[i] << "  " << current_stride << std::endl;
+
+      current_stride = PyArray_ITEMSIZE(arr);
+      for (long j = N - 1; j >= 0; j--){
+          std::cerr << "  " << stride[j] << "   " << current_stride << "   " << dims[j];
+          if (j == i)
+            std::cerr << " <----";
+          std::cerr << std::endl;
+          current_stride *= dims[j];
+      }
       return false;
+    }
     current_stride *= dims[i];
   }
   // this is supposed to be a texpr
   if ((PyArray_FLAGS(arr) & NPY_ARRAY_F_CONTIGUOUS) &&
-      ((PyArray_FLAGS(arr) & NPY_ARRAY_C_CONTIGUOUS) == 0) && (N > 1))
+      ((PyArray_FLAGS(arr) & NPY_ARRAY_C_CONTIGUOUS) == 0) && (N > 1)){
     return false;
-  else
+  }
+  else{
     return true;
+  }
 }
 template <typename T, size_t N>
 types::ndarray<T, N> from_python<types::ndarray<T, N>>::convert(PyObject *obj)
```

Wading through Pythran guts is less daunting than I expected...

@jeanlaroche do you have a small failing example? Mine is kind of big, and takes a while to compile.

**Comment by jeanlaroche** [comment]
Let me try to create one for you...

**Comment by jeanlaroche** [comment]
Here's the function to pythranize
```
import numpy as np

#pythran export test(float [])
def test(x):
    return 2*x
```
Here's the code to call it:
```
import numpy as np
from code_above import test

x = np.ones(10,dtype=float)
print test(x)
print test(x[0::2])
```
The first call works, but the second one craps out with:

> TypeError: Invalid call to pythranized function `test(ndarray)'
Candidates are:
   test(float[:])

>

**Comment by serge-sans-paille** [comment]
@Dapid That's a good start! Once you're satisfied, issue a PR and I'll happily review it :-)

**Comment by serge-sans-paille** [comment]
@Dapid any update on that? Need any help?

**Comment by Dapid** [comment]
I am working on it, got a bunch of notes, and making my way forward. I hope to have something by the end of the week.

**Comment by serge-sans-paille** [comment]
@Dapid I'll do a release today or tomorrow, your patch will go in next release!

**Comment by serge-sans-paille** [comment]
@Dapid release done, any update on your side?

**Comment by Dapid** [comment]
Sorry! Deadlines galore, I haven't had much time to work on it yet. But I will be putting something out as soon as I can.

**Comment by serge-sans-paille** [comment]
Hi @Dapid any update on that dev? Release is coming!

**Comment by h-vetinari** [comment]
@serge-sans-paille 
> Release is coming!

May I ask what the current timeline for 0.8.7 is? That comment I quoted is now 6 weeks old...

**Comment by Dapid** [comment]
Sorry! I have been bad at keeping this, but I am kinda swamped.

But, I mentioned you in the paper: https://www.biorxiv.org/content/early/2018/08/02/383133 (real publication in progress).

**Comment by serge-sans-paille** [comment]
and thanks @Dapid for the motivation and the citation ;-)

**Comment by h-vetinari** [comment]
@serge-sans-paille Thanks for the info!
