### ISSUE TITLE
Use flake8 to find syntax errors & undefined names

### ISSUE THREAD

**Issue by cclauss** [serge-sans-paille/pythran#872]
#871 generates the output: https://travis-ci.org/serge-sans-paille/pythran/builds/370834478

This shows that there are many syntax errors and undefined names to fix across this codebase.  Adding these [flake8](http://flake8.pycqa.org) tests to the current __.travis.yml__ (a task that is beyond my skills) would greatly accelerate the achievement of compatibility with both Python 2 and 3.

**Comment by serge-sans-paille** [comment]
Indeed, some of the flake8 warnings are relevant, I'll check that.

**Comment by cclauss** [comment]
Interesting question if flake8 should be run on Travis (#871) or Appveyor (#873) or yet another CI like Circle.  Travis seem way overloaded.

**Comment by serge-sans-paille** [comment]
@cclauss : #877 is green, does that looks ok to you?

**Comment by serge-sans-paille** [comment]
Closed by #877
