### ISSUE TITLE
cannot convert to 'bool'

### ISSUE THREAD

**Issue by svretina** [serge-sans-paille/pythran#882]
First of all, congratulations for this really awesome software. I am currently trying to implement some ODE's solving algorithms with pythran to benchmark the performance and to learn this tool for my research. 
This code is for solving the wave equation in time: 

#pythran export wave(int)

import numpy as np

def wave(n):

    Nx = n
    number_of_threads = 4
    t0 = 0
    x0 = 0
    alpha = np.sqrt(2.)/np.pi
    dx = 12./Nx
    dt = 0.5*dx/alpha
    Nt = int(5.*np.pi/dt)
    c = alpha*dt/dx
    u = np.zeros((Nx,Nt))
    x = np.zeros((Nx,1))
    t = np.zeros((Nt,1))

    #omp parallel for num_threads(number_of_threads) private(i) shared(Nx,x0,x,dx)
    for i in range(Nx):
        x[i] = x0+i*dx

    #omp parallel for num_threads(number_of_threads) private(i) shared(Nt,t0,dt,t)
    for i in range(Nt):
        t[i] = t0 + i*dt
    
    for i in range(Nx):
        if x[i]>=2 and x[i]<=4:
            u[i][0] = np.sin(np.pi*x[i])
        else:
            u[i][0] = 0
        #omp parallel for shared(Nt,u) private(j)
        for j in range(Nt):
            u[0][j]=0
            u[Nx-1][j]=0

    for j in range(Nt-1):
        #omp parallel for num_threads(number_of_threads) private(i) shared(u,Nx,j,c)
        for i in range(Nx-1):
            u[i][j+1]=u[i][j]-(c/2.)*(u[i+1][j]-u[i-1][j])+(np.power(c,2.)/2.)*(u[i+1][j]-2.*u[i][j]+u[i-1][j] )
    return u

The problem occurs in line    if x[i]>2 and x[i]<4:   
The error output is huge which I dont understand fully. 
Compilation command I use: pythran -DUSE_BOOST_SIMD -march=native -Ofast -fopenmp wave.py

The error log: 

/tmp/tmpeser9znt.cpp: In instantiation of ‘typename __pythran_wave::wave::type<argument_type0>::result_
type __pythran_wave::wave::operator()(argument_type0&&) const [with argument_type0 = long int&; typenam
e __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythonic::types::ndarray<doubl
e, 2>]’:                                                                                              
/tmp/tmpeser9znt.cpp:224:68:   required from here
/tmp/tmpeser9znt.cpp:190:11: error: could not convert ‘{anonymous}::pythonic::__builtin__::pythran::and
_(T0&&, T1&&) [with T0 = __pythran_wave::wave::operator()(argument_type0&&) const [with argument_type0 
= long int&; typename __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythonic::
types::ndarray<double, 2>]::<lambda()>; T1 = __pythran_wave::wave::operator()(argument_type0&&) const [
with argument_type0 = long int&; typename __pythran_wave::wave::type<argument_type0>::result_type = {an
onymous}::pythonic::types::ndarray<double, 2>]::<lambda()>; {anonymous}::pythonic::types::lazy_combined
_t<T0, T1> = {anonymous}::pythonic::types::ndarray<bool, 1>](<lambda closure object>__pythran_wave::wav
e::operator()(argument_type0&&) const [with argument_type0 = long int&; typename __pythran_wave::wave::
type<argument_type0>::result_type = {anonymous}::pythonic::types::ndarray<double, 2>]::<lambda()>{x, i}
)’ from ‘{anonymous}::pythonic::types::lazy_combined_t<__pythran_wave::wave::operator()(argument_type0&
&) const [with argument_type0 = long int&; typename __pythran_wave::wave::type<argument_type0>::result_
type = {anonymous}::pythonic::types::ndarray<double, 2>]::<lambda()>, __pythran_wave::wave::operator()(
argument_type0&&) const [with argument_type0 = long int&; typename __pythran_wave::wave::type<argument_
type0>::result_type = {anonymous}::pythonic::types::ndarray<double, 2>]::<lambda()> > {aka {anonymous}:
:pythonic::types::ndarray<bool, 1>}’ to ‘bool’                                                        
           if (pythonic::__builtin__::pythran::and_([&] () { return (x.fast(i) >= 2L); }, [&] () { retu
rn (x.fast(i) <= 4L); }))                                                                             
           ^~
/tmp/tmpeser9znt.cpp:192:36: error: cannot convert ‘std::enable_if<true, {anonymous}::pythonic::types::
numpy_expr<{anonymous}::pythonic::numpy::functor::sin, {anonymous}::pythonic::types::numpy_expr<{anonym
ous}::pythonic::operator_::functor::mul, {anonymous}::pythonic::types::broadcast<double, double>, {anon
ymous}::pythonic::types::numpy_iexpr<const {anonymous}::pythonic::types::ndarray<double, 2>&> > > >::ty
pe {aka {anonymous}::pythonic::types::numpy_expr<{anonymous}::pythonic::numpy::functor::sin, {anonymous
}::pythonic::types::numpy_expr<{anonymous}::pythonic::operator_::functor::mul, {anonymous}::pythonic::t
ypes::broadcast<double, double>, {anonymous}::pythonic::types::numpy_iexpr<const {anonymous}::pythonic:
:types::ndarray<double, 2>&> > >}’ to ‘double’ in assignment                                          
             std::get<0>(u.fast(i)) = pythonic::numpy::functor::sin{}((3.141592653589793 * x.fast(i)));
             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/tmpeser9znt.cpp:22:0:
/usr/local/lib/python3.6/site-packages/pythran/pythonic/__builtin__/pythran/and_.hpp: In instantiation 
of ‘{anonymous}::pythonic::types::lazy_combined_t<T0, T1> {anonymous}::pythonic::__builtin__::pythran::
and_(T0&&, T1&&) [with T0 = __pythran_wave::wave::operator()(argument_type0&&) const [with argument_typ
e0 = long int&; typename __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythoni
c::types::ndarray<double, 2>]::<lambda()>; T1 = __pythran_wave::wave::operator()(argument_type0&&) cons
t [with argument_type0 = long int&; typename __pythran_wave::wave::type<argument_type0>::result_type = 
{anonymous}::pythonic::types::ndarray<double, 2>]::<lambda()>; {anonymous}::pythonic::types::lazy_combi
ned_t<T0, T1> = {anonymous}::pythonic::types::ndarray<bool, 1>]’:                                     
/tmp/tmpeser9znt.cpp:190:51:   required from ‘typename __pythran_wave::wave::type<argument_type0>::resu
lt_type __pythran_wave::wave::operator()(argument_type0&&) const [with argument_type0 = long int&; type
name __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythonic::types::ndarray<do
uble, 2>]’                                                                                            
/tmp/tmpeser9znt.cpp:224:68:   required from here
/usr/local/lib/python3.6/site-packages/pythran/pythonic/__builtin__/pythran/and_.hpp:21:7: error: could
 not convert ‘val0’ from ‘{anonymous}::pythonic::types::numpy_expr<{anonymous}::pythonic::operator_::fu
nctor::ge, {anonymous}::pythonic::types::numpy_iexpr<const {anonymous}::pythonic::types::ndarray<double
, 2>&>, {anonymous}::pythonic::types::broadcast<double, long int> >’ to ‘bool’                        
       if (val0)
       ^~
/tmp/tmpeser9znt.cpp: In instantiation of ‘typename __pythran_wave::wave::type<argument_type0>::result_
type __pythran_wave::wave::operator()(argument_type0&&) const [with argument_type0 = long int&; typenam
e __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythonic::types::ndarray<doubl
e, 2>]’:                                                                                              
/tmp/tmpeser9znt.cpp:224:68:   required from here
/tmp/tmpeser9znt.cpp:190:11: error: could not convert ‘{anonymous}::pythonic::__builtin__::pythran::and
_(T0&&, T1&&) [with T0 = __pythran_wave::wave::operator()(argument_type0&&) const [with argument_type0 
= long int&; typename __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythonic::
types::ndarray<double, 2>]::<lambda()>; T1 = __pythran_wave::wave::operator()(argument_type0&&) const [
with argument_type0 = long int&; typename __pythran_wave::wave::type<argument_type0>::result_type = {an
onymous}::pythonic::types::ndarray<double, 2>]::<lambda()>; {anonymous}::pythonic::types::lazy_combined
_t<T0, T1> = {anonymous}::pythonic::types::ndarray<bool, 1>](<lambda closure object>__pythran_wave::wav
e::operator()(argument_type0&&) const [with argument_type0 = long int&; typename __pythran_wave::wave::
type<argument_type0>::result_type = {anonymous}::pythonic::types::ndarray<double, 2>]::<lambda()>{x, i}
)’ from ‘{anonymous}::pythonic::types::lazy_combined_t<__pythran_wave::wave::operator()(argument_type0&
&) const [with argument_type0 = long int&; typename __pythran_wave::wave::type<argument_type0>::result_
type = {anonymous}::pythonic::types::ndarray<double, 2>]::<lambda()>, __pythran_wave::wave::operator()(
argument_type0&&) const [with argument_type0 = long int&; typename __pythran_wave::wave::type<argument_
type0>::result_type = {anonymous}::pythonic::types::ndarray<double, 2>]::<lambda()> > {aka {anonymous}:
:pythonic::types::ndarray<bool, 1>}’ to ‘bool’                                                        
           if (pythonic::__builtin__::pythran::and_([&] () { return (x.fast(i) >= 2L); }, [&] () { retu
rn (x.fast(i) <= 4L); }))                                                                             
           ^~
/tmp/tmpeser9znt.cpp:192:36: error: cannot convert ‘std::enable_if<true, {anonymous}::pythonic::types::
numpy_expr<{anonymous}::pythonic::numpy::functor::sin, {anonymous}::pythonic::types::numpy_expr<{anonym
ous}::pythonic::operator_::functor::mul, {anonymous}::pythonic::types::broadcast<double, double>, {anon
ymous}::pythonic::types::numpy_iexpr<const {anonymous}::pythonic::types::ndarray<double, 2>&> > > >::ty
pe {aka {anonymous}::pythonic::types::numpy_expr<{anonymous}::pythonic::numpy::functor::sin, {anonymous
}::pythonic::types::numpy_expr<{anonymous}::pythonic::operator_::functor::mul, {anonymous}::pythonic::t
ypes::broadcast<double, double>, {anonymous}::pythonic::types::numpy_iexpr<const {anonymous}::pythonic:
:types::ndarray<double, 2>&> > >}’ to ‘double’ in assignment                                          
             std::get<0>(u.fast(i)) = pythonic::numpy::functor::sin{}((3.141592653589793 * x.fast(i)));
             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/tmpeser9znt.cpp:22:0:
/usr/local/lib/python3.6/site-packages/pythran/pythonic/__builtin__/pythran/and_.hpp: In instantiation 
of ‘{anonymous}::pythonic::types::lazy_combined_t<T0, T1> {anonymous}::pythonic::__builtin__::pythran::
and_(T0&&, T1&&) [with T0 = __pythran_wave::wave::operator()(argument_type0&&) const [with argument_typ
e0 = long int&; typename __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythoni
c::types::ndarray<double, 2>]::<lambda()>; T1 = __pythran_wave::wave::operator()(argument_type0&&) cons
t [with argument_type0 = long int&; typename __pythran_wave::wave::type<argument_type0>::result_type = 
{anonymous}::pythonic::types::ndarray<double, 2>]::<lambda()>; {anonymous}::pythonic::types::lazy_combi
ned_t<T0, T1> = {anonymous}::pythonic::types::ndarray<bool, 1>]’:                                     
/tmp/tmpeser9znt.cpp:190:51:   required from ‘typename __pythran_wave::wave::type<argument_type0>::resu
lt_type __pythran_wave::wave::operator()(argument_type0&&) const [with argument_type0 = long int&; type
name __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythonic::types::ndarray<do
uble, 2>]’                                                                                            
/tmp/tmpeser9znt.cpp:224:68:   required from here
/usr/local/lib/python3.6/site-packages/pythran/pythonic/__builtin__/pythran/and_.hpp:21:7: error: could
 not convert ‘val0’ from ‘{anonymous}::pythonic::types::numpy_expr<{anonymous}::pythonic::operator_::fu
nctor::ge, {anonymous}::pythonic::types::numpy_iexpr<const {anonymous}::pythonic::types::ndarray<double
, 2>&>, {anonymous}::pythonic::types::broadcast<double, long int> >’ to ‘bool’                        
       if (val0)
       ^~
WARNING  Compilation error, trying hard to find its origin...
WARNING  Nop, I'm going to flood you with C++ errors!
CRITICAL Cover me Jack. Jack? Jaaaaack!!!!
E: error: Command "g++ -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDE
BUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-s
trong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m
64 -mtune=generic -fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DENABLE_PYTHON_MODULE
 -D__PYTHRAN__=3 -DUSE_BOOST_SIMD -DPYTHRAN_BLAS_BLAS -I/usr/local/lib/python3.6/site-packages/pythran 
-I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/usr/local/lib64/python3.6/site-package
s/numpy/core/include -I/usr/include/python3.6m -c /tmp/tmpeser9znt.cpp -o /tmp/tmpz_3lvxpu/tmp/tmpeser9
znt.o -std=c++11 -fno-math-errno -w -fvisibility=hidden -fno-wrapv -march=native -Ofast -fopenmp" faile
d with exit status 1 

I searched all over your documentation and didnt find any solution to this. Could you please help me out? It is critical if I will use pythran to write scientific computations if I can have logical statements with arrays like x[i]>=some number. 

thank you in advance

**Comment by serge-sans-paille** [comment]
Looks cool! I'll check your issue, thanks for reporting o/

**Comment by serge-sans-paille** [comment]
Should be fixed by #884 , I have good speedups on your test case :-)

**Comment by svretina** [comment]
So, I should just update my pythran version and it will be fixed? I am new to github, and more thorough explanations will be appreciated. Thanks for taking the time to answer me!

**Comment by serge-sans-paille** [comment]
On Sat, Apr 28, 2018 at 06:07:30AM -0700, Stamatis Vretinaris wrote:
> So, I should just update my pythran version and it will be fixed? I am new to
> github, and more thorough explanations will be appreciated. Thanks for taking
> the time to answer me!

In that case you can either:

- wait for next pythran release (typically a few months)

- install from source, which basically mean:

```
git clone https://github.com/serge-sans-paille/pythran.git -b feature/ndarray-bool
cd pythran
python setup.py install
```

**Comment by svretina** [comment]
Thank you very much ! I will upload my results on my github with further tests if anyone is interested for pythran applications on astrophysics/physics codes. Thank you again!

**Comment by serge-sans-paille** [comment]
You can also submit a blogpost to https://github.com/serge-sans-paille/pythran-stories, It will get published to http://serge-sans-paille.github.io/pythran-stories/

**Comment by serge-sans-paille** [comment]
I just pushed --force a new version that fixes a compilation issue, so if you cloned the repo, the easier for you is to remove it then repeat the process above.

**Comment by svretina** [comment]
Alright, I just cloned the repo and installed it. And the 'bool' error is gone! But...


/tmp/tmpejhhh0pg.cpp: In instantiation of ‘typename __pythran_wave::wave::type<argument_type0>::result_
type __pythran_wave::wave::operator()(argument_type0&&) const [with argument_type0 = long int&; typenam
e __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythonic::types::ndarray<doubl
e, 2>]’:                                                                                              
/tmp/tmpejhhh0pg.cpp:201:68:   required from here
/tmp/tmpejhhh0pg.cpp:181:34: error: cannot convert ‘std::enable_if<true, {anonymous}::pythonic::types::
numpy_expr<{anonymous}::pythonic::numpy::functor::sin, {anonymous}::pythonic::types::numpy_expr<{anonym
ous}::pythonic::operator_::functor::mul, {anonymous}::pythonic::types::broadcast<double, double>, {anon
ymous}::pythonic::types::numpy_iexpr<const {anonymous}::pythonic::types::ndarray<double, 2>&> > > >::ty
pe {aka {anonymous}::pythonic::types::numpy_expr<{anonymous}::pythonic::numpy::functor::sin, {anonymous
}::pythonic::types::numpy_expr<{anonymous}::pythonic::operator_::functor::mul, {anonymous}::pythonic::t
ypes::broadcast<double, double>, {anonymous}::pythonic::types::numpy_iexpr<const {anonymous}::pythonic:
:types::ndarray<double, 2>&> > >}’ to ‘double’ in assignment                                          
           std::get<0>(u.fast(i)) = pythonic::numpy::functor::sin{}((3.141592653589793 * x.fast(i)));
           ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/tmp/tmpejhhh0pg.cpp: In instantiation of ‘typename __pythran_wave::wave::type<argument_type0>::result_
type __pythran_wave::wave::operator()(argument_type0&&) const [with argument_type0 = long int&; typenam
e __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythonic::types::ndarray<doubl
e, 2>]’:                                                                                              
/tmp/tmpejhhh0pg.cpp:201:68:   required from here
/tmp/tmpejhhh0pg.cpp:181:34: error: cannot convert ‘std::enable_if<true, {anonymous}::pythonic::types::
numpy_expr<{anonymous}::pythonic::numpy::functor::sin, {anonymous}::pythonic::types::numpy_expr<{anonym
ous}::pythonic::operator_::functor::mul, {anonymous}::pythonic::types::broadcast<double, double>, {anon
ymous}::pythonic::types::numpy_iexpr<const {anonymous}::pythonic::types::ndarray<double, 2>&> > > >::ty
pe {aka {anonymous}::pythonic::types::numpy_expr<{anonymous}::pythonic::numpy::functor::sin, {anonymous
}::pythonic::types::numpy_expr<{anonymous}::pythonic::operator_::functor::mul, {anonymous}::pythonic::t
ypes::broadcast<double, double>, {anonymous}::pythonic::types::numpy_iexpr<const {anonymous}::pythonic:
:types::ndarray<double, 2>&> > >}’ to ‘double’ in assignment                                          
           std::get<0>(u.fast(i)) = pythonic::numpy::functor::sin{}((3.141592653589793 * x.fast(i)));
           ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARNING  Compilation error, trying hard to find its origin...
WARNING  Nop, I'm going to flood you with C++ errors!
CRITICAL Cover me Jack. Jack? Jaaaaack!!!!
E: error: Command "g++ -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDE
BUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-s
trong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m
64 -mtune=generic -fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DENABLE_PYTHON_MODULE
 -D__PYTHRAN__=3 -DUSE_BOOST_SIMD -DPYTHRAN_BLAS_BLAS -I/usr/local/lib/python3.6/site-packages/pythran-
0.8.5-py3.6.egg/pythran -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/usr/local/lib6
4/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /tmp/tmpejhhh0pg.cpp -o /tmp/
tmpz6s6knor/tmp/tmpejhhh0pg.o -std=c++11 -fno-math-errno -w -fvisibility=hidden -fno-wrapv -march=nativ
e -Ofast -fopenmp" failed with exit status 1   

 
this came up this time... It has to do with the line: u[i][0] = np.sin(np.pi*x[i])
is it my fault or because of the new feature ndarray.bool ?

**Comment by svretina** [comment]
Changing the above line to u[i][0] = x[i] ( because the u[i][0] = np.sin(np.pi *i) for example worked )
i get this message if it helps more:

/tmp/tmph9_pgsdd.cpp: In instantiation of ‘typename __pythran_wave::wave::type<argument_type0>::result_
type __pythran_wave::wave::operator()(argument_type0&&) const [with argument_type0 = long int&; typenam
e __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythonic::types::ndarray<doubl
e, 2>]’:                                                                                              
/tmp/tmph9_pgsdd.cpp:193:68:   required from here
/tmp/tmph9_pgsdd.cpp:173:34: error: cannot convert ‘{anonymous}::pythonic::types::numpy_iexpr<const {an
onymous}::pythonic::types::ndarray<double, 2>&>’ to ‘double’ in assignment                            
           std::get<0>(u.fast(i)) = x.fast(i);
/tmp/tmph9_pgsdd.cpp: In instantiation of ‘typename __pythran_wave::wave::type<argument_type0>::result_
type __pythran_wave::wave::operator()(argument_type0&&) const [with argument_type0 = long int&; typenam
e __pythran_wave::wave::type<argument_type0>::result_type = {anonymous}::pythonic::types::ndarray<doubl
e, 2>]’:                                                                                              
/tmp/tmph9_pgsdd.cpp:193:68:   required from here
/tmp/tmph9_pgsdd.cpp:173:34: error: cannot convert ‘{anonymous}::pythonic::types::numpy_iexpr<const {an
onymous}::pythonic::types::ndarray<double, 2>&>’ to ‘double’ in assignment                            
           std::get<0>(u.fast(i)) = x.fast(i);
WARNING  Compilation error, trying hard to find its origin...
WARNING  Nop, I'm going to flood you with C++ errors!
CRITICAL Cover me Jack. Jack? Jaaaaack!!!!
E: error: Command "g++ -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDE
BUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-s
trong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m
64 -mtune=generic -fasynchronous-unwind-tables -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DENABLE_PYTHON_MODULE
 -D__PYTHRAN__=3 -DUSE_BOOST_SIMD -DPYTHRAN_BLAS_BLAS -I/usr/local/lib/python3.6/site-packages/pythran-
0.8.5-py3.6.egg/pythran -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I/usr/local/lib6
4/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /tmp/tmph9_pgsdd.cpp -o /tmp/
tmpe8svh3za/tmp/tmph9_pgsdd.o -std=c++11 -fno-math-errno -w -fvisibility=hidden -fno-wrapv -march=nativ
e -Ofast -fopenmp" failed with exit status 1
