### ISSUE TITLE
wrong (numpy) calculations

### ISSUE THREAD

**Issue by svretina** [serge-sans-paille/pythran#885]
I start a new thread, since the ndarray.bool solved the previous problem and the code compiles!

I will repost the code: 

#pythran export wave(int)
import numpy as np

def wave(n):

    Nx = n
    number_of_threads = 4
    t0 = 0
    x0 = 0
    alpha = np.sqrt(2.)/np.pi
    dx = 12./Nx
    dt = 0.5*dx/alpha
    Nt = int(5.*np.pi/dt)
    c = alpha*dt/dx
    u = np.zeros((Nx,Nt))
    x = np.zeros(Nx)
    t = np.zeros(Nt)

    #omp parallel for num_threads(number_of_threads) private(i) shared(Nx,x0,x,dx)
    for i in range(Nx):
        x[i] = x0+i*dx

    #omp parallel for num_threads(number_of_threads) private(i) shared(Nt,t0,dt,t)
    for i in range(Nt):
        t[i] = t0 + i*dt
    
    for i in range(Nx):
        if x[i]>=2 and x[i]<=4:
            u[i,0] = np.sin(np.pi*x[i])
        else:
            u[i,0] = 0
        #omp parallel for shared(Nt,u) private(j)
        for j in range(Nt):
            u[0,j]=0
            u[Nx-1,j]=0

    for j in range(Nt-1):
        #omp parallel for num_threads(number_of_threads) private(i) shared(u,Nx,j,c)
        for i in range(Nx-1):
            u[i,j+1]=u[i,j]-(c/2.)*(u[i+1,j]-u[i-1,j])+(np.power(c,2.)/2.)*(u[i+1,j]-2.*u[i,j]+u[i-1,j])
    print(u[:,0])
    return u

u[:,0] is actually the initial wave that will be computed in time. So the correct form would be 
sin(πx) but I get something weird computed by the pythran module as you can see in the following image:

https://drive.google.com/open?id=1O9r_iqtTKaRwiawrGfRkEwJkicc4GJI8
I printed the u[:,0] from inside the module, or the calculation itself and it gives strange incorrect numbers.

**Comment by serge-sans-paille** [comment]
The following sessions looks ok to me:

```
% python -c 'import w; print(w.wave(4))'
[[ 0.00000000e+00 -4.59242550e-17 -6.88863825e-17 -7.31917814e-17]
 [ 3.67394040e-16  2.75545530e-16  1.72215956e-16  7.74971803e-17]
 [ 0.00000000e+00  1.37772765e-16  2.06659147e-16  2.19575344e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
% pythran w.py
% python -c 'import w; print(w.wave(4))'
[[ 0.00000000e+00 -4.59242550e-17 -6.88863825e-17 -7.31917814e-17]
 [ 3.67394040e-16  2.75545530e-16  1.72215956e-16  7.74971803e-17]
 [ 0.00000000e+00  1.37772765e-16  2.06659147e-16  2.19575344e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
```

How are you compiling? Which compiler options?

**Comment by serge-sans-paille** [comment]
Great, closing the issue :-)
