### ISSUE TITLE
np.arange does not like int parameter on macos

### ISSUE THREAD

**Issue by jeanlaroche** [serge-sans-paille/pythran#894]
On MacOs, the following code does not compile. It compiles fine in linux.
Error log:
[error.txt](https://github.com/serge-sans-paille/pythran/files/1972721/error.txt)

```
import numpy as np

#pythran export test(int)
def test(M):
    # n = np.arange(0, float(M)) <- Compiles
    n = np.arange(0, M) <- Does not compile.
    return n
```

**Comment by jeanlaroche** [comment]
Still not fixed at https://github.com/serge-sans-paille/pythran/commit/c3dd1ef72aa7de51d84ab25ea4d936101d8a5802

**Comment by serge-sans-paille** [comment]
Does #921 fix the issue?

**Comment by jeanlaroche** [comment]
Confirmed fixed with https://github.com/serge-sans-paille/pythran/pull/921 on macos! Yepee!
