### ISSUE TITLE
Numpy functions like trapz

### ISSUE THREAD

**Issue by svretina** [serge-sans-paille/pythran#895]
Hello again, I am trying to implement a simple function that needs integration. Is calling functions like 
trapz supported by pythran? I get this:

```
CRITICAL I am in trouble. Your input file does not seem to match Pythran's cons
traints...                                                                    
E: identifier 'trapz' not found in module 'numpy' (line 1)
```

**Comment by jeanlaroche** [comment]
Typically this means it hasn't been implemented. What I do in such case is either:
- Write my own version in standard numpy then pythranize that (works quite well)
- Add it to pythran (there's a learning curve, it has to be in C++, but it's not that bad).

**Comment by svretina** [comment]
ok understood! If I have the time and write something in C++ I will share it. Thanks.

**Comment by jeanlaroche** [comment]
BTW you can find the source code of trapz here:
https://github.com/numpy/numpy/blob/master/numpy/lib/function_base.py 

That would be easy to simply pythranize...

**Comment by serge-sans-paille** [comment]
> Is calling functions like trapz supported by pythran? I get this:

It's just not implemented :-)

The code source i need to port is here:

    https://github.com/numpy/numpy/blob/d1a661df48625ce5544d83dc022c96cf8c5d41c7/numpy/lib/function_base.py#L3016
