### ISSUE TITLE
strange function docstring

### ISSUE THREAD

**Issue by nbecker** [serge-sans-paille/pythran#897]
This pythran code:

``
#pythran export Decoding_logBP(int[:,:], int list list, int list list, float[:,:], float[:], int)
def Decoding_logBP(H,Bits,Nodes,Lq,Lc,max_iter=1):
``

Gives:
```
In [49]: G.Decoding_logBP?
Docstring:
Decoding function using Belief Propagation algorithm (logarithmic version)

Supported prototypes:

- Decoding_logBP(int[][], int list list, int list list, float[][], float[], int)
- Decoding_logBP(int[][], int list list, int list list, float[][].T, float[], int)
- Decoding_logBP(int[][].T, int list list, int list list, float[][], float[], int)
- Decoding_logBP(int[][].T, int list list, int list list, float[][].T, float[], int)
...
```
What's with the int[][].T, etc?

**Comment by serge-sans-paille** [comment]
Hi nbecker. int[][] <> int[:,:,]. I'll update the generated docstring to use numpy-style notation!

**Comment by serge-sans-paille** [comment]
Should be fixed in #898

**Comment by nbecker** [comment]
No, I mean why are there 4 prototypes?  Why do 2 of them say blah[][].T?  What is the significance of the ".T"?

**Comment by serge-sans-paille** [comment]
it means it accepts the transposed version :-)
