### ISSUE TITLE
pythran in conda-forge

### ISSUE THREAD

**Issue by saraedum** [serge-sans-paille/pythran#907]
Currently pythran does not seem to be in conda-forge. Is that because the GCC there is not sufficiently recent? Would you mind me giving a try at packaging it there?

**Comment by serge-sans-paille** [comment]
That's a great proposal. I maintain my own conda channel (https://anaconda.org/serge-sans-paille/pythran) but I'm okay to switch to conda-forge. The only trick i use is the following:

```
#!/bin/bash
sed -i -e 's,CC=,CC=/opt/anaconda1anaconda2anaconda3/bin/gcc-4.9,' -e 's,CXX=,CXX=/opt/anaconda1anaconda2anaconda3/bin/g++-4.9,' -e 's,library_dirs=,library_dirs=/opt/anaconda1anaconda2anaconda3/lib ,' -e 's,include_dirs=,include_dirs=/opt/anaconda1anaconda2anaconda3/include ,' -e 's|ldflags=|ldflags=-Wl,-rpath /opt/anaconda1anaconda2anaconda3/lib64 |' pythran/pythran-linux2.cfg
sed -i -e 's,CC=,CC=/opt/anaconda1anaconda2anaconda3/bin/gcc-4.9,' -e 's,CXX=,CXX=/opt/anaconda1anaconda2anaconda3/bin/g++-4.9,' -e 's,library_dirs=,library_dirs=/opt/anaconda1anaconda2anaconda3/lib ,' -e 's,include_dirs=,include_dirs=/opt/anaconda1anaconda2anaconda3/include ,' -e 's|ldflags=|ldflags=-Wl,-rpath /opt/anaconda1anaconda2anaconda3/lib64 |' pythran/pythran-linux.cfg

$PYTHON setup.py install
```

in the build.sh

Concerning the releases, what is the process when using conda forge? i usually

1. upload the new version on pypi
2. update my build recipe on my conda setup
3. build the conda packages and upload them

**Comment by saraedum** [comment]
With conda-forge you create a new release on pypi or github, and either wait for the @regro-cf-autotick-bot to pick it up automatically or just bump the version number in the recipe. Building and uploading is fully automatic.

**Comment by saraedum** [comment]
This would probably also fix #747.

**Comment by saraedum** [comment]
@serge-sans-paille is `third_party/boost` patched, or can I use standard boost headers here?

**Comment by serge-sans-paille** [comment]
The standard header are ok, they just also include a copy of the non
official boost.simd package.

I can merge #733 if that's helpful for you.

**Comment by saraedum** [comment]
No worries, I don't mind distributing the boost headers for a first version.

**Comment by saraedum** [comment]
Is there a reason why setup.py asks for pytest-runner at build time?

**Comment by serge-sans-paille** [comment]
for testing purpose, some users wanted to be able to run the tests and choke on the missing dep, so i included it.

**Comment by Dapid** [comment]
I think the correct way is to add tests_require=['pytest'] in the setup.py:setup call. This way, `python setup.py test` will install and run the tests, and `pip install pythran[test]` will pull it in too, but not by default.

**Comment by serge-sans-paille** [comment]
Thanks @saraedum for the good work: https://anaconda.org/conda-forge/pythran
