### ISSUE TITLE
Flags not being passed from setup.py

### ISSUE THREAD

**Issue by Dapid** [serge-sans-paille/pythran#920]
I have written a module that works very well when compiling it with `pythran -fopenmp -ftree-vectorize _gdca.py`. I am not managing to get the same results when building through pip. This is what I have in the setup.py:

```
module_gdca = PythranExtension('gaussdca._gdca', sources=['gaussdca/_gdca.py'],
                               extra_compile_args=['-fopenmp', '-ftree-vectorize'])

setuptools.setup(...       ext_modules=[module_parse, module_gdca])
```

What  am I doing wrong here?

**Comment by serge-sans-paille** [comment]
Thanks for the report! If I'm not mistaken #922 should fix the bug.

**Comment by Dapid** [comment]
Thanks!
Can we get this in a release soon-ish? We are writing a paper where one of the points is that we have faster and easier to install and deploy reimplementation, thanks in no small part to Pythran. Almost 3 times faster than Julia, and skipping some ugly tricks!

**Comment by serge-sans-paille** [comment]
great! I'd be happy to proof-read the paper if you want. I'll do a minor release next week if that's ok with you?
