### ISSUE TITLE
string literal comparison

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#927]
The i variable is here to avoid pythran static evaluation

```
def eee(a, i):
    if a == "ABCD":
        return 2 * i
    elif a == "ZDSD":
        return 1 * i
    return 3 * i

# pythran export abcd(str, int)
def abcd(a, i):
    if a == "EEE":
       return eee("ZZZ", i)
    else:
       return eee("YYY", i)
```

Here one of the warnings from gcc

> pythranstr.cpp:53:12: warning: comparison with string literal results in unspecified behaviour [-Waddress]
>      if ((a == "ABCD"))
>             ^
> pythranstr.cpp:59:14: warning: comparison with string literal results in unspecified behaviour [-Waddress]
>        if ((a == "ZDSD"))

**Comment by diorcety** [comment]
Regardings < and > ? https://stackoverflow.com/questions/34710483/string-comparison-less-than-sign

**Comment by serge-sans-paille** [comment]
Yeah, I need to implement that too, thanks for reminding :-)

**Comment by serge-sans-paille** [comment]
@diorcety what about #942 ?

**Comment by serge-sans-paille** [comment]
my bad, this PR is buggy, keep in touch :-)

**Comment by serge-sans-paille** [comment]
should be better now :-)

**Comment by serge-sans-paille** [comment]
@diorcety PR #942 is up and ready, can you confirm it's ok for you?

**Comment by diorcety** [comment]
:+1:
