### ISSUE TITLE
Lambda issue

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#951]
I can't compile the following code using pythran:
`TypeError: 'ReturnType' object does not support indexing`

```
# pythran export aa(int, int, str)
def aa(a, c, s): 
  if s == "a":
    x = lambda y:y 
  else:
    x = lambda y:y+c
  return x(a)

```

**Comment by serge-sans-paille** [comment]
Thanks for reporting! I can reproduce the issue, working on it :-)
