### ISSUE TITLE
Regression with fast

### ISSUE THREAD

**Issue by diorcety** [serge-sans-paille/pythran#960]
I can't compile this code anymore

```
import numpy as np

#pythran export xxx(int32[][] list, int32[][])
def xxx(a, b=None):
    if b is None:
        assert len(a) > 0
        b = np.copy(a[0])
        a = a[1:]
    else:
        b = np.copy(b)
    m = b >= 0
    for array in a:
        b[m] *= array[m]
return b
```

**Comment by serge-sans-paille** [comment]
looks related to your texpr / shape issue ?

**Comment by diorcety** [comment]
What do you mean?

**Comment by serge-sans-paille** [comment]
Does #957 solves the issue?

**Comment by diorcety** [comment]
No no. I have already apply it on my branch

**Comment by diorcety** [comment]
> /home/yann/virtualenvs/pythran/lib/python3.5/site-packages/pythran-0.8.6.dev0+x-py3.5.egg/pythran/pythonic/types/numpy_texpr.hpp:171:12: error: no viable conversion from returned value of type 'typename std::enable_if<is_numexpr_arg<ndarray<long, pshape<long> > >::value && !std::is_same<bool, typename ndarray<long, pshape<long> >::dtype>::value, ndarray<dtype, pshape<long, long> > >::type' (aka '(anonymous namespace)::pythonic::types::ndarray<int, (anonymous namespace)::pythonic::types::pshape<long, long> >') to function return type 'typename std::enable_if<is_numexpr_arg<ndarray<bool, pshape<long, long> > >::value && std::is_same<bool, typename ndarray<bool, pshape<long, long> >::dtype>::value, numpy_vexpr<numpy_texpr_2<ndarray<int, pshape<long, long> > >, ndarray<long, pshape<long> > > >::type' (aka '(anonymous namespace)::pythonic::types::numpy_vexpr<(anonymous namespace)::pythonic::types::numpy_texpr_2<(anonymous namespace)::pythonic::types::ndarray<int, (anonymous namespace)::pythonic::types::pshape<long, long> > >, (anonymous namespace)::pythonic::types::ndarray<long, (anonymous namespace)::pythonic::types::pshape<long> > >')
>     return this->fast(
>

**Comment by serge-sans-paille** [comment]
ok, I'll check this, thanks!

**Comment by diorcety** [comment]
Seems to compile now. I have still other compilation issue, after that I run my test suite again.
