### ISSUE TITLE
Scipy.special backend for Bessel functions

### ISSUE THREAD

**Issue by Chronum94** [serge-sans-paille/pythran#994]
How difficult would it be to implement this? They're very commonly used in a lot of physics problems in spherical coordinates, and Boost has them, so they can be used from there. It would be really nice to have these functions supported.

On a related note, fantastic package. Much appreciated.

**Comment by serge-sans-paille** [comment]
That sounds feasible. Can you list the exact name of the functions you need?

**Comment by Chronum94** [comment]
From https://docs.scipy.org/doc/scipy-0.19.1/reference/special.html

`jv`, `yv`, `kv`, `iv`, and their derivatives, which have are `jvp`, `yvp`, etc. Optionally, `hankel1`, `hankel2` would also be great to have, and also exist in Boost special functions.

**Comment by serge-sans-paille** [comment]
ok! Will have a look at it :-)

**Comment by serge-sans-paille** [comment]
Fixed by #1005 !
