### ISSUE TITLE
Python build-in slice function

### ISSUE THREAD

**Issue by ucyo** [serge-sans-paille/pythran#996]
Hi there,

support for the build-in slice function of Python would be nice...

```python
import numpy as np

#pythran export mel_p(int)
def mel_p(M):
    A = np.ones(M+10)
    # result = A[2::]  # works
    result = A[slice(2,None,None)]  # compile error
    return result
```

**Comment by serge-sans-paille** [comment]
Hi ucyo, thanks for the report! This looks perfectly feasible.

**Comment by serge-sans-paille** [comment]
@ucyo can you confirm #999 fixes your issue?

**Comment by ucyo** [comment]
Thank you. The example above is compiling. My actual use case throws some C++ errors, but that might be another problem :+1:
